#!/usr/bin/env python3
"""Generate remaining Joshua commentary."""

import json

# Load existing commentary
with open('kjvstudy_org/data/verse_commentary/joshua.json', 'r') as f:
    data = json.load(f)

# Ensure chapters exist
for ch in ['15', '17', '18', '19', '20', '22', '24']:
    if ch not in data['commentary']:
        data['commentary'][ch] = {}

# Joshua 15:54-63 - Cities in Judah's hill country and the Jebusite note
commentary_15 = {
    '54': {
        "analysis": "<strong>And Humtah, and Kirjath-arba, which is Hebron, and Zior; nine cities with their villages:</strong><br><br>This verse continues enumerating Judah's hill country cities, mentioning <strong>Kirjath-arba, which is Hebron</strong>—reminding readers of this city's former identity under Anakim control before Caleb's conquest (Joshua 14:15). The repetition of Hebron's dual name throughout Joshua emphasizes transformation: what was Arba's (giant-clan) city became Abraham's sacred site and now Caleb's inheritance. Names change when kingdoms change hands.<br><br>The hill country (<em>har</em>, הָר) represented the spine of Judah's territory—more defensible than lowlands but requiring terrace agriculture. These nine cities formed a cluster in the southern Judean highlands, providing regional administration and defense. God's provision included both the impressive (Hebron) and the obscure (Humtah, Zior)—every settlement mattered in the territorial fabric. No city was too small for biblical record; God numbers sparrows and hairs (Matthew 10:29-30), much more human communities.",
        "questions": [
            "How do changed names (like Kirjath-arba to Hebron) in your life testify to God's transforming work?",
            "What does God's attention to both major cities and obscure villages teach about His care for all believers, prominent and unknown?",
            "How does living in 'hill country' (more difficult but defensible terrain) apply to the Christian life?"
        ],
        "historical": "The Judean hill country extends from Jerusalem south ward to Beersheba, characterized by limestone ridges, narrow valleys, and terraced slopes. This region required intensive agricultural labor (building and maintaining terraces) but provided security from lowland invaders. Cities clustered along ridge routes and near springs. Archaeological surveys reveal hundreds of Iron Age settlements in this zone, confirming dense occupation during the Israelite period."
    },
    '55': {
        "analysis": "<strong>Maon, Carmel, and Ziph, and Juttah,</strong><br><br>These four cities gain significance through later biblical narratives. <strong>Maon</strong> (<em>Ma'on</em>, מָעוֹן) was home to Nabal the fool, whose wife Abigail's wisdom saved her household and led to her marriage to David (1 Samuel 25). <strong>Carmel</strong> (not Mount Carmel in the north, but a Judean town) was where David's men protected Nabal's shepherds and where Abigail intercepted David's vengeance. <strong>Ziph</strong> (<em>Zif</em>, זִיף) appears in David's wilderness wanderings—the Ziphites twice betrayed David's location to Saul (1 Samuel 23:19; 26:1), yet David spared Saul's life at nearby En-gedi.<br><br>That future biblical events occurred in cities listed here creates narrative anticipation—these names await their stories. Geography is never neutral in Scripture; places become testimonies to human choices and divine providence. Ziph's betrayal, Carmel's foolishness, and Abigail's wisdom all unfolded on this Judean terrain. When we read Joshua's dry city lists, we're actually encountering future drama in embryo form—the stage where God's redemptive history will unfold.",
        "questions": [
            "How does knowing the future stories of these cities (David, Nabal, Abigail) change how you read city lists in Scripture?",
            "What 'geography' (circumstances, relationships, places) in your life is God preparing for future purposes you can't yet see?",
            "How should Christians view seemingly mundane details (like city lists) in Scripture—what treasure might they contain?"
        ],
        "historical": "Maon (Khirbet Ma'in) sits about 8 miles south of Hebron in rugged wilderness terrain—the 'wilderness of Maon' where David fled from Saul. Carmel (Khirbet el-Kirmil) lies about a mile north of Maon, remembered for Nabal's foolishness and Abigail's intervention. Ziph (Tell Ziph) was fortified by Rehoboam (2 Chronicles 11:8) and appears in the Lachish letters. The 'wilderness of Ziph' served as David's hiding place, demonstrating how Judean wilderness areas between settled zones provided refuge for outlaws and rebels. These wildernesses would later host monastic communities seeking spiritual solitude."
    },
    '56': {
        "analysis": "<strong>And Jezreel, and Jokdeam, and Zanoah,</strong><br><br><strong>Jezreel</strong> (not the famous northern valley, but a Judean town) later became home to Ahinoam, one of David's wives (1 Samuel 27:3; 30:5). This demonstrates how personal family histories intersect with tribal geography—David's marriages connected him to various Judean regions, strengthening his tribal base. Biblical characters aren't abstracted from place; they're rooted in specific locations with their own histories and associations.<br><br>These seemingly tedious lists of cities actually map the stage for Israel's entire history. Every prophet, every king, every major event occurs somewhere listed in these chapters. When Jeremiah prophesies or Amos denounces or David flees, they move through landscapes catalogued here in Joshua. Understanding biblical geography isn't mere academic exercise—it grounds theological truth in physical reality, preventing spiritualization that detaches faith from embodied, located human experience.",
        "questions": [
            "How does biblical faith's insistence on specific geography and history challenge modern tendencies toward abstract spirituality?",
            "What locations in your life have spiritual significance, and how do you commemorate God's work in specific places?",
            "Why might God care about preserving city lists that seem tedious to modern readers?"
        ],
        "historical": "Jezreel (Khirbet Terrama or nearby) was a small Judean town distinct from the more famous Jezreel Valley in northern Israel. That two significant places share the same name (meaning 'God sows') shows how biblical names often reflect theological themes rather than unique identifiers. Zanoah (probably Khirbet Zanu) appears in Nehemiah 3:13 and 11:30, showing continuous occupation from Joshua through the post-exilic period—nearly a millennium of community life rooted in this Judean landscape."
    },
    '57': {
        "analysis": "<strong>Cain, Gibeah, and Timnah; ten cities with their villages:</strong><br><br><strong>Gibeah</strong> later becomes infamous as the site of the Benjamite atrocity (Judges 19-20) and as Saul's hometown and capital (1 Samuel 10:26; 15:34). That Gibeah belonged to Judah originally but appears in Judges as Benjamite shows tribal boundary adjustments occurred over time—either through negotiation or conflict. Boundaries recorded in Joshua weren't eternally frozen but formed baseline agreements subject to later modification.<br><br><strong>Timnah</strong> appears in Samson's story as a Philistine town (Judges 14:1), though listed here as Judean—another instance of contested or transitional boundary zones. The Shephelah (lowland hills between Judah's mountains and Philistine coastal plain) remained a friction zone throughout Israel's history, with cities changing hands repeatedly. Geography shaped political reality: transitional zones created ongoing conflict, while natural barriers (mountains, deserts, seas) provided stable boundaries.",
        "questions": [
            "How do you navigate 'boundary zones' in your life—areas of contested values or competing loyalties—while maintaining covenant faithfulness?",
            "What does the fluidity of some boundaries (cities changing tribal affiliation) teach about both the importance and limits of institutional structures?",
            "How should Christians think about place-based community in an increasingly mobile society?"
        ],
        "historical": "Gibeah's location is debated—possibly Tell el-Ful north of Jerusalem or elsewhere. Saul's Gibeah was fortified and excavated by W.F. Albright, revealing an Early Iron Age citadel consistent with Saul's rustic kingship. The Gibeah outrage (Judges 19) nearly destroyed Benjamin, showing how moral corruption in one city could threaten an entire tribe. Timnah (Tell Batash) in the Sorek Valley was a border city between Judah and Philistia, excavated extensively and showing multiple destruction/rebuilding phases consistent with its contested status."
    },
    '58': {
        "analysis": "<strong>Halhul, Beth-zur, and Gedor,</strong><br><br><strong>Beth-zur</strong> (<em>Bet-Tsur</em>, בֵּית צוּר, 'house of rock') gained prominence in the Maccabean period as a key fortress defending Jerusalem's southern approaches (1 Maccabees 4:29, 61; 6:7). This demonstrates how sites listed in Joshua remained strategically important centuries later—geography's military logic transcends political regimes. High points, water sources, and passes retain value regardless of who controls them. God's gift of land included inherent strategic advantages that would benefit Israel for generations.<br><br>The recurrence of 'Beth-' names (Beth-zur, Beth-lehem, Beth-shemesh, etc.) reflects the Hebrew practice of identifying settlements by their primary feature or function: beth meaning 'house/place.' These names create semantic landscapes—toponyms that describe rather than merely label. In contrast to abstract modern place names, biblical names often reveal something essential about the location. Christians similarly should let our language bear meaning, naming things truly and avoiding empty abstraction.",
        "questions": [
            "What 'strategic heights' or 'strongholds' (mental, spiritual, relational) has God given you to steward faithfully?",
            "How does the practice of meaningful naming (places, children, initiatives) reflect and shape spiritual awareness?",
            "What modern tendencies toward abstraction or euphemism need to be replaced with truthful naming?"
        ],
        "historical": "Beth-zur (Khirbet et-Tubeiqah) sits on a 3,000-foot elevation ridge about 20 miles south of Jerusalem, commanding the Hebron road. Archaeological excavations revealed fortifications from multiple periods, including impressive Hellenistic walls from the Maccabean era. The site's strategic value remained constant across centuries—whoever held Beth-zur controlled access between Jerusalem and Hebron. Halhul (modern Halhul) remains a living town north of Hebron, representing rare continuity in toponymy from biblical times to present."
    },
    '59': {
        "analysis": "<strong>And Maarath, and Beth-anoth, and Eltekon; six cities with their villages:</strong><br><br>These lesser-known cities remind us that most biblical history occurred in obscure places, not famous capitals. God's attention to 'Maarath' and 'Beth-anoth'—cities with no recorded biblical narratives—teaches that significance doesn't require fame. Most faithful Israelites lived unremarkable lives in unremarkable towns, yet their faithfulness sustained the nation. The majority of Christian history likewise consists of unknown believers in forgotten places who loved God, raised families, practiced justice, and transmitted faith—the invisible foundations supporting visible heroes.<br><br>The persistent enumeration of cities 'with their villages' (<em>ve-chatserehen</em>, וַחֲצֵרֵיהֶן) acknowledges the symbiotic relationship between urban and rural settlements. Cities provided defense, administration, and markets; villages supplied food and labor. Neither survived independent of the other. This mutual dependence pictures the body of Christ where diverse members contribute complementary functions (1 Corinthians 12:12-27). Visible leaders depend on invisible supporters; prominent ministries rest on faithful givers and prayers unknown to the world.",
        "questions": [
            "How does God's preservation of obscure city names encourage you if your service feels unnoticed or unremarkable?",
            "What 'villages' (supporting roles, unglamorous service) sustain the 'cities' (visible achievements) in your Christian community?",
            "How can you cultivate contentment in obscurity rather than seeking recognition and platform?"
        ],
        "historical": "Little is known about Maarath, Beth-anoth, and Eltekon beyond their mentions in city lists. This obscurity itself is significant—archaeology has identified hundreds of small Iron Age settlements in Judah that left no dramatic history, no destruction layers famous in textbooks, no artifacts in museums. These villages comprised Israel's demographic and economic base, their farmers and shepherds the 'people of the land' whose labor fed cities and supplied armies. Without them, the dramatic events of kings and prophets couldn't have occurred."
    },
    '60': {
        "analysis": "<strong>Kirjath-baal, which is Kirjath-jearim, and Rabbah; two cities with their villages:</strong><br><br><strong>Kirjath-jearim</strong> (<em>Qiryat-Ye'arim</em>, קִרְיַת יְעָרִים, 'city of forests') plays a crucial role in later history as the resting place of the Ark of the Covenant for twenty years after its return from Philistine captivity (1 Samuel 7:1-2). David later retrieved it from here (2 Samuel 6:2). That this city's former name was 'Kirjath-baal' (city of Baal) demonstrates Canaanite religious landscape before Israel's settlement—Baal worship permeated the land. The name change from 'Baal' to 'forests' suggests Israelite renaming, purging pagan associations from their geography.<br><br>Yet the renaming wasn't complete erasure—the text preserves both names, acknowledging history rather than pretending it never happened. This pattern appears throughout Scripture: new names don't obliterate old identities but transform them (Abram to Abraham, Jacob to Israel, Saul to Paul). Redemption doesn't deny the past but redeems it, incorporating even shameful history into a larger narrative of grace. Christians are 'new creations' (2 Corinthians 5:17) who nevertheless remember what we were saved from, making God's grace all the more glorious.",
        "questions": [
            "What 'Baal names' (pagan influences, worldly identities) in your life need renaming through God's transforming work?",
            "How does preserving both old and new names (acknowledging past and present) model healthy Christian testimony?",
            "Why did God choose Kirjath-jearim (former Baal-city) as the Ark's temporary home—what does this suggest about redemption geography?"
        ],
        "historical": "Kirjath-jearim (likely Deir el-Azhar or Abu Ghosh) sat on Judah's northern border with Benjamin, about 9 miles west of Jerusalem. The Ark's twenty-year residence there (c. 1070-1050 BCE) represented an anomalous period—the Ark should have been at the Tabernacle but remained at this border town after its Philistine captivity. The city's location on the Jerusalem-coastal plain road made it strategically positioned. That it was originally 'Kirjath-baal' shows how thoroughly Baal worship dominated pre-conquest Canaan—even place names invoked this fertility deity. Israel's settlement required not just military conquest but cultural-religious transformation."
    },
    '61': {
        "analysis": "<strong>In the wilderness, Beth-arabah, Middin, and Secacah,</strong><br><br>This verse shifts to Judah's wilderness (<em>midbar</em>, מִדְבָּר) cities—settlements in the harsh, sparsely populated region between the Judean highlands and the Dead Sea. This wilderness served multiple purposes: refuge for outlaws (David), ascetic retreat (later Jewish sects like Essenes at Qumran), and buffer zone against eastern invaders. That Judah's allotment included both fertile highlands and barren wilderness shows comprehensive inheritance—God's provision encompasses diverse terrains and ecosystems.<br><br>Wilderness holds unique theological significance throughout Scripture. The Israelites wandered forty years in wilderness; Jesus fasted forty days in wilderness; early monks sought wilderness for spiritual formation. Wilderness strips away civilizational comforts, forcing dependence on God alone. It's simultaneously a place of testing and transformation, judgment and grace, deprivation and revelation. That Judah's territory included substantial wilderness meant the tribe would have opportunities for wilderness spirituality—learning lessons unavailable in comfortable cities.",
        "questions": [
            "What 'wilderness' experiences in your life have forced dependence on God and stripped away false securities?",
            "How does Judah receiving both fertile highlands and barren wilderness challenge prosperity gospel assumptions about God's blessings?",
            "What spiritual disciplines or practices constitute healthy 'wilderness' rhythms in ordinary Christian life?"
        ],
        "historical": "The Judean wilderness (midbar Yehudah) is a harsh, rain-shadow desert dropping from the central hill country (2,500+ feet elevation) to the Dead Sea (1,300 feet below sea level) over just 15-20 miles. Steep wadis, exposed rock, minimal vegetation, and extreme temperatures characterize the region. Yet springs at oases (En-gedi) and winter runoff supported some settlement and pastoralism. Beth-arabah ('house of the Arabah/desert') sat at the wilderness edge. Secacah may be near Qumran, where the Dead Sea Scrolls community later flourished, pursuing rigorous desert piety in isolation from corrupt Jerusalem priesthood."
    },
    '62': {
        "analysis": "<strong>And Nibshan, and the city of Salt, and En-gedi; six cities with their villages.</strong><br><br><strong>En-gedi</strong> (<em>En-Gedi</em>, עֵין גֶּדִי, 'spring of the kid/goat') is the wilderness gem—a lush oasis on the Dead Sea's western shore where fresh water creates a verdant haven amid barren surroundings. David hid in En-gedi's caves when fleeing Saul (1 Samuel 24:1), and Solomon's beloved speaks of En-gedi's vineyards (Song of Solomon 1:14). This 'desert paradise' demonstrates God's capacity to provide abundantly even in seeming desolation—springs in dry places, beauty in wastelands, refuge in hostile terrain.<br><br>The 'city of Salt' (<em>Ir-haMelach</em>, עִיר הַמֶּלַח) likely sat near the Dead Sea, whose hyper-salinity (10x ocean salinity) made it lifeless but economically valuable—salt was crucial for food preservation and sacrifice (Leviticus 2:13). That Judah's inheritance included Dead Sea access gave them salt monopoly, turning liability (uninhabitable sea) into asset (valuable commodity). This pattern recurs in God's economy: He transforms what seems disadvantageous into blessing, weakness into strength (2 Corinthians 12:9-10), suffering into glory (Romans 8:18).",
        "questions": [
            "What 'En-gedis' (unexpected oases) has God provided in wilderness seasons of your life?",
            "How might God be transforming your 'Dead Sea' (barren, seemingly useless situation) into economic or spiritual blessing?",
            "What role does wilderness refuge (like David at En-gedi) play in preparing leaders for future responsibilities?"
        ],
        "historical": "En-gedi remains an oasis on the Dead Sea's western shore, fed by springs from the Judean highlands. The site has been occupied since Chalcolithic times (4000s BCE) due to its reliable water. Archaeological excavations revealed an important agricultural-industrial complex producing perfumes and balsam during the Israelite monarchy. The Song of Solomon's reference to 'camphire [henna] in the vineyards of En-gedi' (1:14) reflects this agricultural prosperity amid wilderness. The city of Salt's location is uncertain, but several ancient sites near the Dead Sea's northwestern shore (Qumran, Khirbet Qumran) are candidates. Salt extraction from the Dead Sea and surrounding salt deposits provided a valuable resource."
    },
    '63': {
        "analysis": "<strong>As for the Jebusites the inhabitants of Jerusalem, the children of Judah could not drive them out; but the Jebusites dwell with the children of Judah at Jerusalem unto this day.</strong><br><br>This sobering note records Judah's failure to complete conquest—<strong>the Jebusites</strong> (<em>haYevusi</em>, הַיְבוּסִי) remained in <strong>Jerusalem</strong> (<em>Yerushalaim</em>, יְרוּשָׁלַיִם) until David's time (2 Samuel 5:6-9), nearly 400 years after Joshua. The phrase \"could not drive them out\" (<em>lo yakhlu lehorisham</em>, לֹא יָכְלוּ לְהוֹרִישָׁם) suggests military inability, yet Judges 1:21 (attributing this to Benjamin, whose border also touched Jerusalem) and Joshua 15:63 together indicate the real issue was incomplete obedience rather than insufficient power. Where God commands, He enables; failure to complete conquest reveals half-hearted commitment, not divine impotence.<br><br>Jerusalem's non-conquest had enormous consequences. This Jebusite enclave sat on Judah's northern border, uncomfortably close to the tribal heartland. Yet God used even this failure providentially—when David eventually conquered Jerusalem, its previous neutrality (belonging to neither Judah nor Benjamin) made it ideal as a national capital offending no tribe. What began as disobedient failure became, through David's conquest, a wise solution to tribal politics. God's providence doesn't excuse human failure, but it does weave even our failures into His ultimate purposes (Romans 8:28).<br><br>The phrase \"unto this day\" indicates the author wrote before David's conquest of Jerusalem (c. 1003 BCE), suggesting early composition of at least this section of Joshua. Yet the theological point transcends dating questions: incomplete obedience creates persistent problems. The Jebusites' continued presence tempted Israel toward syncretism and compromise. Tolerated sin doesn't remain static—it grows and corrupts. Christians must likewise pursue complete sanctification, not accepting 'good enough' obedience that leaves strongholds unconquered.",
        "questions": [
            "What 'Jebusites' (unconquered sins, unsubdued habits) remain in your Jerusalem (heart, life) because of incomplete obedience?",
            "How has God providentially used your past failures or incomplete obedience, incorporating them into His larger purposes?",
            "What's the difference between honest acknowledgment of failure (like this verse) and making excuses for ongoing disobedience?"
        ],
        "historical": "The Jebusites were pre-Israelite inhabitants of Jerusalem (also called Jebus in Judges 19:10-11), a Canaanite people-group mentioned among those to be dispossessed (Exodus 3:8, 17; 23:23). Jerusalem sits on a ridge between the Kidron and Hinnom valleys, with natural defenses that made it easily defensible. The Jebusite fortress on the southeastern spur (City of David) relied on these topographical advantages plus the Gihon spring for water.<br><br>Joshua 10:1-27 records Joshua's defeat of Jerusalem's king (Adoni-zedek) in the southern campaign, but this didn't result in occupation—the city remained Jebusite. Judges 1:8 mentions Judah attacking Jerusalem and setting it on fire, yet verse 21 clarifies the Jebusites continued dwelling there. These seemingly contradictory reports likely reflect different phases: raids versus permanent occupation. The city wasn't fully conquered until David's forces entered through the water shaft (2 Samuel 5:8), ending Jebusite independence and establishing Jerusalem as Israel's eternal capital.<br><br>The choice of Jerusalem as capital proved providential despite its origin in incomplete conquest. Its location on the Benjamin-Judah border, its previous neutrality, and its central position in the hill country made it ideal for uniting the northern and southern tribes. Solomon later built the Temple there, and Jerusalem became the spiritual center of Judaism and later Christianity, with enormous eschatological significance (Revelation 21:2)."
    }
}

for verse_num, verse_data in commentary_15.items():
    data['commentary']['15'][verse_num] = verse_data

# Save
with open('kjvstudy_org/data/verse_commentary/joshua.json', 'w') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print("✓ Added commentary for Joshua 15:54-63")
print("Progress: 34/96 verses completed")
