[project]
name = "kjvstudy-org"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "biblepy>=0.1.3",
    "fastapi>=0.115.12",
    "jinja2>=3.1.6",
    "parse>=1.20.2",
    "pytest>=8.3.5",
    "uvicorn>=0.34.2",
]
