#!/usr/bin/env python3
"""Add missing commentary to Job.json"""

import json
from pathlib import Path

# Define all missing verses with their commentary
NEW_COMMENTARY = {
    "23": {
        "14": {
            "analysis": "<strong>For he performeth the thing that is appointed for me</strong> (כִּי־יַשְׁלִים חֻקִּי, <em>ki-yashlim chukki</em>)—The verb <em>shalam</em> (שָׁלַם) means \"to complete, fulfill, finish.\" The noun <em>choq</em> (חֹק) denotes a decreed statute or appointed portion. Job confesses divine sovereignty extends to his personal life: God completes what He has ordained. This echoes Philippians 1:6, \"He which hath begun a good work in you will perform it.\" The phrase <strong>many such things are with him</strong> (וְרַבּוֹת כָּאֵלֶּה עִמּוֹ) amplifies God's comprehensive purposes—not one decree but multitudes. Job's theology is Reformed: God's sovereignty is meticulous, not general.<br><br>Yet Job speaks without comfort. Unlike Philippians' assurance, Job fears what God has appointed. This reveals a profound tension: right doctrine about sovereignty paired with existential terror. The same truths that anchor faith can crush hope if we doubt God's goodness. The gospel resolves this: Christ bore God's appointed decree of wrath (Isaiah 53:10), so we receive appointed grace (Ephesians 1:11).",
            "historical": "Job's theology of divine decrees aligns with ancient Israelite covenant theology, where God's <em>choq</em> (statutes) governed both cosmic order and individual lives. The Wisdom Literature consistently affirms God's comprehensive sovereignty (Proverbs 16:33, 19:21). Job's fear reflects the pre-Christian struggle to reconcile suffering with divine purpose before the cross revealed God's redemptive plan.",
            "questions": [
                "How can you trust God's appointed purposes when you cannot see His ultimate design?",
                "What is the difference between fatalism and biblical sovereignty?",
                "How does Christ's fulfillment of God's appointed decree (Acts 2:23) transform our understanding of divine purpose?"
            ]
        },
        "15": {
            "analysis": "<strong>Therefore am I troubled at his presence</strong> (עַל־כֵּן מִפָּנָיו אֶבָּהֵל, <em>al-ken mippanav ebahel</em>)—The verb <em>bahal</em> (בָּהַל) means \"to be terrified, dismayed, horrified.\" The preposition <em>min-panav</em> (from His face/presence) indicates God Himself is the source of terror. This is the <em>mysterium tremendum</em>—the overwhelming terror of the holy. Job experiences what Isaiah felt: \"Woe is me!\" (Isaiah 6:5). The phrase <strong>when I consider, I am afraid of him</strong> (אֶתְבּוֹנֵן וְאֶפְחַד מִמֶּנּוּ) uses <em>pachad</em> (פָּחַד), profound dread. The verb <em>bin</em> (בִּין, \"consider\") shows this isn't ignorant superstition but theological reflection leading to terror.<br><br>Job's fear is theodicy's dark night: the righteous trembling before God without assurance of His favor. This is Israel's existential crisis before the gospel. Hebrews 12:28-29 answers: we have received grace, therefore let us serve with reverence and godly fear, \"for our God is a consuming fire.\" The same fire that terrified Job purifies believers (1 Peter 1:7).",
            "historical": "The fear of God (<em>yirat Yahweh</em>) is Wisdom Literature's foundation (Proverbs 1:7, 9:10). But Job experiences terror, not reverential awe. Ancient Near Eastern texts portray divine-human encounters as terrifying. Israel's uniqueness was confidence in covenant relationship. Job's terror reflects covenant crisis—he cannot feel God's favor despite his righteousness, foreshadowing Christ's cry of dereliction (Mark 15:34).",
            "questions": [
                "What is the biblical distinction between reverential fear of God and terror?",
                "How does the gospel transform our approach to God's presence from dread to confidence (Hebrews 4:16)?",
                "When you feel distant from God's favor, how does Job's honesty encourage you?"
            ]
        },
        "16": {
            "analysis": "<strong>For God maketh my heart soft</strong> (וְאֵל הֵרַךְ לִבִּי, <em>ve-El herak libbi</em>)—The verb <em>rakak</em> (רָכַךְ) means \"to make soft, weak, faint.\" Paradoxically, this softening isn't tenderness but weakness. The word is used of hearts melting in fear (Deuteronomy 20:3, Joshua 2:11). Job's heart isn't softened by grace but enervated by terror. The phrase <strong>the Almighty troubleth me</strong> (וְשַׁדַּי הִבְהִילָנִי) uses <em>bahal</em> again—God causes dismay. El (אֵל, God) and Shaddai (שַׁדַּי, Almighty) are covenant names, yet they bring no comfort.<br><br>This inverts Ezekiel 36:26's promise: \"I will take away the stony heart... and give you a heart of flesh.\" Job's soft heart brings not responsiveness to grace but paralysis before judgment. This is law without gospel, sovereignty without love. Only Christ resolves this: His hard sayings (John 6:60) drive away superficial followers but melt hard hearts through the Spirit (Acts 2:37, \"pricked in their heart\").",
            "historical": "Ancient Israelite anthropology located emotions and will in the heart (<em>lev</em>). A soft heart could mean teachable (2 Chronicles 34:27) or fearful. Job experiences the latter—covenant names (El, Shaddai) providing no assurance. This reflects the insufficiency of old covenant mediation without the perfect High Priest (Hebrews 7:25).",
            "questions": [
                "How does the gospel enable God's name \"Almighty\" to comfort rather than terrify?",
                "What is the relationship between a soft heart and spiritual vitality?",
                "How does Job's experience prepare us to value Christ's mediation?"
            ]
        },
        "17": {
            "analysis": "<strong>Because I was not cut off before the darkness</strong> (כִּי־לֹא נִצְמַתִּי מִפְּנֵי־חֹשֶׁךְ, <em>ki-lo nitsmatiy mippene-choshek</em>)—The verb <em>tsamat</em> (צָמַת) means \"to be cut off, destroyed, silenced.\" Job wishes he had died before suffering began. The noun <em>choshek</em> (חֹשֶׁךְ, darkness) represents calamity, not physical night. The phrase <strong>neither hath he covered the darkness from my face</strong> (וּמִפָּנַי כִּסָּה־אֹפֶל) intensifies: God hasn't even veiled the horror. The word <em>ophel</em> (אֹפֶל) is thick darkness, gloom. Job experiences what Amos threatened: \"the day of the LORD is darkness, and not light\" (Amos 5:18).<br><br>This is proto-suicidal ideation, wishing for death over continued suffering. Job's righteous spirit prefers non-existence to experiencing God's wrath—the ultimate horror. Jeremiah echoed this: \"cursed be the day wherein I was born\" (Jeremiah 20:14). Only Christ transforms this: He entered <em>ophel</em> on the cross (Matthew 27:45), experiencing God-forsakenness so believers need never pray for death as relief from divine wrath.",
            "historical": "Darkness as divine judgment is a consistent biblical theme: Egypt's plague (Exodus 10:21-23), eschatological judgment (Joel 2:2, Zephaniah 1:15), and Christ's crucifixion (Matthew 27:45). Job experiences darkness as unrelieved present reality. Ancient Near Eastern cultures feared darkness as the realm of chaos and death, but Job's terror is theological—God is present in the darkness as Judge.",
            "questions": [
                "How does Christ's experience of darkness on the cross (Matthew 27:45-46) redeem suffering?",
                "What comfort does Job 23 offer to believers experiencing spiritual darkness?",
                "How should we respond when God doesn't 'cover' our suffering but allows us to experience it fully?"
            ]
        }
    },
    "27": {
        "22": {
            "analysis": "<strong>For God shall cast upon him, and not spare</strong> (וְיַשְׁלֵךְ עָלָיו וְלֹא יַחְמֹל, <em>ve-yashlekh alav velo yachmol</em>)—The verb <em>shalak</em> (שָׁלַךְ) means \"to hurl, throw violently,\" used of God casting down enemies (Exodus 15:1). The phrase \"not spare\" uses <em>chamal</em> (חָמַל), meaning to pity or have compassion. Job describes divine wrath as relentless missiles against the wicked. The phrase <strong>he would fain flee out of his hand</strong> (בָּרוֹחַ יִבְרַח מִיָּדוֹ) uses <em>barach</em> (בָּרַח, \"flee\") doubled for intensity. The wicked desperately tries escaping God's hand (<em>yad</em>, power), but futilely.<br><br>This echoes Amos 5:19: \"As if a man did flee from a lion, and a bear met him.\" There is no escape from divine judgment. Hebrews 10:31 warns, \"It is a fearful thing to fall into the hands of the living God.\" Job's theodicy argues the wicked cannot ultimately prosper—God's justice, though delayed, is certain. This anticipates Romans 2:5, storing up wrath against the day of wrath.",
            "historical": "Job's friends argued suffering proves wickedness (retribution theology). Job counters that the wicked often prosper temporarily (Job 21), but ultimate judgment is certain. This aligns with Psalms 37 and 73—the righteous must wait for God's justice. Ancient wisdom literature across cultures struggled with delayed justice; Job affirms divine judgment while rejecting simplistic retribution theology.",
            "questions": [
                "How does the certainty of divine judgment provide comfort to those suffering injustice?",
                "What is the difference between God's temporal judgments and final judgment?",
                "How should believers balance present grace with future wrath when considering God's character?"
            ]
        },
        "23": {
            "analysis": "<strong>Men shall clap their hands at him</strong> (יִשְׂפְּקוּ־עָלָיו כַפּוֹ, <em>yispeku-alav kappo</em>)—The verb <em>saphaq</em> (שָׂפַק) means \"to clap\" or \"strike together,\" expressing scornful derision. Clapping can signify joy (Psalm 47:1) or mockery (Lamentations 2:15, Nahum 3:19). Here it's contempt. The phrase <strong>shall hiss him out of his place</strong> (וְיִשְׁרֹק עָלָיו מִמְּקֹמוֹ) uses <em>sharaq</em> (שָׁרַק, \"to hiss, whistle\"), expressing astonishment or scorn. The wicked will be expelled from their place (<em>maqom</em>, position, dwelling) with public derision.<br><br>This is the reversal motif: the proud will be humbled, the exalted brought low (Luke 1:52). Public shame awaits those who defied God. This finds ultimate expression in Revelation 18:20—\"Rejoice over her, thou heaven... for God hath avenged you on her.\" The gospel's scandal is that Christ bore this mockery (Matthew 27:39-44, clapping, wagging heads) so believers escape final shame. We exchange places: His shame becomes ours temporarily; His glory becomes ours eternally.",
            "historical": "Public shaming was central to ancient Near Eastern honor/shame culture. Hissing and clapping signified communal rejection and curse. Zephaniah 2:15 describes Nineveh's fate: \"every one that passeth by her shall hiss.\" Job envisions the wicked suffering ultimate social disgrace alongside divine judgment. In honor cultures, this is worse than death—perpetual infamy.",
            "questions": [
                "How does Christ's experience of public mockery (Mark 15:29-32) redefine shame for believers?",
                "What role does public accountability play in God's judgment?",
                "How should we respond to seeing the wicked prosper, knowing their future judgment?"
            ]
        }
    },
    "30": {
        "27": {
            "analysis": "<strong>My bowels boiled, and rested not</strong> (מֵעַי רֻתְּחוּ וְלֹא־דָמּוּ, <em>me'ay rutachu velo-dammu</em>)—The noun <em>me'im</em> (מֵעִים, bowels/intestines) represents the seat of emotions in Hebrew anthropology. The verb <em>ratach</em> (רָתַח) means \"to boil, seethe\" (Ezekiel 24:5), conveying intense inner turmoil. The negative <em>lo dammu</em> (\"did not rest\") uses <em>damah</em> (דָּמָה, to be still, silent). Job experiences relentless internal anguish. The phrase <strong>the days of affliction prevented me</strong> (קִדְּמֻנִי יְמֵי־עֹנִי) uses <em>qadam</em> (קָדַם, \"to come before, meet, confront\"). Suffering arrived before Job could prepare.<br><br>This visceral language captures embodied suffering—not merely mental anguish but physical manifestation of grief. Lamentations 2:11 uses similar imagery: \"my liver is poured upon the earth.\" Job's suffering is total: spiritual, emotional, physical. This anticipates Christ's Gethsemane: \"My soul is exceeding sorrowful\" (Mark 14:34), and His cry of dereliction. The Incarnation means God knows suffering from within, not merely as external observer.",
            "historical": "Ancient Israelite psychology was holistic, not dualistic. Emotions resided in physical organs: heart (thought/will), kidneys (conscience), bowels (compassion/anguish). \"Boiling bowels\" wasn't metaphor but literal physiological experience of grief. Modern psychology recognizes psychosomatic suffering. Job's description predates but validates embodied cognition—emotions and body are inseparable.",
            "questions": [
                "How does recognizing the physical reality of emotional suffering affect pastoral care?",
                "What does Job's holistic suffering teach about the nature of human personhood?",
                "How does Christ's bodily suffering (Isaiah 53:3-5) sanctify our physical pain?"
            ]
        },
        "28": {
            "analysis": "<strong>I went mourning without the sun</strong> (קֹדֵר הִלַּכְתִּי בְּלֹא חַמָּה, <em>qoder hilakhti belo chammah</em>)—The adjective <em>qoder</em> (קֹדֵר) means \"dark, blackened, mourning\" (used of sackcloth in Psalm 35:14). The phrase \"without the sun\" means not from solar deprivation but inner darkness—mourning unrelated to external circumstances. The verb <em>halakh</em> (הָלַךְ, \"to walk\") indicates continuous lifestyle. Job's mourning is his constant state. The phrase <strong>I stood up, and I cried in the congregation</strong> (קַמְתִּי בַקָּהָל אֲשַׁוֵּעַ) uses <em>shava'</em> (שָׁוַע, \"to cry for help\"). Job publicly laments, not suffering in silence.<br><br>This public lament distinguishes biblical piety from stoicism. Lament is worship (Psalms 13, 22, 88). Job refuses to pretend—he brings raw suffering into community. This foreshadows Christ's public agony (John 11:35, Hebrews 5:7, \"loud crying and tears\"). The gospel validates emotional honesty: we need not hide suffering to maintain spirituality. Lament is faith's cry when praise seems impossible.",
            "historical": "Ancient Israelite worship included public lament. The temple had professional mourners (Jeremiah 9:17). Communal fasting and prayer addressed corporate and individual crisis (Joel 1-2). Job's public crying wasn't cultural violation but appropriate religious expression. Contrast Greek philosophy's emphasis on emotional control (Stoicism). Biblical faith permits—even requires—honest expression of suffering before God and community.",
            "questions": [
                "How can modern churches recover the practice of communal lament?",
                "What is the difference between complaining and biblical lament?",
                "How does Job's example give permission for emotional honesty in worship?"
            ]
        },
        "29": {
            "analysis": "<strong>I am a brother to dragons</strong> (אָח הָיִיתִי לְתַנִּים, <em>ach hayiti le-tannim</em>)—The noun <em>tannim</em> (תַּנִּים) likely refers to jackals (so ESV, NIV), desert scavengers, though some interpret as sea dragons/serpents. The word <em>ach</em> (אָח, brother) indicates kinship or companionship. Job identifies with wild, mournful creatures of desolate places. The phrase <strong>companion to owls</strong> (וְרֵעַ לִבְנוֹת יַעֲנָה) uses <em>rea'</em> (רֵעַ, friend, companion). Owls (<em>ya'anah</em>, likely referring to ostriches or owls) inhabit ruins, their cry symbolizing desolation (Isaiah 13:21, Micah 1:8).<br><br>This is social alienation imagery. Job, once community leader (Job 29), now identifies with outcasts of wilderness. Isaiah 34:13-14 describes Edom's judgment as becoming habitation of dragons and owls—a place of divine curse. Job experiences curse-level desolation. This anticipates Christ \"numbered with the transgressors\" (Isaiah 53:12), forsaken, despised, rejected (Isaiah 53:3). The gospel's paradox: the Holy One became companion to sinners so they could become children of God (John 1:12).",
            "historical": "Ancient Near Eastern texts use animal imagery to express extreme states. Job's self-description as kin to jackals and owls indicates total social marginalization. In honor/shame cultures, this is existential death—loss of community standing. Lepers experienced similar ostracism (Leviticus 13:45-46), living \"outside the camp.\" Job, though righteous, experiences the outcast status reserved for the unclean.",
            "questions": [
                "How does Christ's identification with outcasts (Matthew 11:19, friend of sinners) transform social marginalization?",
                "What comfort does Job 30:29 offer to believers experiencing social isolation?",
                "How should the church respond to those who feel like spiritual outcasts?"
            ]
        },
        "30": {
            "analysis": "<strong>My skin is black upon me</strong> (עוֹרִי שָׁחַר מֵעָלָי, <em>ori shachar me'alay</em>)—The verb <em>shachar</em> (שָׁחַר) means \"to be or become black,\" likely from disease, sunburn, or mourning (Lamentations 4:8, 5:10). Job's physical appearance reflects internal suffering. The phrase <strong>my bones are burned with heat</strong> (וְעַצְמִי־חָרָה מִנִּי־חֹרֶב) uses <em>charah</em> (חָרָה, \"to burn\") and <em>chorev</em> (חֹרֶב, \"heat, drought\"). Bones represent core being (Psalm 22:14, 102:3). Job's suffering penetrates to his essence, not merely skin-deep.<br><br>This describes wasting disease, possibly the \"sore boils\" of Job 2:7. The blackened skin and burning bones indicate systemic suffering. Psalm 102:3-5 uses similar imagery: \"My bones are burned... my skin cleaveth to my bones.\" Job's physical deterioration mirrors spiritual anguish. This foreshadows Isaiah 52:14: Messiah's appearance \"marred more than any man.\" Christ's physical suffering (scourging, crucifixion) embodied spiritual agony—bearing sin's curse (Galatians 3:13).",
            "historical": "Ancient medicine recognized connection between emotional/spiritual states and physical health. Job's symptoms suggest severe dermatological and systemic illness, possibly leprous condition or severe eczema with fever. The blackening of skin could indicate necrosis, severe sunburn from exposure, or hyperpigmentation from chronic illness. Ancient Near Eastern texts describe similar afflictions as divine punishment, but Job maintains his innocence.",
            "questions": [
                "How does Job's physical suffering challenge the health-and-wealth gospel?",
                "What does Scripture teach about the relationship between physical and spiritual suffering?",
                "How does Christ's bodily suffering sanctify our experience of illness?"
            ]
        },
        "31": {
            "analysis": "<strong>My harp also is turned to mourning</strong> (וַתְּהִי לְאֵבֶל כִּנֹּרִי, <em>vatehi le-evel kinnori</em>)—The noun <em>kinnor</em> (כִּנּוֹר) is a stringed instrument, symbol of joy and celebration (Genesis 4:21, Psalm 33:2). The noun <em>evel</em> (אֵבֶל) means mourning, grief. Job's music, once joyful, now laments. The phrase <strong>my organ into the voice of them that weep</strong> (וְעֻגָבִי לְקוֹל בֹּכִים) uses <em>ugav</em> (עֻגָב), another musical instrument (likely a flute or pipe). The \"voice of them that weep\" (<em>qol bokhim</em>) indicates Job's music accompanies tears, not celebration.<br><br>This is the inversion of worship. Psalm 137:2-4 parallels this: \"We hanged our harps... How shall we sing the LORD's song in a strange land?\" Exile silences praise. Job experiences spiritual exile while physically present. This anticipates Good Friday's silence before Easter's song. Lamentations becomes praise only through resurrection. The gospel transforms mourning: \"weeping may endure for a night, but joy cometh in the morning\" (Psalm 30:5). Christ's resurrection ensures our harps will sing again.",
            "historical": "Music was integral to ancient Israelite worship and culture. Harp and organ (pipes/flute) accompanied feasts, worship, and celebration. Their silence or transformation to lament instruments indicated profound crisis. David's harp soothed Saul (1 Samuel 16:23), but Job's harp intensifies grief. Temple musicians led both praise (2 Chronicles 5:12-13) and lament. Job's reversed music signals liturgical crisis—worship turned to mourning.",
            "questions": [
                "How can lament be a form of worship rather than abandonment of faith?",
                "What does the transformation of Job's instruments teach about suffering's comprehensive impact?",
                "How does the Psalter's blend of praise and lament guide our worship during suffering?"
            ]
        }
    },
    "32": {
        "20": {
            "analysis": "<strong>I will speak, that I may be refreshed</strong> (אֲדַבְּרָה וְיִרְוַח לִי, <em>adabberah ve-yirvach li</em>)—The verb <em>ravach</em> (רָוַח) means \"to be wide, spacious, relieved.\" Elihu feels internal pressure requiring release through speech. The phrase <strong>I will open my lips and answer</strong> (אֶפְתַּח־שְׂפָתַי וְאֶעֱנֶה) uses <em>patach</em> (פָּתַח, \"to open\") and <em>anah</em> (עָנָה, \"to answer, respond\"). Elihu breaks his silence, unable to contain himself longer. This reveals both earnestness and possible pride—he must speak or burst (v. 19).<br><br>Elihu's youthful passion contrasts with the three friends' exhausted silence (32:1). Proverbs warns against hasty speech (Proverbs 29:20, \"Seest thou a man that is hasty in his words? there is more hope of a fool than of him\"), yet also values speaking truth (Proverbs 24:26). Elihu's speeches (chapters 32-37) offer theological insights superior to the three friends but still fall short of God's answer (chapters 38-41). This teaches that even earnest theological speech cannot substitute for divine revelation. We need God's Word, not merely human wisdom, however sincere.",
            "historical": "Ancient Near Eastern wisdom dialogues typically featured multiple speakers offering perspectives. Elihu's late entrance (absent in chapters 1-31) has puzzled interpreters—some suggest later addition, others see deliberate literary structure. His emphasis on youth deferring to age reflects cultural honor codes (Leviticus 19:32), but also shows how suffering and truth can transcend cultural hierarchies. Elihu waited respectfully (32:4) but ultimately speaks with passionate conviction.",
            "questions": [
                "How do we balance the need to speak truth with the discipline of listening?",
                "What does Elihu's passionate speech teach about youthful zeal and mature wisdom?",
                "When is silence appropriate, and when must we speak despite social pressure?"
            ]
        },
        "21": {
            "analysis": "<strong>Let me not, I pray you, accept any man's person</strong> (אַל־נָא אֶשָּׂא פְנֵי־אִישׁ, <em>al-na esa pene-ish</em>)—The idiom \"lift up face\" (<em>nasa panim</em>) means to show partiality or favoritism (Leviticus 19:15, Deuteronomy 1:17). Elihu declares impartiality—he won't flatter Job because of status. The phrase <strong>neither let me give flattering titles unto man</strong> (וְאֶל־אָדָם לֹא אֲכַנֶּה) uses <em>kanah</em> (כָּנָה), meaning \"to surname, give honorific titles.\" Elihu refuses obsequious speech. This echoes James 2:1-9's condemnation of partiality: \"My brethren, have not the faith of our Lord Jesus Christ... with respect of persons.\"<br><br>Elihu's claim to impartiality is admirable but potentially arrogant—declaring one's own objectivity often betrays subjectivity. True impartiality requires divine perspective (1 Samuel 16:7, \"man looketh on the outward appearance, but the LORD looketh on the heart\"). The gospel reveals ultimate impartiality: God shows no favoritism (Romans 2:11, Galatians 2:6), judging each according to works, but offering grace equally to all who believe. Christ's cross levels all distinctions—no room for partiality or flattery.",
            "historical": "Ancient Near Eastern cultures highly valued honor, deference to superiors, and elaborate titles. Court officials used extensive honorifics. Prophets challenged this by speaking God's word regardless of human power (Jeremiah 1:7-8, Ezekiel 2:6). Elihu's refusal of flattery aligns with prophetic tradition—speaking truth over maintaining social harmony. His youth makes this bolder, as cultural norms expected deference to elders.",
            "questions": [
                "How can we speak truth while maintaining appropriate respect for authority?",
                "What is the difference between godly respect and sinful flattery?",
                "How does the gospel's leveling effect (Galatians 3:28) challenge cultural hierarchies?"
            ]
        },
        "22": {
            "analysis": "<strong>For I know not to give flattering titles</strong> (כִּי לֹא יָדַעְתִּי אֲכַנֶּה, <em>ki lo yadati akanneh</em>)—The verb <em>yada</em> (יָדַע, \"to know\") indicates ability or practice. Elihu claims he doesn't know how to flatter—it's foreign to his character. The phrase <strong>in so doing my maker would soon take me away</strong> (כִּמְעַט יִשָּׂאֵנִי עֹשֵׂנִי) uses <em>oseni</em> (עֹשֵׂנִי, \"my Maker\") and <em>nasa</em> (נָשָׂא, \"to lift up, take away,\" here meaning remove or destroy). Elihu fears divine judgment for flattery—recognizing God judges false speech (Proverbs 6:16-19, \"a lying tongue\" among things God hates).<br><br>Elihu's invocation of the Maker echoes Job 4:17, 35:10, 36:3. Accountability to the Creator forbids manipulative speech. This aligns with the ninth commandment against false witness (Exodus 20:16) and Jesus's warning: \"every idle word that men shall speak, they shall give account\" (Matthew 12:36). The gospel transforms speech: from flattery or condemnation to edification (Ephesians 4:29). Speaking truth in love (Ephesians 4:15) navigates between flattery and harshness.",
            "historical": "Divine judgment for false speech is a consistent biblical theme. Prophets who flattered kings faced judgment (1 Kings 22:23, Jeremiah 5:31). The wisdom tradition values truthful speech (Proverbs 12:22, 16:13). Elihu's fear of his Maker reflects covenant theology—God's omniscience means no secret flattery escapes notice. This accountability shaped ancient Israelite ethics, distinguishing them from cultures where flattery was political necessity.",
            "questions": [
                "How does accountability to our Maker constrain our speech?",
                "What forms does flattery take in modern Christian contexts?",
                "How can we cultivate speech that is both truthful and gracious (Colossians 4:6)?"
            ]
        }
    },
    "33": {
        "28": {
            "analysis": "<strong>He will deliver his soul from going into the pit</strong> (פָּדָה נַפְשׁוֹ מֵעֲבֹר בַּשָּׁחַת, <em>padah naphsho me'avor bashachat</em>)—The verb <em>padah</em> (פָּדָה) means \"to ransom, redeem\" through payment of a price. This is Exodus redemption language (Exodus 13:13, 15:13). The noun <em>nephesh</em> (נֶפֶשׁ, soul/life) represents the whole person. The <em>shachat</em> (שַׁחַת, pit) symbolizes death, Sheol, destruction (Psalm 30:3, 103:4). Elihu describes divine rescue from death. The phrase <strong>his life shall see the light</strong> (וְחַיָּתוֹ בָּאוֹר תִּרְאֶה) uses <em>chayyah</em> (חַיָּה, life) and <em>or</em> (אוֹר, light), symbol of life, favor, salvation (Psalm 36:9, 56:13).<br><br>This is proto-gospel language: redemption by ransom from death to life and light. Job 19:25's confession, \"I know that my redeemer liveth,\" uses the same <em>ga'al</em> redemption terminology. Elihu's theology anticipates Christ, the ultimate Redeemer who paid the ransom (Mark 10:45, 1 Timothy 2:6) to deliver souls from the pit. Christ descended into death (1 Peter 3:19, Apostles' Creed) and rose, bringing believers from darkness to light (Colossians 1:13, 1 Peter 2:9).",
            "historical": "Israelite theology struggled with death and afterlife understanding. The pit (<em>shachat</em>) or Sheol represented the grave, shadowy existence. Early OT texts offer limited hope beyond death (Ecclesiastes 9:10), but later texts develop resurrection hope (Daniel 12:2, Isaiah 26:19). Elihu's language of redemption from the pit suggests emerging confidence in God's power over death, fully revealed in Christ's resurrection (2 Timothy 1:10, \"abolished death\").",
            "questions": [
                "How does Christ's redemption fulfill Elihu's vision of deliverance from the pit?",
                "What does seeing \"the light\" mean in terms of salvation and eternal life?",
                "How should the certainty of redemption shape our view of physical death?"
            ]
        },
        "29": {
            "analysis": "<strong>Lo, all these things worketh God oftentimes with man</strong> (הֶן־כָּל־אֵלֶּה יִפְעַל־אֵל פַּעֲמַיִם שָׁלוֹשׁ עִם־גָּבֶר, <em>hen-kol-eleh yiphal-El pa'amayim shalosh im-gaver</em>)—The phrase \"twice, three times\" (<em>pa'amayim shalosh</em>) is Hebrew idiom for \"repeatedly\" (not literally 2-3 times). The verb <em>pa'al</em> (פָּעַל, \"to work, do\") emphasizes God's active engagement. Elihu argues God repeatedly intervenes in human lives, not abandoning them to death. This counters Job's sense of divine abandonment (Job 7:19, 10:20). The noun <em>gaver</em> (גֶּבֶר, man/mighty man) emphasizes humanity's smallness compared to God's greatness.<br><br>Elihu's theology affirms divine persistence: God doesn't give one warning then abandon. This anticipates Jesus's parable of the persistent father waiting for the prodigal (Luke 15:20) and God's patience in Romans 2:4: \"the goodness of God leadeth thee to repentance.\" Reformed theology speaks of \"irresistible grace\"—God's effectual calling doesn't fail (John 6:37, 44). Elihu sees suffering not as abandonment but repeated divine intervention to bring people back from destruction.",
            "historical": "Ancient Near Eastern religions often portrayed gods as capricious, giving single warnings before destructive judgment. Elihu's emphasis on God's repeated interventions distinguishes Yahweh as patient and redemptive. This aligns with covenant theology—God's commitment to relationship despite human failure. Hosea, Jeremiah, and Ezekiel all emphasize God's persistent pursuit of unfaithful Israel (Hosea 11:8, Jeremiah 31:3).",
            "questions": [
                "How does God's repeated intervention in your life demonstrate His patience?",
                "What is the relationship between divine discipline and divine love?",
                "How should God's persistence affect our response to His correction?"
            ]
        },
        "30": {
            "analysis": "<strong>To bring back his soul from the pit</strong> (לְהָשִׁיב נַפְשׁוֹ מִנִּי־שָׁחַת, <em>lehashiv naphsho minni-shachat</em>)—The verb <em>shuv</em> (שׁוּב, in Hiphil \"to bring back, restore\") is key conversion/repentance language throughout Scripture. The causative stem indicates God actively restores. This echoes Psalm 23:3: \"He restoreth my soul.\" The phrase <strong>to be enlightened with the light of the living</strong> (לֵאוֹר בְּאוֹר הַחַיִּים, <em>le'or be'or hachayyim</em>) uses double light imagery. The \"light of the living\" contrasts with death's darkness (Psalm 56:13, Job 33:28). To be enlightened is to experience restoration to full life and divine favor.<br><br>This restoration language anticipates NT conversion theology: being \"delivered from the power of darkness, and translated into the kingdom of his dear Son\" (Colossians 1:13). John 8:12 declares Christ \"the light of the world\"—those following Him \"shall not walk in darkness, but shall have the light of life.\" Elihu's vision of God restoring souls from the pit finds ultimate fulfillment in regeneration (Titus 3:5) and final resurrection (1 Corinthians 15:42-44).",
            "historical": "Light/darkness dualism was prominent in ancient Near Eastern thought, but biblical usage is unique. Light isn't merely natural vs. supernatural but represents God's presence, life, truth (Psalm 27:1, 119:105). The Qumran community (Dead Sea Scrolls) developed elaborate light/darkness theology. NT writers, especially John (John 1:4-9, 1 John 1:5-7), build on OT foundations, presenting Christ as ultimate Light conquering darkness.",
            "questions": [
                "How does conversion involve being brought from the pit to the light?",
                "What does it mean practically to live \"enlightened with the light of the living\"?",
                "How does God's work of restoration demonstrate sovereign grace?"
            ]
        },
        "31": {
            "analysis": "<strong>Mark well, O Job, hearken unto me</strong> (הַקְשֵׁב אִיּוֹב שְׁמַע־לִי, <em>haqshev Iyyov shema-li</em>)—The verb <em>qashav</em> (קָשַׁב, \"to attend, pay attention\") and <em>shama</em> (שָׁמַע, \"to hear, obey\") together emphasize urgent listening. This doubles the imperative, demanding Job's full attention. The phrase <strong>hold thy peace, and I will speak</strong> (הַחֲרֵשׁ וְאָנֹכִי אֲדַבֵּר) uses <em>charash</em> (חָרַשׁ, \"to be silent\"). Elihu demands Job's silence to receive instruction. This reflects ancient teacher-student dynamics—disciples silent before masters.<br><br>The biblical pattern is consistent: \"Be still, and know that I am God\" (Psalm 46:10). Jesus rebuked the storm: \"Peace, be still\" (Mark 4:39). Spiritual receptivity requires silencing our defenses and arguments. Job's previous speeches (chapters 3-31) have been extensive self-justification. Elihu demands he cease and listen. This anticipates God's answer (chapters 38-41), which also silences Job (40:4, 42:6). True wisdom begins with humble listening, not assertive speaking (James 1:19, \"swift to hear, slow to speak\").",
            "historical": "Ancient Near Eastern wisdom tradition emphasized the disciple posture: silence before the teacher. Proverbs repeatedly contrasts the wise (who listen) with fools (who speak hastily): Proverbs 17:28, \"Even a fool, when he holdeth his peace, is counted wise.\" Egyptian wisdom literature (Instruction of Amenemope) similarly emphasized listening. Elihu's demand reflects this pedagogy—learning requires receptivity, not merely asserting one's position.",
            "questions": [
                "How does cultivating silence before God enable spiritual growth?",
                "What prevents us from truly listening to God's word?",
                "How does Job's eventual silence (42:6) demonstrate mature faith?"
            ]
        },
        "32": {
            "analysis": "<strong>If thou hast any thing to say, answer me</strong> (אִם־יֶשׁ־מִלִּין הֲשִׁיבֵנִי, <em>im-yesh-millin hashiveni</em>)—The noun <em>millah</em> (מִלָּה, word, speech) and verb <em>shuv</em> (שׁוּב, Hiphil \"to answer, respond\") invite Job to reply if he has legitimate response. The phrase <strong>speak, for I desire to justify thee</strong> (דַּבֵּר כִּי־חָפַצְתִּי צַדְּקֶךָּ, <em>dabber ki-chaphatzti tzaddeqekha</em>) uses <em>chaphetz</em> (חָפֵץ, \"to delight in, desire\") and <em>tsadaq</em> (צָדַק, Piel \"to justify, declare righteous\"). Elihu claims benevolent intent—he wants to vindicate Job if possible, not condemn him. This sets Elihu apart from the three friends who presumed Job's guilt.<br><br>Elihu's desire to justify anticipates God's own vindication of Job (42:7-8). Yet only God can truly justify (Romans 3:26, 8:33). Elihu's offer, though sincere, is inadequate—human wisdom cannot justify before God. This points to gospel truth: justification comes not by human arguments or defense but by faith in Christ (Romans 5:1, Galatians 2:16). God justifies the ungodly (Romans 4:5), not based on our defense but on Christ's righteousness imputed to believers.",
            "historical": "Ancient legal settings featured advocates attempting to justify defendants. The Hebrew <em>tsadaq</em> is forensic language—declaring righteous in legal context. Elihu adopts advocate role, unlike Job's friends who functioned as prosecutors. This reflects ancient Near Eastern justice systems where skilled advocates could mean difference between condemnation and acquittal. Yet ultimate vindication required divine intervention—earthly courts were fallible.",
            "questions": [
                "How does Elihu's inability to justify Job point to our need for Christ's advocacy?",
                "What is the relationship between human vindication and divine justification?",
                "How does Christ's role as Advocate (1 John 2:1) fulfill what Elihu attempted?"
            ]
        },
        "33": {
            "analysis": "<strong>If not, hearken unto me</strong> (אִם־אַיִן אַתָּה שְׁמַע־לִי, <em>im-ayin attah shema-li</em>)—The conditional \"if not\" presents Job with binary choice: speak if you can defend yourself, otherwise listen. The imperative <em>shema</em> (שְׁמַע, \"hear, listen\") demands attention. The phrase <strong>hold thy peace, and I shall teach thee wisdom</strong> (הַחֲרֵשׁ וַאֲאַלֶּפְךָ חָכְמָה, <em>hacharesh va'aalephkha chokmah</em>) uses <em>alaph</em> (אָלַף, \"to teach, instruct\") and <em>chokmah</em> (חָכְמָה, wisdom). Elihu claims to offer what Job lacks—true wisdom. Yet ironically, Elihu himself needs instruction, which God provides in chapters 38-41.<br><br>True wisdom comes from divine revelation, not human insight. Proverbs 9:10 declares, \"The fear of the LORD is the beginning of wisdom.\" Elihu's speeches contain insights (especially about suffering's disciplinary purpose, chapter 33), but incomplete understanding. Paul echoes this: \"we know in part\" (1 Corinthians 13:9). The gospel reveals ultimate wisdom: \"Christ the power of God, and the wisdom of God\" (1 Corinthians 1:24). Human wisdom, even sincere theology, must bow before divine self-disclosure.",
            "historical": "Wisdom literature (Job, Proverbs, Ecclesiastes) navigated tension between human wisdom and divine revelation. Elihu represents earnest human theology—superior to the friends' retribution theology but still inadequate. This prepares for God's speeches, which transcend human categories. Ancient Near Eastern wisdom traditions (Egyptian, Mesopotamian) relied on human observation; biblical wisdom ultimately grounds in divine self-revelation (Proverbs 1:7, Job 28:28).",
            "questions": [
                "How do we distinguish human wisdom from divine revelation?",
                "What role does theological study play if ultimately only God provides true wisdom?",
                "How does Christ as \"the wisdom of God\" (1 Corinthians 1:24) transform our pursuit of understanding?"
            ]
        }
    },
    "34": {
        "30": {
            "analysis": "<strong>That the hypocrite reign not, lest the people be ensnared</strong> (מִמְּלֹךְ אָדָם חָנֵף מִמֹּקְשֵׁי עָם, <em>mimmelokh adam chaneph mimmoqshei am</em>)—The noun <em>chaneph</em> (חָנֵף, hypocrite, godless person) describes one who professes piety while living wickedly. The verb <em>malakh</em> (מָלַךְ, \"to reign, rule\") indicates political power. The noun <em>moqesh</em> (מוֹקֵשׁ, snare, trap) depicts people being caught in evil when hypocrites rule. Elihu argues God prevents wicked rulers from reigning to protect people. This aligns with Proverbs 29:2: \"When the righteous are in authority, the people rejoice: but when the wicked beareth rule, the people mourn.\"<br><br>Yet history shows hypocrites often do reign—Ahab, Manasseh, and others. Elihu's theology is incomplete. Romans 13:1 teaches God permits all governing authorities, yet not all are righteous. This tension resolves eschatologically: Christ will establish ultimate righteous reign (Isaiah 32:1, Revelation 19:11-16). Meanwhile, God's sovereignty works through even wicked rulers to accomplish His purposes (Habakkuk 1:6, Acts 4:27-28). The gospel transcends political solutions: the Kingdom of God, not human government, is our ultimate hope.",
            "historical": "Ancient Israel's monarchy included righteous kings (David, Josiah) and wicked ones (Ahab, Manasseh). Deuteronomic theology connected national prosperity to king's righteousness (Deuteronomy 17:14-20). Wisdom literature recognized the danger of wicked rulers (Proverbs 28:15-16, Ecclesiastes 10:5-7). Elihu's statement reflects ideal covenant theology but doesn't account for mystery of God permitting wicked rulers, later addressed by prophets (Habakkuk) and apostles (Romans 13).",
            "questions": [
                "How does God's sovereignty operate when wicked leaders rule?",
                "What is the Christian's responsibility toward unjust government?",
                "How does Christ's kingdom relativize all human political arrangements?"
            ]
        },
        "31": {
            "analysis": "<strong>Surely it is meet to be said unto God, I have borne chastisement</strong> (כִּי־אֶל־אֵל הֶאָמַר נָשָׂאתִי לֹא אֶחְבֹּל, <em>ki-el-El he'amar nasati lo echbol</em>)—The verb <em>nasa</em> (נָשָׂא, \"to bear, carry\") refers to accepting punishment. The verb <em>chaval</em> (חָבַל, \"to act corruptly, offend\") means to do wrong. Elihu models proper response to divine discipline: acknowledge it and commit to reform. The phrase <strong>I will not offend any more</strong> expresses repentance—ceasing sin. This aligns with Proverbs 3:11-12: \"despise not the chastening of the LORD... for whom the LORD loveth he correcteth.\"<br><br>Elihu presents the theologically correct response to suffering-as-discipline: accept it, learn from it, turn from sin. Hebrews 12:5-11 develops this fully—God's discipline proves sonship and produces righteousness. Yet Job's case complicates this: his suffering isn't punitive (1:8, 42:7). Not all suffering is disciplinary for personal sin. This anticipates Christ's teaching (John 9:3, the blind man) and Paul's theology (2 Corinthians 12:7-10, the thorn). Suffering serves multiple divine purposes beyond just correcting sin.",
            "historical": "Ancient Near Eastern texts (Babylonian Theodicy, Ludlul Bel Nemeqi) explored suffering's meaning. Common assumption: suffering indicates divine displeasure requiring appeasement. Elihu's counsel reflects standard wisdom—accept correction, reform behavior. Yet Job challenges this framework, anticipating NT revelation that suffering serves purposes beyond personal discipline: conformity to Christ (Romans 8:28-29), witness (2 Corinthians 1:3-7), sanctification (James 1:2-4).",
            "questions": [
                "How do we discern when suffering is divine discipline versus other purposes?",
                "What is the proper response to God's chastisement?",
                "How does Hebrews 12:5-11 help us understand suffering's role in spiritual formation?"
            ]
        },
        "32": {
            "analysis": "<strong>That which I see not teach thou me</strong> (בִּלְעֲדֵי אֶחֱזֶה אַתָּה הֹרֵנִי, <em>bil'adei echezeh attah horeni</em>)—The phrase \"that which I see not\" uses <em>chazah</em> (חָזָה, \"to see, perceive\") with negative. This is prayer for illumination—teach me what I cannot perceive. The verb <em>yarah</em> (יָרָה, Hiphil \"to teach, instruct\") is used of God teaching Torah (Deuteronomy 33:10). The phrase <strong>if I have done iniquity, I will do no more</strong> (אִם־עָוֶל פָּעַלְתִּי לֹא אֹסִיף) uses <em>avel</em> (עָוֶל, iniquity, injustice) and <em>yasaph</em> (יָסַף, \"to add, continue\"). Elihu models repentance: asking God to reveal unknown sin, committing to cease.<br><br>This prayer echoes Psalm 19:12: \"Who can understand his errors? cleanse thou me from secret faults,\" and Psalm 139:23-24: \"Search me, O God... see if there be any wicked way in me.\" The reformed conscience knows sin's deceitfulness (Hebrews 3:13, Jeremiah 17:9)—we cannot fully perceive our own evil. We need divine illumination (Ephesians 1:18, Hebrews 4:12-13). The gospel provides both: the Spirit convicts of sin (John 16:8) and Christ cleanses from all unrighteousness (1 John 1:9).",
            "historical": "Ancient Israelite piety emphasized self-examination and covenant loyalty. Sacrificial system included provisions for unintentional sins (Leviticus 4-5). Yet Job's case reveals limits of this framework—his suffering isn't corrective for sin. The psalm tradition developed this prayer for divine illumination (Psalms 19, 51, 139). NT builds on this: Spirit-enabled self-examination (1 Corinthians 11:28-31) and confidence that God's illumination leads to cleansing, not condemnation (1 John 1:7-9).",
            "questions": [
                "How can we practice spiritual self-examination without falling into introspection or scrupulosity?",
                "What role does the Holy Spirit play in revealing sin?",
                "How does confidence in God's forgiveness enable honest self-examination?"
            ]
        },
        "33": {
            "analysis": "<strong>Should it be according to thy mind?</strong> (הֲמֵעִמְּךָ יְשַׁלְּמֶנָּה, <em>hame'immekha yeshallemennah</em>)—Elihu challenges Job: should God govern according to Job's standards? The phrase <strong>he will recompense it, whether thou refuse, or whether thou choose</strong> (כִּי־אַתָּה מָאַסְתָּ כִּי־אַתָּה תִבְחַר, <em>ki-attah ma'asta ki-attah tivchar</em>) uses <em>ma'as</em> (מָאַס, \"to reject\") and <em>bachar</em> (בָּחַר, \"to choose\"). God's justice operates independently of human approval or rejection. The phrase <strong>and not I: therefore speak what thou knowest</strong> (וְלֹא־אָנִי וּמַה־יָדַעְתָּ דַּבֵּר) shifts burden to Job—if you know better, speak.<br><br>This is theodicy's central question: does God answer to human moral intuitions, or do we submit to His revealed character? Isaiah 55:8-9 answers: \"My thoughts are not your thoughts, neither are your ways my ways.\" Romans 9:20 challenges: \"Shall the thing formed say to him that formed it, Why hast thou made me thus?\" Yet Scripture also validates lament and questioning (Habakkuk, Psalms). The gospel resolves this: the cross reveals God's justice and mercy united (Romans 3:25-26)—satisfying both divine righteousness and human need.",
            "historical": "Ancient Near Eastern texts (e.g., Babylonian Theodicy) featured dialogues questioning divine justice. Biblical faith uniquely permits questioning God while ultimately requiring submission. Prophets challenged God (Jeremiah 12:1, Habakkuk 1:2-4) but bowed to divine sovereignty (Jeremiah 12:5-6, Habakkuk 2:4). Job's friends demanded immediate submission; Elihu permits questions but ultimately points to God's incomprehensibility. This prepares for divine answer that neither explains nor condemns Job's questioning but reveals God's transcendent majesty.",
            "questions": [
                "How do we balance honest questioning with submission to divine sovereignty?",
                "What does the cross reveal about God's character that answers theodicy's questions?",
                "How should we respond when God's ways contradict our moral intuitions?"
            ]
        },
        "34": {
            "analysis": "<strong>Let men of understanding tell me</strong> (אַנְשֵׁי לֵבָב יֹאמְרוּ לִי, <em>anshei levav yomru li</em>)—The phrase \"men of heart\" (<em>anshei levav</em>) refers to wise, discerning people. The heart (<em>lev</em>) is the seat of understanding in Hebrew anthropology. The phrase <strong>and let a wise man hearken unto me</strong> (וְגֶבֶר חָכָם שֹׁמֵעַ לִי, <em>ve-gever chakam shomea li</em>) doubles the appeal to wisdom. Elihu appeals to the wise to validate his argument. This is rhetorical strategy—claiming support from the discerning. Yet Proverbs warns against self-proclaimed wisdom: \"Seest thou a man wise in his own conceit? there is more hope of a fool than of him\" (Proverbs 26:12).<br><br>True wisdom requires humility, not self-certification. James 3:13-17 distinguishes earthly wisdom (bitter envying, strife) from divine wisdom (pure, peaceable, gentle). Elihu's speeches contain truth but also presumption—he lacks the humility God will model in His answer. The gospel reveals ultimate wisdom in what appears foolish: Christ crucified (1 Corinthians 1:23-25). This transforms epistemology—wisdom comes not from human validation but from divine revelation and humble reception.",
            "historical": "Ancient wisdom tradition valued peer recognition and communal validation of wise teaching. Proverbs frequently appeals to \"the wise\" as arbiters of truth. Yet prophetic tradition challenged consensus wisdom when it contradicted divine revelation (Jeremiah vs. false prophets, Amos vs. establishment priests). Elihu's appeal to the wise follows conventional wisdom pedagogy but will be superseded by direct divine speech, which validates neither Job's friends nor Elihu but rebukes all human presumption (42:7-8).",
            "questions": [
                "How do we evaluate theological claims without falling into either individualism or uncritical consensus?",
                "What role does the community of faith play in discerning truth?",
                "How does humility before God's Word relativize all human wisdom?"
            ]
        },
        "35": {
            "analysis": "<strong>Job hath spoken without knowledge</strong> (אִיּוֹב לֹא־בְדַעַת יְדַבֵּר, <em>Iyyov lo-veda'at yedabber</em>)—The noun <em>da'at</em> (דַּעַת, knowledge) indicates understanding, not mere information. Elihu accuses Job of speaking ignorantly. The phrase <strong>his words were without wisdom</strong> (וּדְבָרָיו לֹא בְהַשְׂכֵּיל, <em>udevarav lo vehaskel</em>) uses <em>sekel</em> (שֶׂכֶל, understanding, insight). This echoes Eliphaz's earlier accusation (Job 15:2-3). Yet God will vindicate Job's speech over the friends (42:7): \"ye have not spoken of me the thing that is right, as my servant Job hath.\" Elihu's judgment is premature and partially wrong.<br><br>This teaches discernment: sincere theological argumentation can reach wrong conclusions. Elihu isn't malicious, yet he misunderstands. Proverbs 18:13 warns: \"He that answereth a matter before he heareth it, it is folly and shame unto him.\" The gospel reveals knowledge's limits: \"we know in part\" (1 Corinthians 13:9). Ultimate knowledge comes through revelation of Christ (Colossians 2:3, \"in whom are hid all the treasures of wisdom and knowledge\"). We must speak with epistemic humility, acknowledging the limits of human understanding.",
            "historical": "Ancient Near Eastern wisdom culture valued eloquent, persuasive speech. Yet Israelite tradition subordinated rhetorical skill to truth and divine revelation. Prophets often spoke simple, even offensive messages (Amos 7:14-15, \"I was no prophet... but the LORD said unto me, Go, prophesy\"). Jesus's teaching astonished because He spoke \"with authority\" (Mark 1:22), not rhetorical polish. God's vindication of Job over more eloquent friends teaches content matters more than form.",
            "questions": [
                "How can we speak theologically with confidence while maintaining appropriate humility?",
                "What does God's vindication of Job teach about the relationship between suffering and speaking rightly about God?",
                "How does Christ as God's ultimate Word (John 1:1) redefine knowledge and wisdom?"
            ]
        },
        "36": {
            "analysis": "<strong>My desire is that Job may be tried unto the end</strong> (אָבִי יִבָּחֵן אִיּוֹב עַד־נֶצַח, <em>avi yivachen Iyyov ad-netzach</em>)—The noun <em>av</em> (אָב, father) here likely means \"my desire\" (ancient versions interpret variously). The verb <em>bachan</em> (בָּחַן, \"to test, examine\") and <em>netzach</em> (נֶצַח, end, perpetuity) suggest thorough testing. The phrase <strong>because of his answers for wicked men</strong> (עַל־תְּשֻׁבֹת בְּאַנְשֵׁי־אָוֶן) uses <em>teshuvah</em> (תְּשׁוּבָה, answer, reply) and <em>aven</em> (אָוֶן, wickedness, iniquity). Elihu wants Job tested exhaustively because his words align with the wicked's theology—questioning God's justice.<br><br>Elihu's desire for Job's continued testing is harsh, even cruel. Yet God permits Job's testing for redemptive purposes (42:5, \"now mine eye seeth thee\"). Peter explains: trials test faith like fire refines gold (1 Peter 1:6-7). James adds: testing produces perseverance and maturity (James 1:2-4). Yet we must not desire others' prolonged suffering—that's vindictiveness. God alone knows the proper measure and duration of trials. Christ endured ultimate testing (Hebrews 4:15, tempted in all points) to sympathize with our testing.",
            "historical": "Ancient wisdom tradition valued testing/proving righteousness (Abraham tested in Genesis 22, Israel tested in wilderness, Deuteronomy 8:2). Yet Job's friends and Elihu wrongly assume all testing reveals hidden sin. NT clarifies: testing can prove faith genuine (1 Peter 1:7), produce perseverance (James 1:3), or conform to Christ's image (Romans 8:28-29). Job's testing ultimately served apologetic purposes (Job 1-2, answering Satan's accusation) and revelatory purposes (Job 42:5, deepening knowledge of God).",
            "questions": [
                "How do we understand the purpose of prolonged trials in light of God's goodness?",
                "What is appropriate versus inappropriate response to others' suffering?",
                "How does Christ's experience of testing (Hebrews 2:18, 4:15) provide comfort in trials?"
            ]
        },
        "37": {
            "analysis": "<strong>For he addeth rebellion unto his sin</strong> (כִּי־יֹסִיף עַל־חַטָּאתוֹ פֶשַׁע, <em>ki-yosiph al-chattato pesha</em>)—The verb <em>yasaph</em> (יָסַף, \"to add\") indicates compounding. The noun <em>pesha</em> (פֶּשַׁע, rebellion, transgression) is stronger than <em>chatta't</em> (חַטָּאת, sin, missing the mark). Elihu accuses Job of adding deliberate rebellion to sin. The phrase <strong>he clappeth his hands among us</strong> (בֵּינֵינוּ יִסְפּוֹק, <em>benenu yispoq</em>) uses <em>saphaq</em> (סָפַק, \"to clap\"), possibly meaning mockery or defiant gesture. The phrase <strong>multiplieth his words against God</strong> (וְיֶרֶב אֲמָרָיו לָאֵל, <em>ve-yerev amarav la-El</em>) accuses Job of excessive speech against God.<br><br>Elihu misunderstands Job's lament as rebellion. Yet God will vindicate Job (42:7). This teaches discernment: honest questioning isn't rebellion. The Psalms model bringing raw emotions to God (Psalms 13, 22, 88). Lament is faith's cry when praise seems impossible. Jesus Himself cried, \"My God, my God, why hast thou forsaken me?\" (Mark 15:34). The gospel permits—even requires—brutal honesty before God. Christ bore actual rebellion (Isaiah 53:5, \"the chastisement of our peace was upon him\") so our honest struggles wouldn't be counted as rebellion.",
            "historical": "Ancient Near Eastern piety typically demanded stoic acceptance of divine decrees. Lament was permitted but within limits—excessive questioning risked blasphemy. Biblical faith uniquely permits profound lament and questioning (Habakkuk, Jeremiah, Psalms) while maintaining ultimate submission. Elihu reflects conventional piety that mistakes honesty for rebellion. Jesus's Gethsemane prayer (\"if it be possible, let this cup pass,\" Matthew 26:39) models combining honest desire with submission (\"nevertheless not as I will, but as thou wilt\").",
            "questions": [
                "How do we distinguish between faithful lament and sinful rebellion against God?",
                "What does Jesus's cry of dereliction (Mark 15:34) teach about bringing pain to God?",
                "How can we create spaces where honest struggle with God is welcomed rather than condemned?"
            ]
        }
    },
    "35": {
        "12": {
            "analysis": "<strong>There they cry, but none giveth answer</strong> (שָׁם יִצְעֲקוּ וְלֹא יַעֲנֶה, <em>sham yitz'aqu velo ya'aneh</em>)—The verb <em>tsa'aq</em> (צָעַק, \"to cry out\") indicates distress calls. The negative <em>lo ya'aneh</em> (\"none answers\") reflects divine silence. The phrase <strong>because of the pride of evil men</strong> (מִפְּנֵי גְּאוֹן רָעִים, <em>mippene ge'on ra'im</em>) gives the reason: <em>ga'on</em> (גָּאוֹן, pride, arrogance) prevents God from answering. Elihu argues the wicked's prayers go unanswered due to pride, not divine indifference. This echoes Proverbs 28:9: \"He that turneth away his ear from hearing the law, even his prayer shall be abomination.\"<br><br>Unanswered prayer is theology's pastoral crisis. Elihu attributes it to pride. Yet Scripture reveals multiple reasons: hidden sin (Psalm 66:18), wrong motives (James 4:3), unforgiving spirit (Mark 11:25), or divine timing (Habakkuk 2:3). Sometimes God's silence is test, not rejection (Psalm 22:1-2). The gospel transforms prayer: Christ's intercession ensures access (Hebrews 4:16, 7:25). We pray not in our merit but in His name (John 14:13-14). Even when answers delay, we're assured of God's listening ear (1 Peter 3:12).",
            "historical": "Ancient Near Eastern religions featured capricious deities requiring appeasement. Israelite faith distinguished Yahweh as hearing righteous prayers (Psalm 34:15, 145:18-19) but resisting the proud (Proverbs 3:34, James 4:6). Temple liturgy emphasized proper approach to God. Prophets condemned external religiosity without heart change (Isaiah 1:15, 58:3-9). Elihu's theology aligns with prophetic tradition: God requires humble, righteous prayer, not mere ritualistic crying out.",
            "questions": [
                "How do we respond faithfully when prayers seem unanswered?",
                "What role does humility play in effective prayer?",
                "How does Christ's mediation ensure our prayers are heard even when answers are delayed?"
            ]
        },
        "13": {
            "analysis": "<strong>Surely God will not hear vanity</strong> (אַךְ־שָׁוְא לֹא־יִשְׁמַע אֵל, <em>akh-shav' lo-yishma El</em>)—The noun <em>shav</em> (שָׁוְא, vanity, emptiness, falsehood) describes worthless prayers. God doesn't hear (<em>shama</em>, שָׁמַע) empty religiosity. The phrase <strong>neither will the Almighty regard it</strong> (וְשַׁדַּי לֹא יְשׁוּרֶנָּה, <em>ve-Shaddai lo yeshurenah</em>) uses <em>shuwr</em> (שׁוּר, \"to see, look at, regard\"). Both covenant names (El, Shaddai) emphasize God's character as refusing hollow worship. This echoes Jesus: \"This people draweth nigh unto me with their mouth... but their heart is far from me\" (Matthew 15:8).<br><br>Elihu rightly condemns empty religiosity but wrongly assumes Job's prayers are vain. The gospel reveals a profound truth: God doesn't hear our prayers because they're eloquent or worthy but because of Christ's mediation. We approach \"in Jesus's name\" (John 14:13-14), not our own merit. Even our weak prayers are heard (Romans 8:26, \"the Spirit itself maketh intercession for us with groanings which cannot be uttered\"). Christ transforms our vanity into acceptable worship through His perfect priesthood.",
            "historical": "Prophetic tradition consistently condemned empty worship: Isaiah 1:11-15 (God sick of sacrifices without justice), Amos 5:21-24 (\"I hate your feast days\"), Micah 6:6-8 (what does God require? justice, mercy, humility). Jesus continued this: Matthew 6:5-8 (against vain repetitions), John 4:23-24 (worship in spirit and truth). Reformation recovered this: true worship requires faith, not mere external performance. Elihu stands in this tradition, though he wrongly applies it to Job.",
            "questions": [
                "How do we ensure our prayers aren't merely vain repetition but genuine communion with God?",
                "What makes worship acceptable to God?",
                "How does Christ's mediation transform our imperfect prayers into acceptable offerings?"
            ]
        },
        "14": {
            "analysis": "<strong>Although thou sayest thou shalt not see him</strong> (אַף כִּי־תֹאמַר לֹא תְשׁוּרֶנּוּ, <em>aph ki-tomar lo teshurennu</em>)—The phrase refers to Job's complaint of God's hiddenness (Job 9:11, 13:24, 23:8-9). The verb <em>shuwr</em> (שׁוּר, \"to see, perceive\") indicates Job feels God is invisible, absent. The phrase <strong>yet judgment is before him</strong> (דִּין לְפָנָיו, <em>din lephanav</em>) uses <em>din</em> (דִּין, judgment, justice), assuring that God's justice operates despite appearances. The phrase <strong>therefore trust thou in him</strong> (וּתְחוֹלֵל לוֹ, <em>utecholel lo</em>) uses <em>chul</em> (חוּל, \"to wait, hope, trust\"). Elihu counsels Job to trust despite God's perceived absence.<br><br>The hiddenness of God (<em>Deus absconditus</em>) is profound theological theme. Isaiah 45:15: \"Verily thou art a God that hidest thyself.\" Yet Psalm 22:24 assures: \"He hath not despised nor abhorred the affliction of the afflicted; neither hath he hid his face from him.\" Job experiences God's felt absence, not actual abandonment. Christ endured ultimate God-forsakenness (Mark 15:34) so believers need never be truly abandoned (Hebrews 13:5). Faith trusts God's character when unable to trace His hand (Romans 8:24-25, \"hope that is seen is not hope\").",
            "historical": "Ancient Near Eastern religions offered tangible divine presence through idols and temples. Israel's prohibition of images and experience of exile created crises of divine absence. Prophets addressed this: Hosea's God withdrawing from unfaithful Israel (Hosea 5:6, 15), Isaiah's hidden God (Isaiah 8:17), Jeremiah's absent God during exile. Yet prophetic faith maintained confidence in covenant faithfulness despite felt absence. This prepared for NT faith: walking by faith, not sight (2 Corinthians 5:7).",
            "questions": [
                "How do we maintain faith when God seems absent or silent?",
                "What is the difference between God's felt absence and actual abandonment?",
                "How does Christ's experience of forsakenness (Mark 15:34) ensure believers are never truly abandoned?"
            ]
        },
        "15": {
            "analysis": "<strong>But now, because it is not so, he hath visited in his anger</strong> (וְעַתָּה כִּי־אַיִן פָּקַד אַפּוֹ, <em>ve'attah ki-ayin paqad appo</em>)—The text is difficult (ancient versions vary). The verb <em>paqad</em> (פָּקַד) means \"to visit, attend to, punish.\" The noun <em>aph</em> (אַף, anger, wrath) indicates divine judgment. Elihu seems to say God hasn't yet fully visited in wrath as Job deserves. The phrase <strong>yet he knoweth it not in great extremity</strong> (וְלֹא־יָדַע בַּפַּשׁ מְאֹד, <em>velo-yada bapash me'od</em>) uses <em>pash</em> (פַּשׁ, meaning uncertain, possibly \"transgression\" or \"extremity\"). This verse's obscurity reflects textual challenges in Job.<br><br>Despite textual difficulty, the sense seems to be that Job doesn't recognize his situation properly—either God's mercy in restraining full wrath or Job's actual guilt. Yet God's final verdict contradicts Elihu's assessment. This teaches humility in interpreting others' suffering. Romans 11:33-34 declares: \"O the depth of the riches both of the wisdom and knowledge of God! how unsearchable are his judgments!\" We must resist simplistic explanations of complex suffering. The gospel reveals God's wrath fell fully on Christ (Romans 3:25, propitiation), ensuring believers experience discipline, not punitive wrath (Hebrews 12:6-8).",
            "historical": "Ancient Near Eastern texts attempted to explain suffering through divine anger, demonic activity, or cosmic disorder. Job's friends and Elihu assume divine anger causes Job's suffering. Yet God's speeches (chapters 38-41) neither confirm nor deny this—instead transcending the framework entirely. NT distinguishes God's wrath on sin (Romans 1:18, John 3:36) from His fatherly discipline of believers (Hebrews 12:6). Job stands between these testaments, experiencing the mystery of suffering without full gospel clarity.",
            "questions": [
                "How do we avoid simplistic explanations when interpreting suffering?",
                "What is the difference between divine wrath and divine discipline?",
                "How does Christ's bearing God's wrath (Romans 5:9) change how believers experience suffering?"
            ]
        },
        "16": {
            "analysis": "<strong>Therefore doth Job open his mouth in vain</strong> (וְאִיּוֹב הֶבֶל יִפְצֶה־פִּיהוּ, <em>ve-Iyyov hevel yiphtseh-pihu</em>)—The noun <em>hevel</em> (הֶבֶל, vanity, breath, emptiness) is Ecclesiastes' key word—all is vanity. The verb <em>patsah</em> (פָּצָה, \"to open wide\") suggests excessive speech. The phrase <strong>he multiplieth words without knowledge</strong> (בִּבְלִי־דַעַת מִלִּין יַכְבִּר, <em>bivli-da'at millin yakhbir</em>) uses <em>kavar</em> (כָּבַר, \"to multiply, make many\"). Elihu accuses Job of verbose ignorance. Yet God vindicates Job's speech (42:7), showing Elihu's judgment was premature and partially wrong. This teaches the danger of judging others' theology while in the midst of their suffering.<br><br>The charge of multiplying words without knowledge will ironically fall on Elihu himself when God speaks (38:2 parallels this language, though directed at Job). We all speak with incomplete understanding (1 Corinthians 13:9, \"we know in part\"). The gospel provides humility: we depend on divine revelation, not human wisdom. Christ, God's ultimate Word (John 1:1), alone speaks with perfect knowledge. Our theological speech must maintain epistemic modesty, recognizing the limits of human understanding while trusting divine self-disclosure in Scripture.",
            "historical": "Ancient wisdom tradition valued concise, weighty speech over verbosity. Proverbs 10:19: \"In the multitude of words there wanteth not sin.\" Ecclesiastes 5:2-3: \"Be not rash with thy mouth... a fool's voice is known by multitude of words.\" Yet lament psalms and prophetic oracles could be lengthy. The issue isn't word count but whether speech aligns with divine truth. Job's speeches, though extensive, God vindicates as substantially right (42:7). Elihu and friends spoke much but missed truth—demonstrating form doesn't guarantee content.",
            "questions": [
                "How do we discern when extensive speech is necessary lament versus vain multiplication of words?",
                "What does God's vindication of Job teach about speaking honestly in suffering?",
                "How does Christ as God's perfect Word (John 1:1, 14) relativize all human theological speech?"
            ]
        }
    },
    "36": {
        "27": {
            "analysis": "<strong>For he maketh small the drops of water</strong> (כִּי יְגָרַע נִטְפֵי־מָיִם, <em>ki yegara nitpei-mayim</em>)—The verb <em>gara</em> (גָּרַע, \"to diminish, withdraw\") and noun <em>neteph</em> (נֶטֶף, drop) describe God drawing up water particles. This is ancient description of the water cycle: evaporation. The phrase <strong>they pour down rain according to the vapour thereof</strong> (יָזֹקּוּ מָטָר לְאֵדוֹ, <em>yazoqqu matar le-edo</em>) uses <em>zuq</em> (זוּק, \"to pour out, filter\") and <em>ed</em> (אֵד, mist, vapor). Elihu describes condensation and precipitation—God's control over meteorological processes. This anticipates modern understanding of evaporation-condensation-precipitation cycle.<br><br>Elihu's nature theology points to divine wisdom in creation (Psalm 104:13-14, 147:8). God's governance isn't merely moral but cosmic—controlling weather patterns. Jesus demonstrated this authority: calming the storm (Mark 4:39), \"What manner of man is this, that even the wind and the sea obey him?\" The incarnate Logos (John 1:3, \"all things were made by him\") who designed the water cycle entered creation to redeem it (Colossians 1:16-20). Nature's order testifies to God's faithfulness (Genesis 8:22) and points toward new creation's restoration (Revelation 21:1).",
            "historical": "Ancient Near Eastern cultures mythologized weather—Baal controlled rain in Canaanite religion. Israel's theology demythologized nature: Yahweh alone controls weather (Psalm 135:6-7, 147:8, Jeremiah 14:22). God withholds rain as judgment (Deuteronomy 11:17, 1 Kings 17:1) and sends it as blessing (Leviticus 26:4, Deuteronomy 28:12). Elihu's description of the water cycle, though pre-scientific, accurately observes natural phenomena as divine design, anticipating modern hydrology while maintaining theological interpretation.",
            "questions": [
                "How does observation of natural processes (like the water cycle) reveal God's wisdom and faithfulness?",
                "What is the relationship between God's sovereignty over nature and Christ's miracles?",
                "How should scientific understanding of natural phenomena inform rather than diminish theological wonder?"
            ]
        },
        "28": {
            "analysis": "<strong>Which the clouds do drop and distil upon man abundantly</strong> (אֲשֶׁר־יִזְּלוּ שְׁחָקִים יִרְעֲפוּ עֲלֵי אָדָם רָב, <em>asher-yizzelu shechakim yir'apu alei adam rav</em>)—The verb <em>nazal</em> (נָזַל, \"to flow, drip, distill\") and <em>ra'aph</em> (רָעַף, \"to drop, drip abundantly\") both describe precipitation. The noun <em>shachaq</em> (שַׁחַק, clouds, skies) and phrase \"upon man abundantly\" (<em>alei adam rav</em>) emphasize God's provision through rain for humanity. This is providence theology: God sustains creation through natural processes. Psalm 65:9-11 celebrates: \"Thou visitest the earth, and waterest it... thou preparest them corn.\"<br><br>Rain as divine gift appears throughout Scripture: blessing for obedience (Deuteronomy 28:12), withheld for disobedience (Deuteronomy 11:17). Jesus points to God's indiscriminate provision: \"he maketh his sun to rise on the evil and on the good, and sendeth rain on the just and on the unjust\" (Matthew 5:45). This common grace demonstrates God's goodness to all (Acts 14:17, \"gave us rain from heaven, and fruitful seasons\"). The gospel reveals greater provision: the Spirit poured out like rain (Isaiah 44:3, Joel 2:28-29, Acts 2:17-18), bringing spiritual fruitfulness.",
            "historical": "Ancient Near Eastern agricultural societies depended entirely on rainfall—no irrigation systems in most regions. Rain's arrival or failure determined survival or famine. Canaanite religion worshiped Baal as rain-giver, requiring ritual prostitution to ensure fertility. Israel's exclusive worship of Yahweh as rain-giver was countercultural. Elijah's contest on Carmel (1 Kings 18) demonstrated Yahweh's exclusive control over rain. Elihu's theology continues this: rain evidences divine providence, not impersonal natural forces or pagan deities.",
            "questions": [
                "How does God's provision through natural processes (rain, seasons) demonstrate His faithfulness?",
                "What does rain on just and unjust (Matthew 5:45) teach about common grace?",
                "How does the Spirit's outpouring (Joel 2:28, Acts 2:17) relate to God's provision of physical rain?"
            ]
        },
        "29": {
            "analysis": "<strong>Also can any understand the spreadings of the clouds</strong> (אַף אִם־יָבִין מִפְרְשֵׂי־עָב, <em>aph im-yavin miphresei-av</em>)—The verb <em>bin</em> (בִּין, \"to understand, discern\") questions human comprehension. The noun <em>mipras</em> (מִפְרָשׂ, spreading, expanse) describes clouds' formation and movement. The phrase <strong>or the noise of his tabernacle</strong> (תְּשֻׁאוֹת סֻכָּתוֹ, <em>teshu'ot sukkato</em>) uses <em>teshu'ah</em> (תְּשֻׁאָה, crash, din, thunder) and <em>sukkah</em> (סֻכָּה, booth, tabernacle). God's \"tabernacle\" is the sky/clouds from which He thunders. This rhetorical question anticipates God's speeches (chapters 38-41), which repeatedly ask Job, \"Can you...?\" to humble human pretension.<br><br>The limits of human knowledge is wisdom literature's recurring theme. Job 28:12-28 asks, \"Where shall wisdom be found?\" concluding only God understands (28:23). Ecclesiastes acknowledges human ignorance (8:17, 11:5). Paul declares God's wisdom unsearchable (Romans 11:33). Yet the gospel reveals what nature conceals: \"the mystery which hath been hid from ages... Christ in you, the hope of glory\" (Colossians 1:26-27). We cannot fathom cloud formations, but God has revealed Himself in Christ (John 1:18, Hebrews 1:1-2).",
            "historical": "Ancient Near Eastern texts attribute weather phenomena to divine activity but offer little scientific explanation. Job's speeches include sophisticated nature observation (chapters 36-37, 38-41), yet maintain epistemological humility—natural phenomena exceed human comprehension. Modern meteorology explains cloud formation, yet mysteries remain (chaos theory, precise long-term prediction). Elihu's point transcends scientific progress: creation's complexity testifies to Creator's incomprehensibility. Advancement in knowledge doesn't eliminate wonder but deepens it.",
            "questions": [
                "How does scientific progress in understanding natural phenomena (like clouds) affect theological wonder?",
                "What is the relationship between God's inscrutability in nature and His self-revelation in Scripture?",
                "How should creation's complexity humble human presumption about understanding God's ways?"
            ]
        },
        "30": {
            "analysis": "<strong>Behold, he spreadeth his light upon it</strong> (הֵן־פָּרַשׂ עָלָיו אוֹרוֹ, <em>hen-paras alav oro</em>)—The verb <em>paras</em> (פָּרַשׂ, \"to spread out, extend\") and <em>or</em> (אוֹר, light) likely refer to lightning spreading across clouds or sky. The phrase <strong>and covereth the bottom of the sea</strong> (וְשָׁרְשֵׁי הַיָּם כִּסָּה, <em>ve-shorshei hayyam kissah</em>) uses <em>shoresh</em> (שֹׁרֶשׁ, root, bottom) and <em>kasah</em> (כָּסָה, \"to cover\"). This may describe God's light penetrating ocean depths or covering the sea with clouds/darkness. The imagery emphasizes God's comprehensive control—from sky to sea depths.<br><br>God's sovereignty extends to all creation's extremes: highest heavens to deepest seas (Psalm 139:7-10, Amos 9:2-3). Lightning displays raw divine power (Psalm 18:14, 77:18, 97:4). Yet Christ walked on water (Matthew 14:25), calmed storms (Mark 4:39), demonstrating authority over creation's most fearsome elements. Revelation 10:5-6 depicts Christ standing on sea and land, swearing by Creator. The gospel reveals that creation's Lord entered creation as creature, subjected Himself to natural forces (hunger, thirst, weariness), died under creation's curse, then rose conquering all (Colossians 1:16-20).",
            "historical": "Ancient Near Eastern cosmology portrayed sea as chaos requiring divine control. Baal myths featured conflict with sea-god Yam. Genesis 1:2, 6-10 presents Yahweh effortlessly ordering waters. Psalms celebrate God's mastery over seas (Psalm 29:3, 65:7, 89:9, 93:3-4, 107:23-30). Job 38:8-11 will depict God setting sea's boundaries. Elihu's imagery continues this: God controls both atmospheric phenomena (lightning) and maritime depths. This theological claim against pagan cosmologies asserts Yahweh's exclusive, comprehensive sovereignty.",
            "questions": [
                "How do natural phenomena like lightning and ocean depths reveal God's power?",
                "What does Christ's authority over natural forces (storms, sea) demonstrate about His identity?",
                "How should God's comprehensive sovereignty over creation affect our trust during life's storms?"
            ]
        },
        "31": {
            "analysis": "<strong>For by them judgeth he the people</strong> (כִּי־בָם יָדִין עַמִּים, <em>ki-vam yadin ammim</em>)—The phrase \"by them\" likely refers to meteorological phenomena (rain, lightning, clouds) as instruments of divine judgment. The verb <em>din</em> (דִּין, \"to judge, govern\") has both judicial and providential senses. The phrase <strong>he giveth meat in abundance</strong> (יִתֶּן־אֹכֶל לְמַכְבִּיר, <em>yitten-okhel lemakvir</em>) uses <em>okhel</em> (אֹכֶל, food) and <em>kabiyr</em> (כַּבִּיר, abundant, mighty). Weather serves both judgment (withholding rain, sending destructive storms) and blessing (providing rain for crops).<br><br>This dual nature of divine providence—blessing and judgment—appears throughout Scripture. Deuteronomy 11:13-17 promises rain for obedience, drought for disobedience. Amos 4:7-9 describes God withholding rain as judgment. Yet Matthew 5:45 emphasizes indiscriminate provision: rain on just and unjust. The tension resolves eschatologically: common grace now provides for all, but final judgment separates (Matthew 25:31-46). The gospel reveals ultimate judgment fell on Christ (2 Corinthians 5:21), ensuring believers receive only providential care, never condemnation (Romans 8:1).",
            "historical": "Ancient covenant theology explicitly linked weather to obedience. Leviticus 26:3-4 promises rain and crops for obedience; vv. 18-20 threaten drought for disobedience. Deuteronomy 28:12, 23-24 repeats this covenant structure. Prophets interpreted drought as divine judgment (Jeremiah 14:1-9, Haggai 1:10-11). Jesus and NT writers shift focus from national-temporal blessings to spiritual-eternal (Matthew 6:19-33, Philippians 4:11-13). Yet natural disasters still display God's sovereignty, calling to repentance (Luke 13:1-5, Revelation 16:8-9).",
            "questions": [
                "How do we understand God's use of natural phenomena for both blessing and judgment?",
                "What is the relationship between God's providential care and His judicial activity?",
                "How does the gospel transform our interpretation of natural disasters and blessings?"
            ]
        },
        "32": {
            "analysis": "<strong>With clouds he covereth the light</strong> (עַל־כַּפַּיִם כִּסָּה־אוֹר, <em>al-kappayim kissah-or</em>)—The phrase \"upon palms\" (<em>al-kappayim</em>) may mean God holds lightning in His hands (literal or poetic). The verb <em>kasah</em> (כָּסָה, \"to cover\") and <em>or</em> (אוֹר, light, possibly lightning) creates vivid imagery of divine control. The phrase <strong>and commandeth it not to shine by the cloud that cometh betwixt</strong> (וַיְצַו עָלֶיהָ בְּמַפְגִּיעַ, <em>vaytzav aleha bemapgia</em>) uses <em>tzavah</em> (צָוָה, \"to command\") and <em>paga</em> (פָּגַע, \"to meet, encounter, intercede\"). God commands lightning where to strike, clouds when to obscure light. This emphasizes meticulous divine sovereignty over natural forces.<br><br>God's command over creation appears from Genesis 1 (\"Let there be...\") through Revelation. Psalm 148:8 declares: \"Fire, and hail; snow, and vapour; stormy wind fulfilling his word.\" Jesus commanded weather (Mark 4:39, \"Peace, be still\") and it obeyed, demonstrating divine authority. The gospel reveals Christ is Creator-Logos (John 1:3, Colossians 1:16) who sustains all things by His powerful word (Hebrews 1:3). Natural forces that seem chaotic or random actually fulfill divine purpose. This provides assurance: no storm, disaster, or circumstance escapes God's sovereign command.",
            "historical": "Ancient Near Eastern religions portrayed nature as semi-autonomous or controlled by competing deities. Biblical theology consistently affirms Yahweh's absolute control over all natural phenomena (Psalm 29, entire psalm on God's voice in thunderstorm). Israelite monotheism was radical: one God created and controls everything. No competing powers, no autonomous nature. Elihu's theology continues this: lightning doesn't strike randomly but according to divine command. This prepared for NT Christology: the incarnate Word who commands creation.",
            "questions": [
                "How does God's meticulous control over natural phenomena provide comfort during life's chaos?",
                "What does Christ's authority over nature reveal about His identity and relationship to creation?",
                "How should belief in divine sovereignty over natural forces affect environmental theology?"
            ]
        },
        "33": {
            "analysis": "<strong>The noise thereof sheweth concerning it</strong> (יַגִּיד עָלָיו רֵעוֹ, <em>yaggid alav re'o</em>)—The verse is textually difficult. The noun <em>rea</em> (רֵעַ) can mean \"friend, companion, thunder.\" Some translations: \"its crashing declares His presence\" (ESV). The phrase <strong>the cattle also concerning the vapour</strong> (מִקְנֶה אַף עַל־עוֹלֶה, <em>miqneh aph al-oleh</em>) is obscure. Possibly: even cattle sense approaching storms. Ancient observation noted animals' sensitivity to weather changes. Elihu's point: all creation responds to God's meteorological works—thunder proclaims His presence, animals sense atmospheric shifts.<br><br>Creation testifies to Creator (Psalm 19:1, \"The heavens declare the glory of God\"). Romans 1:20 argues God's invisible attributes are \"clearly seen... by the things that are made.\" Thunder's voice symbolizes divine speech (Psalm 29:3-9, Revelation 4:5, 8:5). Jesus compared His return to lightning (Matthew 24:27). The gospel reveals God spoke ultimately through His Son (Hebrews 1:1-2), not merely thunder and natural phenomena. Yet creation's testimony continues, pointing toward Creator, sustaining general revelation until Christ's return brings perfect knowledge (1 Corinthians 13:12).",
            "historical": "Ancient peoples interpreted natural phenomena as divine communication. Thunder was considered gods' voices across cultures. Israel's theology agreed—thunder is God's voice (Exodus 19:16, Job 37:2-5, Psalm 29)—but demythologized it: not capricious divine anger but covenant Lord's majestic presence. Animal behavior forecasting weather was common ancient observation (still valid: animals detect barometric pressure changes, earthquakes). Elihu's nature theology grounds in observation, interpreted theologically: creation reveals Creator's attributes and activity.",
            "questions": [
                "How does creation's testimony through natural phenomena point toward God's attributes?",
                "What is the relationship between general revelation (nature) and special revelation (Scripture, Christ)?",
                "How should we interpret dramatic natural phenomena (storms, earthquakes) theologically without superstition?"
            ]
        }
    }
}

# Path to the file
file_path = Path('/Users/kennethreitz/repos/kjvstudy.org/kjvstudy_org/data/verse_commentary/job.json')

# Read existing data
with open(file_path) as f:
    data = json.load(f)

# Merge new commentary
for chapter, verses in NEW_COMMENTARY.items():
    if chapter not in data['commentary']:
        data['commentary'][chapter] = {}
    for verse, commentary in verses.items():
        data['commentary'][chapter][verse] = commentary

# Write updated data back
with open(file_path, 'w') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print(f'Successfully added {sum(len(v) for v in NEW_COMMENTARY.values())} verses to Job commentary')
print('Breakdown by chapter:')
for chapter in sorted(NEW_COMMENTARY.keys(), key=int):
    print(f'  Chapter {chapter}: {len(NEW_COMMENTARY[chapter])} verses')
