#!/usr/bin/env python3
"""Add commentary for John 13:6-12"""

import json
from pathlib import Path

# File path
json_file = Path("/Users/kennethreitz/repos/kjvstudy.org/kjvstudy_org/data/verse_commentary/john.json")

# Read existing data
with open(json_file, 'r', encoding='utf-8') as f:
    data = json.load(f)

# Ensure chapter 13 exists
if "13" not in data["commentary"]:
    data["commentary"]["13"] = {}

# Commentary for each verse
commentaries = {
    "6": {
        "analysis": "<strong>Then cometh he to Simon Peter: and Peter saith unto him, Lord, dost thou wash my feet?</strong> Peter's reaction to Jesus washing his feet reveals the natural human recoil from grace—the pride that resists receiving unmerited service. The phrase <strong>Lord, dost thou wash my feet?</strong> (Κύριε, σύ μου νίπτεις τοὺς πόδας/<em>Kyrie, sy mou nipteis tous podas</em>) places emphatic pronouns in stark contrast: <em>Thou</em> (σύ)—the Master, and <em>my</em> (μου)—the servant. The present tense <em>nipteis</em> (wash) suggests Peter interrupted Jesus mid-action, shocked at what was unfolding.<br><br>The verb νίπτω (<em>niptō</em>) specifically means to wash a part of the body (usually feet or hands), distinct from λούω (<em>louō</em>), which means to bathe the whole body—a distinction Jesus exploits in verse 10. Footwashing was the task of the lowliest household slave, so degrading that Jewish law forbade requiring it of Hebrew servants (only Gentile slaves). Yet here stands the Lord of Glory, the one Peter confessed as <strong>the Christ, the Son of the living God</strong> (Matthew 16:16), performing the most menial service.<br><br>Peter's question contains both reverence ('Lord') and resistance. He grasps the incongruity but not yet the theology. This scene dramatizes the incarnation itself: the Word became flesh and <em>took on the form of a servant</em> (Philippians 2:7). The Creator serves His creatures. The Judge cleanses the guilty. Pride says, 'I must serve You'; grace says, 'Let Me serve you.'",
        "historical": "This scene occurs in the upper room during the Last Supper, hours before Jesus's arrest (John 13:1-2). Jewish Passover meals required ritual purity, and guests arriving with dusty feet from Jerusalem's streets would need washing. Normally, a household servant performed this task upon arrival. The disciples' failure to wash one another's feet reveals their persistent dispute about greatness (Luke 22:24)—each considered himself too important to serve.<br><br>First-century Jewish culture was intensely hierarchical. Rabbis held exalted status; disciples served masters, never the reverse. Peter had witnessed Jesus's divine power—walking on water, raising the dead, commanding nature. The cognitive dissonance of seeing this Lord kneel before him with a water basin was profound. Roman foot-washing customs differed somewhat from Jewish, but throughout the ancient Near East, the act signified the washer's inferior status. For Jesus to wash His disciples' feet inverted all social and religious order.",
        "questions": [
            "Why does receiving unmerited service from Christ feel more difficult than serving Him through our own efforts?",
            "In what ways does our spiritual pride manifest as resistance to God's grace rather than gratitude for it?",
            "How does Jesus's willingness to perform the most degrading service challenge our concern for status and reputation?"
        ]
    },
    "7": {
        "analysis": "<strong>Jesus answered and said unto him, What I do thou knowest not now; but thou shalt know hereafter.</strong> Christ's response to Peter's protest introduces the pedagogical principle that divine actions often precede human understanding. The phrase <strong>What I do</strong> (ἐγὼ ποιῶ/<em>egō poiō</em>) emphasizes Jesus's sovereignty—<em>I</em> am doing this, regardless of your comprehension. The present tense <em>poiō</em> stresses ongoing action with multiple layers of meaning.<br><br>The contrast between <strong>now</strong> (ἄρτι/<em>arti</em>) and <strong>hereafter</strong> (μετὰ ταῦτα/<em>meta tauta</em>) structures Christian experience: we walk by faith, not sight (2 Corinthians 5:7). <em>Arti</em> indicates the immediate present moment—Peter in his pre-cross confusion cannot grasp what unfolds. <em>Meta tauta</em> (literally 'after these things') points beyond the crucifixion, resurrection, and Pentecost to the Spirit-enlightened understanding that follows.<br><br>The verb <strong>knowest</strong> (οἶδας/<em>oidas</em>) refers to intuitive, perceptive knowledge, while <strong>shalt know</strong> (γνώσῃ/<em>gnōsē</em>) uses γινώσκω (<em>ginōskō</em>), meaning experiential knowledge gained through relationship. Peter will move from confused observation to participated understanding. This parallels Jesus's earlier words: <em>What I do thou knowest not now</em> applies to the cross itself—disciples flee in confusion, but later understand redemption accomplished.",
        "historical": "This exchange occurred within hours of Jesus's betrayal. The disciples remained confused about Jesus's mission despite three years of teaching. They expected Messiah to overthrow Rome and establish David's throne, not die as a criminal. Jesus's cryptic references to death and resurrection (Mark 8:31-33) bewildered them—Peter had even rebuked Jesus for such talk. Here Jesus acknowledges the gap between event and understanding, promising illumination would come 'after these things'—fulfilled when the risen Christ opened their minds to understand the Scriptures (Luke 24:45) and the Spirit came at Pentecost (John 14:26). The early church treasured this verse as validation for their post-resurrection theological development, understanding depths in Jesus's actions they'd missed at the time.",
        "questions": [
            "What does it mean to trust Christ's actions before understanding His purposes, and how does this apply to suffering or confusion in your life?",
            "How does the promise of future understanding sustain faith during present darkness or theological perplexity?",
            "In what ways has your understanding of Scripture or God's work deepened 'hereafter'—after experiencing what you once merely heard about?"
        ]
    },
    "8": {
        "analysis": "<strong>Peter saith unto him, Thou shalt never wash my feet. Jesus answered him, If I wash thee not, thou hast no part with me.</strong> Peter's emphatic refusal—<strong>never</strong> (οὐ μὴ...εἰς τὸν αἰῶνα/<em>ou mē...eis ton aiōna</em>)—uses the strongest Greek negation plus 'unto the age,' creating absolute, eternal refusal. Yet Jesus's response is more absolute still: <strong>If I wash thee not, thou hast no part with me</strong> (Ἐὰν μὴ νίψω σε, οὐκ ἔχεις μέρος μετ' ἐμοῦ/<em>Ean mē nipsō se, ouk echeis meros met' emou</em>).<br><br>The verb <strong>wash</strong> (νίψω/<em>nipsō</em>) shifts from present to aorist subjunctive—not ongoing action but a definitive act with permanent consequences. The phrase <strong>no part with me</strong> (οὐκ ἔχεις μέρος μετ' ἐμοῦ) is covenant language. <em>Meros</em> means portion, share, inheritance—the same term used for Israel's inheritance in the Promised Land (Joshua 19:9). Without Jesus's cleansing, Peter has no share in Christ's kingdom, no inheritance, no fellowship.<br><br>This dialogue transcends literal foot-washing to address soteriological necessity. Peter must receive Christ's cleansing or remain eternally separated. Pride that refuses grace is damning pride. We contribute nothing to salvation except the sin requiring it. Christ's work is complete and non-negotiable—we receive it humbly or reject it proudly. Peter's journey from 'never' to 'not my feet only' (v.9) mirrors conversion: from self-sufficient refusal to desperate reception of grace.",
        "historical": "Peter's character oscillates between bold confession and rash presumption. He walked on water then sank in doubt (Matthew 14:28-31). He confessed Jesus as Christ then rebuked Him for predicting death (Matthew 16:16-23). Here Peter's protest stems from misguided devotion—he loves Jesus but misunderstands grace. His 'never' echoes his later 'I will lay down my life for thy sake' (John 13:37), followed by three denials. Peter had to learn that discipleship begins not with brave self-offering but humble reception. The phrase 'no part with me' would resonate deeply with Jewish disciples familiar with inheritance language from Torah. Being cut off from one's portion meant exclusion from covenant blessings—exactly what Jesus warns Peter faces if he refuses cleansing. Later, Peter's epistles emphasize humility (1 Peter 5:5) and the cleansing blood of Christ (1 Peter 1:18-19), lessons learned through this upper-room exchange.",
        "questions": [
            "How does Peter's 'never' reveal the pride that masquerades as humility or devotion, and where does this appear in your own spiritual life?",
            "What does Jesus's absolute requirement ('If I wash thee not, thou hast no part with me') teach about the non-negotiable necessity of His atoning work?",
            "Why is receiving grace often harder than giving service, and what does this reveal about the human condition?"
        ]
    },
    "9": {
        "analysis": "<strong>Simon Peter saith unto him, Lord, not my feet only, but also my hands and my head.</strong> Peter's characteristic impulsiveness swings from absolute refusal (v.8) to maximal request. The emphatic negation <strong>not...only</strong> (οὐ...μόνον/<em>ou...monon</em>) followed by <strong>but also</strong> (ἀλλὰ καί/<em>alla kai</em>) intensifies his plea. If cleansing by Christ brings fellowship, Peter wants complete cleansing—<strong>my hands and my head</strong> (τὰς χεῖρας καὶ τὴν κεφαλήν/<em>tas cheiras kai tēn kephalēn</em>).<br><br>Peter's request, though sincere, reveals continuing misunderstanding. He grasps that Christ's cleansing is necessary but thinks more ritual washing brings more spiritual benefit. This reflects a works-oriented mindset: if some is good, more is better; if feet-washing grants fellowship, full-body washing grants greater fellowship. Yet grace doesn't operate on quantitative scales. The sufficiency of Christ's work needs no human addition or intensification.<br><br>Peter's response also shows genuine love for Christ. Once convinced that Jesus's washing brings 'part with me,' Peter desires maximum communion. His error isn't in wanting closeness with Christ but in thinking human enthusiasm or religious excess achieves it. This anticipates later misunderstandings about salvation by grace through faith—legalists add requirements, enthusiasts add experiences, but the gospel says Christ's work alone suffices.",
        "historical": "Peter's request makes sense within Jewish purity rituals. Levitical law prescribed washings of hands, feet, and head for priests (Exodus 30:19-21). The Pharisees emphasized ritual hand-washing before meals (Mark 7:2-4). If Jesus's foot-washing symbolized spiritual cleansing, Peter reasoned, complete washing would be better. This reflects the broader Jewish emphasis on ritual purity as means to holiness. What Peter hadn't yet grasped was that Jesus was instituting something entirely new—not enhanced Levitical ritual but spiritual cleansing through His impending death. The church fathers saw Peter's request as emblematic of misguided religious zeal—the desire to add to Christ's sufficient work. Augustine commented that Peter's error wasn't in loving Christ too much but in understanding grace too little.",
        "questions": [
            "In what ways do we, like Peter, try to add to Christ's finished work through increased religious activity or intensity?",
            "How does Peter's swing from 'never' to 'not only my feet' illustrate the volatility of enthusiasm untethered to theological understanding?",
            "What does true faith look like—enthusiastic maximalism or humble reception of what Christ offers?"
        ]
    },
    "10": {
        "analysis": "<strong>Jesus saith to him, He that is washed needeth not save to wash his feet, but is clean every whit: and ye are clean, but not all.</strong> Jesus corrects Peter's misunderstanding with crucial theological distinction. <strong>He that is washed</strong> (ὁ λελουμένος/<em>ho leloumenos</em>) uses the perfect passive participle of λούω (<em>louō</em>)—to bathe the whole body—indicating completed action with ongoing results. This person <strong>needeth not</strong> (οὐ χρείαν ἔχει/<em>ou chreian echei</em>) further bathing, only to <strong>wash his feet</strong> (νίψασθαι τοὺς πόδας/<em>nipsasthai tous podas</em>), using νίπτω (<em>niptō</em>), the verb for partial washing.<br><br>The distinction maps onto Christian soteriology with precision. The complete bath (λούω) represents justification—the once-for-all cleansing from sin's guilt through Christ's blood (Titus 3:5, 'washing of regeneration'). The foot-washing (νίπτω) represents ongoing sanctification—daily cleansing from sin's defilement through confession and Spirit-empowered growth (1 John 1:9, 'If we confess our sins, he is faithful and just to forgive us'). Believers are definitively cleansed (<em>clean every whit</em>—καθαρός ἐστιν ὅλος/<em>katharos estin holos</em>), yet require continual cleansing from worldly contamination.<br><br>The phrase <strong>ye are clean, but not all</strong> (ὑμεῖς καθαροί ἐστε, ἀλλ' οὐχὶ πάντες/<em>hymeis katharoi este, all' ouchi pantes</em>) introduces the sobering reality of Judas's presence. Among the Twelve, eleven had experienced regeneration's bath; one remained spiritually filthy despite outward proximity to Christ. External religious participation doesn't guarantee internal transformation.",
        "historical": "First-century bathing customs illuminate Jesus's metaphor. After visiting the public baths (<em>thermae</em>), a Roman would return home with clean body but dusty feet from walking unpaved streets. Only feet required washing, not re-bathing. Jesus takes this common experience and transforms it into spiritual truth. Jewish purification rituals similarly distinguished complete immersion (mikveh) from partial washing. The once-for-all nature of justification contrasted with the Levitical system's endless repetition of sacrifices—a distinction Hebrews 10:11-14 emphasizes. Jesus's reference to one unclean disciple anticipates verse 11's explanation about Judas. Despite three years with Jesus, witnessing miracles, hearing teaching, Judas remained unregenerate—a warning against presuming external religion equals internal reality. The early church applied this verse both to initial baptism (the bath) and ongoing confession of sin (the foot-washing), seeing sacramental and pastoral implications.",
        "questions": [
            "How does understanding the distinction between definitive cleansing (justification) and ongoing cleansing (sanctification) affect your assurance of salvation and pursuit of holiness?",
            "What 'dust' accumulates on believers' feet through daily living in a fallen world, and how does Christ provide for its cleansing?",
            "What does Judas's presence among the disciples—outwardly identical but spiritually unclean—teach about the dangers of mere external religion?"
        ]
    },
    "11": {
        "analysis": "<strong>For he knew who should betray him; therefore said he, Ye are not all clean.</strong> This verse explains Jesus's cryptic statement in verse 10. The phrase <strong>he knew</strong> (ᾔδει γάρ/<em>ēdei gar</em>) uses the pluperfect form of οἶδα (<em>oida</em>), indicating comprehensive, settled knowledge existing before the moment—Jesus had always known. The participle <strong>who should betray him</strong> (τὸν παραδιδόντα αὐτόν/<em>ton paradidonata auton</em>) uses present tense, suggesting ongoing treachery—Judas's betrayal wasn't sudden impulse but developing conspiracy.<br><br>The verb παραδίδωμι (<em>paradidōmi</em>)—to hand over, betray, deliver up—appears repeatedly in the Passion narrative. Judas <em>paradidōmi</em> Jesus to the authorities (John 18:2), who <em>paradidōmi</em> Him to Pilate (John 18:30), who <em>paradidōmi</em> Him to crucifixion (John 19:16). Yet providentially, the Father <em>paradidōmi</em> the Son for our redemption (Romans 8:32). Human treachery serves divine purposes.<br><br>Jesus's foreknowledge of betrayal intensifies the scene's pathos. He washes the feet of His betrayer. He serves the one plotting His death. This displays both divine omniscience and incomprehensible love—<em>while we were yet sinners, Christ died for us</em> (Romans 5:8). Judas receives the same intimate service as the faithful Eleven, demonstrating that Christ's love extends even to those who reject Him. Yet love spurned becomes judgment. Judas's presence at the foot-washing but exclusion from spiritual cleansing illustrates the tragedy of resisting grace.",
        "historical": "John's Gospel emphasizes Jesus's divine knowledge throughout—He knew what was in man (2:25), knew the Samaritan woman's history (4:18), knew from the beginning who would believe and who would betray (6:64). This foreknowledge doesn't cause Judas's betrayal but reveals Jesus's deity. Judas held the disciples' money bag and regularly stole from it (John 12:6), showing long-standing treachery. Jesus's selection of Judas knowing he would betray raises questions addressed by verse 18: 'that the scripture may be fulfilled.' Judas fulfilled Psalm 41:9—'he that eateth bread with me hath lifted up his heel against me.' Satan entered Judas during this very meal (John 13:27), though Judas had already contracted with the chief priests for thirty silver pieces (Matthew 26:14-16). The early church wrestled with Judas's culpability versus divine sovereignty. Church fathers like Augustine argued Judas acted freely yet within God's sovereign plan—a mystery but not contradiction.",
        "questions": [
            "How does Jesus's foreknowledge of Judas's betrayal yet willingness to wash his feet demonstrate the nature of divine love?",
            "What does Judas's proximity to Jesus—sharing meals, hearing teaching, witnessing miracles—yet remaining spiritually unclean warn about external religion?",
            "How should the reality that Christ's love extends even to His betrayers shape our understanding of evangelism and treatment of enemies?"
        ]
    },
    "12": {
        "analysis": "<strong>So after he had washed their feet, and had taken his garments, and was set down again, he said unto them, Know ye what I have done to you?</strong> Having completed the foot-washing, Jesus resumes His position as teacher (ἀνέπεσεν πάλιν/<em>anepesen palin</em>—reclined again at table) to explain the acted parable. The question <strong>Know ye what I have done?</strong> (Γινώσκετε τί πεποίηκα ὑμῖν;/<em>Ginōskete ti pepoiēka hymin?</em>) uses present tense γινώσκω (<em>ginōskō</em>)—do you understand, perceive, grasp the significance?—with perfect tense πεποίηκα (<em>pepoiēka</em>), emphasizing completed action with abiding results.<br><br>Jesus distinguishes between witnessing an action and comprehending its meaning. The disciples saw Him wash feet; the question is whether they understood the theological, Christological, and ethical implications. This pedagogical method—symbolic action followed by explanation—appears throughout Jesus's ministry (cleansing the temple, cursing the fig tree, instituting the Lord's Supper). Physical actions convey spiritual realities.<br><br>The phrase <strong>what I have done to you</strong> (τί πεποίηκα ὑμῖν) positions disciples as recipients, not spectators. Jesus didn't perform a demonstration for them to observe but an act toward them requiring response. The foot-washing wasn't abstract theology but personal service with direct application. Verses 13-17 will unpack the meaning: Jesus is Lord and Teacher, yet serves; therefore disciples must serve one another. But the deeper meaning connects to verses 8-10: cleansing through Christ brings fellowship, foreshadowing His atoning death that washes away sin.",
        "historical": "Ancient pedagogical methods emphasized imitation of teachers. Disciples watched rabbis' actions as carefully as they heard their words, replicating lifestyle not just learning. Jesus's question 'Know ye what I have done?' invites reflection on meaning, not mere repetition of action. The foot-washing occurred within the Passover meal celebrating Israel's deliverance from Egypt. Just as Passover commemorated physical redemption through the lamb's blood, Jesus's actions pointed toward spiritual redemption through His blood. Church tradition has debated whether to practice literal foot-washing as ordinance (some Anabaptist groups) or understand it as ethical principle (mutual service and humility). Most Reformed interpreters see both spiritual meaning (cleansing through Christ's work) and ethical application (humble service), without making foot-washing a required ritual. Jesus's resumed teaching position after washing feet signifies the union of authority and humility—He serves without surrendering lordship, combining majesty and meekness.",
        "questions": [
            "What is the difference between observing Jesus's actions and understanding their significance, and how does this apply to reading Scripture?",
            "How does Jesus's question 'Know ye what I have done to you?' shift focus from watching to participating, from spectatorship to discipleship?",
            "In what ways does the foot-washing scene reveal both the humility and authority of Christ, and how should this dual reality shape Christian leadership?"
        ]
    }
}

# Add new commentaries to chapter 13
for verse, content in commentaries.items():
    if verse not in data["commentary"]["13"]:
        data["commentary"]["13"][verse] = content
        print(f"Added commentary for John 13:{verse}")
    else:
        print(f"Commentary for John 13:{verse} already exists, skipping")

# Write back to file
with open(json_file, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"\nSuccessfully updated {json_file}")
print(f"Total verses in John 13: {len(data['commentary']['13'])}")
