#!/usr/bin/env python3
"""
Generate proper verse-specific commentary for 20 1 Chronicles verses.
Replaces generic filler with actual theological analysis.
"""

import json
from pathlib import Path

# Define the commentary data
COMMENTARY = {
    "5": {
        "25": {
            "analysis": "<strong>They transgressed</strong> (מָעֲלוּ ma'alu) uses the same Hebrew root as the trespass offering, signifying covenant violation at the deepest level—not mere sin but betrayal of relationship. <strong>Went a whoring after</strong> (וַיִּזְנוּ אַחֲרֵי vayyiznu acharei) employs the graphic metaphor of prostitution, portraying idolatry as spiritual adultery against Yahweh the covenant Husband (cf. Hosea's marriage).<br><br>The irony is devastating: they pursued <strong>the gods of the people of the land, whom God destroyed before them</strong>—worshiping the deities of conquered nations whose impotence had been demonstrated through Israel's conquest. The trans-Jordanian tribes (Reuben, Gad, half-Manasseh) who had received their inheritance first now forfeit it first through apostasy, foreshadowing their exile by Assyria (v. 26).<br><br>The Chronicler emphasizes <strong>the God of their fathers</strong> (אֱלֹהֵי אֲבוֹתֵיהֶם)—covenant continuity from Abraham, Isaac, and Jacob—highlighting that their sin wasn't ignorance but willful rejection of known grace. This pattern of prosperity leading to apostasy (Deuteronomy 8:11-20) haunts Israel's history and warns against the prosperity gospel's dangers.",
            "historical": "Written after Babylonian exile (c. 450-400 BC) to returned Israelites rebuilding Jerusalem, this warning about the trans-Jordanian tribes had prophetic fulfillment. These tribes fell first to Assyrian conquest (732 BC under Tiglath-Pileser III), a century before Judah's exile. The Chronicler uses their apostasy to explain why they were the first to lose their inheritance—a cautionary tale for post-exilic Judah facing similar temptations to syncretism with Persian and Samaritan religious practices.",
            "questions": [
                "How does prosperity sometimes lead you to 'forget' God's past faithfulness, and what spiritual disciplines guard against this pattern?",
                "In what ways might modern Christians pursue the 'gods of the people' whose emptiness God has already demonstrated?"
            ]
        }
    },
    "6": {
        "9": {
            "analysis": "<strong>Ahimaaz begat Azariah, and Azariah begat Johanan</strong>—this genealogical link within the high priestly line connects two significant names. Ahimaaz (אֲחִימַעַץ 'my brother is counsel') served as high priest during David's reign, while Azariah (עֲזַרְיָה 'Yahweh has helped') became high priest under Solomon, serving in the temple Solomon built (v. 10).<br><br>The repetition of Azariah in this lineage is significant: at least five high priests bore this name (also called Uzziah), demonstrating how names commemorating Yahweh's help became foundational in Israel's worship leadership. Johanan (יוֹחָנָן 'Yahweh is gracious') continues the theophoric naming pattern, each generation embedding covenant theology into family identity.<br><br>This priestly succession bridges the tabernacle era (mobile sanctuary) and temple era (permanent sanctuary), showing God's faithfulness to the Aaronic priesthood promise despite changing worship contexts. The genealogy anticipates Christ as our great High Priest (Hebrews 4:14), whose priesthood supersedes Aaron's line.",
            "historical": "This genealogy traces the high priestly line from Aaron through Zadok to the First Temple period (970-586 BC). Azariah son of Ahimaaz likely served during Solomon's prosperous reign when the Jerusalem temple replaced the tabernacle at Gibeon. The Chronicler, writing to post-exilic priests reestablishing temple worship, emphasizes legitimate priestly descent—crucial for those challenged by Samaritans claiming equally valid priesthoods descended from northern Israel.",
            "questions": [
                "How do the theophoric names ('Yahweh has helped,' 'Yahweh is gracious') in this priestly line testify to experienced grace rather than empty tradition?",
                "What does this unbroken priestly succession teach about God's faithfulness to His covenant promises despite human unfaithfulness?"
            ]
        },
        "19": {
            "analysis": "<strong>The sons of Merari</strong> (בְּנֵי מְרָרִי)—Merari means 'bitter' or 'sad,' yet this Levitical clan served joyfully in God's sanctuary. <strong>Mahli</strong> (מַחְלִי 'mild' or 'sick') and <strong>Mushi</strong> (מוּשִׁי 'yielding') bear names suggesting weakness, yet they bore the heavy tabernacle framework (Numbers 4:29-33)—the boards, bars, pillars, and sockets that gave structure to God's dwelling place.<br><br><strong>These are the families of the Levites according to their fathers</strong> (אֵלֶּה מִשְׁפְּחוֹת הַלֵּוִי לַאֲבוֹתֵיהֶם)—the phrase emphasizes patrilineal inheritance of sacred duty. Unlike the priesthood (restricted to Aaron's line), all Levi's descendants shared sanctuary service, with Merari's descendants carrying the foundational structural elements. God's choice of the 'bitter' clan for foundational work reveals His pattern: using the weak things to shame the strong (1 Corinthians 1:27).<br><br>The Merarites' service—hauling heavy beams and sockets through wilderness—was unglamorous compared to Kohathite care of sacred vessels or Gershonite handling of fine curtains, yet without their burden-bearing, the tabernacle couldn't stand. This foreshadows Christ's foundation-laying (1 Corinthians 3:11) and the Church's need for unsung servants.",
            "historical": "Merari's clan received specific assignments during the wilderness wanderings (1400s BC) and continued these traditional roles through the temple period. The Chronicler, writing to post-exilic Levites (450-400 BC) reestablishing temple service with limited resources and workforce, emphasizes that even the 'bitter' and 'mild' clans had indispensable roles. This countered any hierarchical thinking that devalued support roles compared to more visible priestly functions.",
            "questions": [
                "How does God's choice of the 'bitter' (Merari) clan for foundational structural work challenge your assumptions about which roles in God's kingdom are most important?",
                "What 'heavy framework' responsibilities in your church are unglamorous but essential, and how can you honor those who bear these burdens?"
            ]
        },
        "29": {
            "analysis": "<strong>The sons of Merari</strong>—this genealogical expansion traces Merari's descendants through multiple generations. <strong>Mahli, Libni his son, Shimei his son, Uzza his son</strong>—each name carries meaning: Libni (לִבְנִי 'white' or 'distinguished'), Shimei (שִׁמְעִי 'famous' or 'renowned'), Uzza (עֻזָּא 'strength'). The progression from Mahli ('mild/sick') through Libni ('distinguished') to Uzza ('strength') suggests a theological narrative: from weakness to honor to strength through God's grace.<br><br>This Merarite line served as Levitical musicians in David's reorganized temple worship (vv. 31-47). Those whose ancestors hauled heavy tabernacle framework now lifted voices and instruments in praise—from burden-bearing to worship-leading. The transformation illustrates how faithful service in 'lesser' roles prepares for greater kingdom assignments (Matthew 25:21).<br><br>The genealogical precision demonstrates the Chronicler's emphasis on legitimate, traceable lineage for temple servants. In post-exilic restoration, when many couldn't prove their ancestry (Ezra 2:59-63), such detailed genealogies validated returning Levites' right to resume sacred duties.",
            "historical": "This genealogy spans from Moses's era (Exodus-Numbers accounts of Merari's duties) through David's temple preparations (1000 BC) to the Chronicler's post-exilic audience (450-400 BC). David transformed Levitical roles from primarily transporters to musicians, singers, and gatekeepers—a liturgical revolution that elevated all Levitical clans. The Merarites, once heavy laborers, now include Ethan the Ezrahite (v. 44), a wisdom sage credited with Psalm 89.",
            "questions": [
                "How does the name progression from 'mild' to 'distinguished' to 'strength' encourage you about God's transformative work through generations of faithfulness?",
                "What 'burden-bearing' season in your life has God transformed into a 'worship-leading' season?"
            ]
        },
        "39": {
            "analysis": "<strong>And his brother Asaph</strong>—this introduces Asaph (אָסָף 'gatherer' or 'collector'), one of David's three chief musicians and author of 12 canonical Psalms (50, 73-83). The term <strong>brother</strong> (אָח) indicates fellow Levite, not biological sibling. Asaph <strong>stood on his right hand</strong> (הָעֹמֵד עַל־יְמִינוֹ)—the position of honor—alongside Heman the Kohathite during temple worship, with Ethan/Jeduthun the Merarite on the left (v. 44).<br><br>Asaph's genealogy traces through <strong>Berachiah</strong> (בְּרֶכְיָהוּ 'Yahweh blesses') and <strong>Shimea</strong> (שִׁמְעָא 'something heard'), names emphasizing blessing and proclamation—perfect for a worship leader whose Psalms would be 'heard' and 'bless' Israel for millennia. Asaph's prophetic gift (2 Chronicles 29:30 calls his words 'prophecy') made him not merely a musician but a Spirit-anointed messenger through song.<br><br>The tri-clan representation (Kohath-Heman, Gershon-Asaph, Merari-Ethan) in temple music demonstrated that all Levitical branches equally participate in praise, breaking down clan rivalry. This anticipates the New Testament truth that all believers—regardless of tribe or nation—are priests offering spiritual sacrifices of praise (1 Peter 2:9; Hebrews 13:15).",
            "historical": "David appointed Asaph around 1000 BC as chief musician when the ark was brought to Jerusalem. Asaph's descendants maintained this role through the First Temple era (970-586 BC), during Hezekiah's reforms (2 Chronicles 29:30), and returned from exile (Ezra 2:41). The Chronicler highlights Asaph to encourage post-exilic worship renewal, showing that authentic praise requires both Spirit-empowered gifting and legitimate genealogical standing.",
            "questions": [
                "How does Asaph's role as both 'gatherer' (his name) and prophet-musician challenge modern divisions between artistic gift and spiritual authority?",
                "What does the tri-clan representation in temple worship teach about unity-in-diversity within Christ's body?"
            ]
        },
        "49": {
            "analysis": "<strong>But Aaron and his sons</strong> (וְאַהֲרֹן וּבָנָיו)—this emphatic contrast distinguishes the exclusive priestly duties from broader Levitical service. Only Aaron's descendants could <strong>offered upon the altar of the burnt offering</strong> (עֹלָה olah, the sacrifice wholly consumed by fire) and <strong>the altar of incense</strong> (קְטֹרֶת qetoret, the fragrant smoke rising before the Holy of Holies). These two altars represented complete dedication to God (burnt offering) and intercessory prayer (incense).<br><br><strong>Appointed for all the work of the place most holy</strong> (קֹדֶשׁ הַקֳּדָשִׁים qodesh haqodashim)—only Aaron's line could enter the Holy of Holies on Yom Kippur. The phrase <strong>to make an atonement</strong> (לְכַפֵּר lechapper) uses the Hebrew root meaning 'to cover'—priestly ministry covered Israel's sin through blood sacrifice, prefiguring Christ who 'covers' definitively through His own blood (Romans 3:25; Hebrews 9:11-14).<br><br><strong>According to all that Moses the servant of God had commanded</strong>—this appeal to Mosaic authority validates post-exilic priestly practice against Samaritan competing claims. The Aaronic priesthood derives authority not from human appointment but from divine command through Moses (Exodus 28-29; Leviticus 8-9). Christ's priesthood similarly rests on God's oath, not Levitical law (Hebrews 7:20-22).",
            "historical": "Written after exile when the restored community faced questions about proper worship procedures, this verse reasserts Aaronic exclusivity in sacrificial duties. During the Second Temple period (515 BC-AD 70), Zadokite priests (descended from Aaron through Zadok) maintained these functions until Christ's death made the temple veil-tearing (Matthew 27:51) obsolete the old system. The Chronicler emphasizes Mosaic authorization to counter syncretistic worship proposals from neighboring peoples.",
            "questions": [
                "How do the two altars (burnt offering and incense) picture the twin aspects of Christian life: complete consecration and constant prayer?",
                "Since Christ fulfilled Aaron's priestly role definitively, how does Hebrews 10:19-22's invitation to boldly approach God transform your prayer life?"
            ]
        },
        "59": {
            "analysis": "<strong>And Ashan with her suburbs, and Beth-shemesh with her suburbs</strong>—this verse lists Levitical cities assigned to Aaron's descendants in Judah's and Simeon's territories. The Hebrew <strong>מִגְרָשֶׁיהָ</strong> (migrasheiha, 'suburbs') technically means 'pasture lands' or 'open spaces'—grazing fields extending 2,000 cubits around each city (Numbers 35:4-5), providing agricultural support for non-farming priestly families.<br><br><strong>Ashan</strong> (עָשָׁן 'smoke') appears in Joshua 15:42 as a Judahite city given to Simeon (Joshua 19:7), then designated for Levites. <strong>Beth-shemesh</strong> (בֵּית־שֶׁמֶשׁ 'house of the sun') was a strategic border city with Philistia, famous as the terminus of the ark's return journey after Philistine captivity (1 Samuel 6). The priestly presence in border cities served dual purposes: worship leadership and covenant witness to neighboring nations.<br><br>The Levitical city system (48 cities total) geographically distributed spiritual leadership throughout Israel, preventing priestly isolation in Jerusalem and ensuring Torah teaching reached all tribes. This decentralized model anticipates the New Testament pattern of elders/pastors in every city (Titus 1:5), making spiritual oversight accessible rather than centralized.",
            "historical": "The Levitical city system originated in Joshua's conquest (c. 1400 BC, Joshua 21) but required continual renegotiation as tribal boundaries shifted. By the Chronicler's time (450-400 BC), most northern Levitical cities were lost to Assyrian conquest; this genealogical record preserved the ideal distribution and encouraged restoration where possible. Beth-shemesh's excavation shows Israelite occupation from Late Bronze Age through Iron Age II, confirming its long-standing importance.",
            "questions": [
                "How does the Levitical city system—distributing spiritual leaders throughout the land rather than centralizing them—challenge or affirm your church's approach to ministry?",
                "What significance does priestly presence in border cities like Beth-shemesh have for Christian witness in culturally contested spaces?"
            ]
        },
        "69": {
            "analysis": "<strong>Aijalon with her suburbs, and Gath-rimmon with her suburbs</strong>—two more Levitical cities allocated to Kohathite families in Dan's and Ephraim's territories. <strong>Aijalon</strong> (אַיָּלוֹן 'place of deer') sits in the valley where Joshua commanded the moon to stand still during battle (Joshua 10:12), making it a site commemorating Yahweh's miraculous intervention. A Levitical city at this location meant regular liturgical remembrance of God's power in holy history.<br><br><strong>Gath-rimmon</strong> (גַּת־רִמּוֹן 'winepress of pomegranate') appears in both Dan's (Joshua 19:45) and Manasseh's (Joshua 21:25) allotments, suggesting either two cities with identical names or textual confusion in transmission—a reminder that Scripture preserves authentic ancient records with their original textual challenges rather than sanitized versions. The Levites received 'winepress' cities, symbolically appropriate for those who would tread out spiritual harvest and produce the wine of joy in worship (Psalm 104:15).<br><br>These brief listings—easy to skip in reading—actually map God's intentional geographic dispersion of worship leaders. By placing Levites in strategically located cities throughout all tribal territories, God ensured no Israelite lived far from Torah instruction and covenant worship. The pattern anticipates Jesus's commission to make disciples 'in Jerusalem, Judea, Samaria, and the ends of the earth' (Acts 1:8).",
            "historical": "Aijalon's valley remained strategically significant through Israel's history—site of battles under Joshua (1400 BC), Saul (1 Samuel 14:31), and later Philistine-Israelite conflicts. In the divided monarchy period (930-722 BC), Aijalon's location on the Benjamin-Dan border made it a contested frontier city. For the Chronicler's post-exilic audience, these northern Levitical cities were mostly lost, but the record preserved God's original intention for complete tribal coverage of spiritual leadership.",
            "questions": [
                "How does Levitical presence at sites of miraculous deliverance (like Aijalon) emphasize worship's role in remembering and retelling God's mighty acts?",
                "What does the strategic distribution of worship leaders teach about intentional church planting in underserved areas?"
            ]
        },
        "79": {
            "analysis": "<strong>Kedemoth also with her suburbs, and Mephaath with her suburbs</strong>—these Levitical cities in Reuben's trans-Jordanian territory supported Merarite Levites. <strong>Kedemoth</strong> (קְדֵמוֹת 'eastern places' or 'ancient places') appears in Moses's diplomatic message to Sihon requesting peaceful passage (Deuteronomy 2:26), making it historically significant as a contact point before Israel's conquest of the Amorite kingdoms. A Levitical city at Kedemoth meant priests lived where Israel first attempted peaceful coexistence before necessary warfare—a reminder that God's people seek peace before battle (Romans 12:18).<br><br><strong>Mephaath</strong> (מֵיפַעַת 'splendor' or 'height') was both a Levitical city and city of refuge (Joshua 21:37), combining worship and justice functions. Cities of refuge provided asylum for accidental killers until high priest's death atoned for bloodguilt (Numbers 35:25-28)—a powerful type of Christ, whose death provides permanent refuge from sin's death penalty (Hebrews 6:18). That Levites administered these cities shows the inseparability of worship and justice in God's design.<br><br>These trans-Jordanian Levitical cities fell to Assyria in 732 BC (2 Kings 15:29), fulfilling the warning of 1 Chronicles 5:25-26 about apostasy's consequences. The Chronicler records them nonetheless, preserving God's original perfect plan even when Israel's unfaithfulness disrupted its fulfillment.",
            "historical": "Kedemoth and Mephaath's location east of the Dead Sea in the Moabite plateau made them vulnerable to Moabite and Ammonite encroachment. The Mesha Stele (c. 840 BC) mentions Moab's King Mesha recapturing cities from Israel, possibly including these. By the Chronicler's time, these cities were long lost to foreign control, but their memorial in Scripture testifies to God's comprehensive care for spiritual leadership across all Israel's territories, even the vulnerable frontier regions.",
            "questions": [
                "How does Kedemoth's association with peace-seeking before warfare inform Christian ethics about when to fight and when to pursue peace?",
                "What does the combination of Levitical city and city of refuge in Mephaath teach about the church's dual calling to worship and justice?"
            ]
        }
    },
    "7": {
        "8": {
            "analysis": "<strong>The sons of Becher</strong>—this genealogy catalogs Benjamin's clan through Becher (בֶּכֶר 'young camel' or 'firstborn'). The eight sons listed—<strong>Zemira</strong> (זְמִירָה 'song'), <strong>Joash</strong> (יוֹעָשׁ 'Yahweh has given'), <strong>Eliezer</strong> (אֱלִיעֶזֶר 'God is help'), <strong>Elioenai</strong> (אֶלְיוֹעֵינַי 'to Yahweh are my eyes'), <strong>Omri</strong> (עָמְרִי 'sheaf' or 'pupil'), <strong>Jerimoth</strong> (יְרִימוֹת 'heights'), <strong>Abiah</strong> (אֲבִיָּה 'Yahweh is father'), and <strong>Anathoth</strong> (עֲנָתוֹת 'answers')—form a theological catechism in names, emphasizing Yahweh's provision, help, fatherhood, and attentive hearing.<br><br>The name <strong>Anathoth</strong> gains special significance as Jeremiah's hometown (Jeremiah 1:1), a Levitical city in Benjamin's territory. That Becher's descendant bore this name before the city's prominence shows God's providential preparation—centuries before Jeremiah, a Benjamite bore the name 'answers,' anticipating the prophet who would answer God's call in Israel's darkest hour. This genealogical 'easter egg' rewards careful readers with Christological connections (Jeremiah prefigured Christ's rejection by his hometown, Luke 4:24).<br><br><strong>All these are the sons of Becher</strong>—the summarizing formula emphasizes completeness. Benjamin's prominence (Paul's tribe, Romans 11:1; the temple sat in Benjamin's land) roots in extensive, blessed genealogy. Despite being Jacob's youngest and Rachel's last son, Benjamin became numerically and strategically significant through covenant multiplication (Genesis 49:27).",
            "historical": "Benjamin's tribe occupied the strategic hill country between Ephraim and Judah, including Jerusalem's northern suburbs. Though the smallest tribe (Judges 20-21 nearly destroyed them), Benjamin produced Israel's first king (Saul), joined Judah after the schism (930 BC), and maintained identity through exile. The Chronicler, emphasizing Judah-Benjamin continuity, shows post-exilic Jerusalem's population as legitimate heirs of pre-exilic Israel. Anathoth, mentioned in this genealogy, became a priestly city hosting Abiathar's descendants after Solomon's purge (1 Kings 2:26).",
            "questions": [
                "How do the theophoric names in Becher's genealogy ('Yahweh has given,' 'God is help') testify to faith formation through naming practices?",
                "What encouragement does Benjamin's recovery from near-extinction (Judges 21) to prominence offer regarding God's redemptive purposes for broken communities?"
            ]
        },
        "18": {
            "analysis": "<strong>And his sister Hammoleketh</strong> (הַמֹּלֶכֶת 'the queen' or 'the reigning one')—this rare feminine genealogical entry appears in Manasseh's tribal register. Most biblical genealogies trace patrilineal descent, but Hammoleketh's inclusion suggests she had inheritance rights (cf. Zelophehad's daughters, Numbers 27:1-11) or bore sons of special significance. Her name's meaning, 'the queen,' may indicate royal connections or simply high status within the clan.<br><br>She <strong>bare Ishod</strong> (אִישְׁהוֹד 'man of majesty'), <strong>Abiezer</strong> (אֲבִיעֶזֶר 'father of help'), and <strong>Mahalah</strong> (מַחְלָה 'disease' or 'weakness'). Abiezer's clan gained fame through Gideon, who came from Ophrah of the Abiezrites (Judges 6:11). Gideon, whose weakness God used to defeat Midian with 300 men, perfectly embodied his ancestor's name 'father of help'—divine strength perfected in human weakness (2 Corinthians 12:9).<br><br>The juxtaposition of names—Ishod ('majesty'), Abiezer ('help'), Mahalah ('weakness')—creates theological tension: majesty coexists with weakness when God provides help. This anticipates Paul's paradox: 'when I am weak, then I am strong' (2 Corinthians 12:10). That these sons trace through their mother rather than father breaks patriarchal convention, showing God's kingdom purposes transcend cultural gender norms.",
            "historical": "Manasseh's tribe split between west Jordan (this branch) and east Jordan territories. Hammoleketh's sons settled west of Jordan, likely in the hill country that later hosted Gideon's exploits against Midianite raiders (Judges 6-8, c. 1200 BC). For the Chronicler's post-exilic audience, Manasseh's tribal identity was fragmented—the eastern half had been exiled by Assyria (732 BC) and never returned, while western Manasseh merged with Ephraim's territory in the northern kingdom.",
            "questions": [
                "What does Hammoleketh's inclusion in this patrilineal genealogy teach about God's regard for women's roles in covenant history?",
                "How does Gideon's descent from Abiezer ('father of help') illustrate God's pattern of achieving mighty victories through weak, unlikely instruments?"
            ]
        },
        "28": {
            "analysis": "<strong>And their possessions and habitations were</strong> (וּמוֹשְׁבוֹתָם וּמוֹשְׁבֵיהֶם)—this territorial summary maps Ephraim's key settlements. <strong>Beth-el</strong> (בֵּית־אֵל 'house of God') heads the list, where Jacob dreamed of heaven's ladder (Genesis 28:19) and where Jeroboam later erected a golden calf (1 Kings 12:29), illustrating how holy places can become idolatrous shrines. The tension between Beth-el's sacred past and apostate future warns against presuming on location's holiness while abandoning covenant faithfulness.<br><br>The geographic sweep—<strong>eastward Naaran, westward Gezer</strong>—spans from Jordan Valley to coastal plain, showing Ephraim's extensive territory, the richest in northern Israel. <strong>Shechem also</strong> (שְׁכֶם) appears prominently, the first place Abraham built an altar in Canaan (Genesis 12:6-7), where Joshua renewed the covenant (Joshua 24), and later the northern kingdom's first capital (1 Kings 12:25). Shechem's recurring covenant significance makes its mention here more than geographic data—it's theological geography, sites where God revealed himself and Israel responded in worship.<br><br><strong>Unto Gaza</strong> (עַד־עַזָּה)—this southern extension seems anomalous since Gaza was Philistine territory. Some translations read 'Ayyah' instead, a northern city, resolving the geographic puzzle. But if Gaza is correct, it claims Ephraim's maximum territorial ambitions reached to the Philistine pentapolis, goals never fully realized due to incomplete conquest (Judges 1:19, 29).",
            "historical": "Ephraim dominated the northern kingdom after Solomon's death (930 BC), with Jeroboam I (an Ephraimite) establishing rival worship centers at Beth-el and Dan. The Chronicler, writing to post-exilic Judahites, presents Ephraim's original territorial blessing as contrast to their later apostasy and Assyrian conquest (722 BC). Many Ephraimites fled south to Judah during northern kingdom's collapse, and Josiah's reforms (640-609 BC) attempted to reclaim these cities for Yahweh worship (2 Chronicles 34:6-7).",
            "questions": [
                "How does Beth-el's transformation from 'house of God' to idolatrous shrine warn against relying on past spiritual experiences without present faithfulness?",
                "What do Ephraim's extensive but ultimately lost territories teach about the danger of material blessing without corresponding spiritual devotion?"
            ]
        },
        "38": {
            "analysis": "<strong>And the sons of Jether</strong>—this genealogical fragment lists <strong>Jephunneh</strong> (יְפֻנֶּה 'he will be turned'), <strong>Pispah</strong> (פִּסְפָּה 'expansion' or 'dispersion'), and <strong>Ara</strong> (אֲרָא 'wandering' or 'wayfaring'). These names appear in Asher's tribal register (v. 30-40), one of Scripture's least-developed tribal genealogies. Asher's relative obscurity in biblical narrative (rarely mentioned after Joshua's allocation) makes every detail significant.<br><br>The name <strong>Jephunneh</strong> notably appears as Caleb's father (Numbers 13:6), though that Jephunneh was a Kenizzite (Numbers 32:12) incorporated into Judah, not this Asherite Jephunneh. The name recurrence shows how names circulated across tribes—shared linguistic heritage even when family lines diverged. 'He will be turned' as a name suggests covenantal hope: God turns wanderers home, a theme especially poignant for northern tribes like Asher who largely vanished after Assyrian exile.<br><br><strong>Pispah</strong> ('expansion') and <strong>Ara</strong> ('wandering') create narrative tension: expansion versus wandering, settlement versus dispersion. Asher's allotment along the Phoenician coast provided prosperity through Mediterranean trade but also constant temptation to assimilate with Canaanite culture. These names reflect both blessing and danger inherent in their geographic position.",
            "historical": "Asher's coastal territory (from Mount Carmel to Phoenicia) made them economically prosperous through trade with Tyre and Sidon but spiritually vulnerable to Baalism. Jacob's blessing promised Asher 'royal dainties' (Genesis 49:20), fulfilled through agricultural abundance and maritime commerce. By the Chronicler's time, Asher's tribal identity had dissolved—most were absorbed into Assyrian deportations (722 BC) or assimilated into Phoenician culture. Anna the prophetess (Luke 2:36) represents a rare post-exilic Asherite maintaining tribal identity.",
            "questions": [
                "How do the names 'expansion' and 'wandering' in Asher's genealogy illustrate the tension between material blessing and spiritual rootedness?",
                "What does Asher's eventual disappearance as a distinct tribe warn about the long-term costs of cultural assimilation over covenant faithfulness?"
            ]
        }
    },
    "8": {
        "8": {
            "analysis": "<strong>And Shaharaim begat children in the country of Moab</strong>—this unusual notice records a Benjamite living and procreating in Moabite territory, Israel's enemy nation descended from Lot's incest (Genesis 19:37). The text states he begot children <strong>after he had sent them away</strong>—he divorced his wives <strong>Hushim</strong> (חֻשִׁים 'hasters') and <strong>Baara</strong> (בַּעֲרָא 'brutish one'), apparently after relocating to Moab, then married Moabite women and started a new family (vv. 9-10).<br><br>This morally complex scenario—divorce, foreign settlement, intermarriage with Moabites—gets recorded without editorial comment, simply preserved as historical fact. The Chronicler's audience would recognize the problematic pattern: intermarriage with Moabites violated Deuteronomy 23:3-6 (Moabites forbidden from assembly 'forever'), yet produced legitimate Benjamite lineage that returned post-exile. This mirrors Ruth's Moabite origin producing David's lineage—God's providence works through messy human situations that violate ideal covenant standards.<br><br>The name <strong>Shaharaim</strong> (שַׁחֲרַיִם 'double dawn' or 'two gates') may itself signal doubling/duplication, fitting someone who started a second family after abandoning his first. His story warns against geographic solutions to relational problems—fleeing to Moab didn't resolve issues that led to divorcing two wives; it simply relocated his dysfunction.",
            "historical": "Benjamin's location bordering Moab across the Dead Sea facilitated trans-border movement, especially during periods of Moabite strength (e.g., Eglon's conquest in Judges 3). Shaharaim's Moabite sojourn likely occurred during the judges period or early monarchy. The Chronicler includes this irregular genealogy because Shaharaim's Moabite descendants returned from Babylonian exile as legitimate Benjamites, proving tribal identity survived even foreign intermarriage. This encouraged post-exilic Jews facing identity questions after 70 years in Babylon.",
            "questions": [
                "How does God's inclusion of Shaharaim's irregular Moabite family in Benjamin's genealogy demonstrate redemptive providence working through messy human choices?",
                "What does this passage teach about the difference between God's ideal standards (no Moabite intermarriage) and His redemptive accommodation of flawed human history?"
            ]
        },
        "18": {
            "analysis": "<strong>Ishmerai also, and Jezliah, and Jobab, the sons of Elpaal</strong>—this genealogical snippet lists three Benjamite names in the Elpaal clan. <strong>Ishmerai</strong> (יִשְׁמְרַי 'Yahweh guards'), <strong>Jezliah</strong> (יִזְלִיאָה 'God will draw out'), and <strong>Jobab</strong> (יוֹבָב 'a desert') demonstrate typical Hebrew naming patterns: theophoric names incorporating Yahweh/El (first two) alongside common nouns (third).<br><br>These obscure names appear nowhere else in Scripture—no heroic deeds, prophetic words, or dramatic failures recorded. Yet their inclusion in Chronicles testifies to a profound theological truth: every covenant member matters to God's record-keeping, not just heroes and kings. The Holy Spirit inspired preservation of otherwise forgotten names, suggesting God's encyclopedic memory of His people (Malachi 3:16; Philippians 4:3) and anticipating the Lamb's Book of Life (Revelation 21:27).<br><br>The name <strong>Jobab</strong> ('desert') appears as both an Edomite king (Genesis 36:33) and these Benjamite clan members, showing name-sharing across ethnic boundaries. That 'desert' became a personal name may reflect circumstances of birth (born during wilderness wandering?) or character traits (austere, hardy). Scripture's willingness to memorialize even 'desert'-named minor figures shows God values all His image-bearers, not merely the illustrious.",
            "historical": "This genealogy belongs to Benjamin's families dwelling in Jerusalem after some period of displacement (v. 28 says 'these dwelt in Jerusalem'). The context suggests post-exilic resettlement (Nehemiah 11 lists Benjamites who settled Jerusalem), though the genealogy extends back to pre-exilic ancestors. The Chronicler's preservation of these names validated the tribal claims of returning exiles, confirming their legitimate descent from ancient Benjamite clans despite 70-year Babylonian interruption.",
            "questions": [
                "How does God's preservation of 'nobodies' like Ishmerai, Jezliah, and Jobab in Scripture encourage you about your own significance in His kingdom?",
                "What does the inclusion of seemingly unimportant genealogical details teach about God's comprehensive care for every member of His covenant community?"
            ]
        },
        "28": {
            "analysis": "<strong>These were heads of the fathers, by their generations, chief men</strong> (רָאשֵׁי אָבוֹת לְתֹלְדוֹתָם roshei avot letoldotam)—this summarizing formula designates clan patriarchs, literally 'heads of fathers' houses according to their generations.' The term <strong>chief men</strong> (רָאשִׁים rashim) indicates leadership status, those with authority to represent their extended families in tribal decision-making, military service, and judicial matters (Exodus 18:25; Deuteronomy 1:15).<br><br><strong>These dwelt in Jerusalem</strong> (בִּירוּשָׁלִַם יָשָׁבוּ)—Benjamin's strategic significance appears in their Jerusalem settlement. Though Jerusalem sat primarily in Benjamin's allotment, David's conquest made it a royal city transcending tribal boundaries. Benjamin's continued residence in Jerusalem through monarchy, exile, and restoration demonstrates covenant faithfulness despite political upheaval. When the northern tribes apostatized under Jeroboam (930 BC), Benjamin remained with Judah, maintaining access to legitimate temple worship.<br><br>This verse's function is administrative and theological: administratively, it marks the conclusion of several Benjamite genealogical lists; theologically, it validates post-exilic Jerusalem's population as legitimate heirs of pre-exilic Israel. The Chronicler assures returned exiles that their 'heads of fathers' houses' in rebuilt Jerusalem stand in direct succession to ancient tribal leadership, confirming covenant continuity despite Babylonian interruption.",
            "historical": "Jerusalem's population dynamics shifted dramatically through history. Originally a Jebusite city conquered by David (c. 1000 BC, 2 Samuel 5:6-9), it became capital of united Israel, then Judah alone after 930 BC. Babylonian destruction (586 BC) depopulated the city; Nehemiah's reforms (445 BC) repopulated it through voluntary settlement and lots (Nehemiah 11:1-2). The Chronicler, writing during this restoration period, emphasizes Benjamin's continuous Jerusalem presence, providing historical legitimacy for current residents' claims to ancestral land.",
            "questions": [
                "How does Benjamin's faithfulness in dwelling near Jerusalem and maintaining temple worship challenge believers to prioritize spiritual community over economic opportunity?",
                "What does the preservation of 'heads of fathers' houses' through exile teach about God's commitment to institutional continuity alongside personal salvation?"
            ]
        },
        "38": {
            "analysis": "<strong>And Azel had six sons</strong>—this detailed enumeration appears twice in Chronicles (here and 9:44), emphasizing King Saul's genealogy. <strong>Azel</strong> (אָצֵל 'noble' or 'set apart') descended from Jonathan through Merib-baal/Mephibosheth (v. 34), making these six sons Saul's great-great-great-grandsons. Their names—<strong>Azrikam</strong> (עַזְרִיקָם 'my help has risen'), <strong>Bocheru</strong> (בֹּכְרוּ 'firstborn'), <strong>Ishmael</strong> (יִשְׁמָעֵאל 'God hears'), <strong>Sheariah</strong> (שְׁעַרְיָה 'Yahweh has stormed'), <strong>Obadiah</strong> (עֹבַדְיָה 'servant of Yahweh'), and <strong>Hanan</strong> (חָנָן 'gracious')—blend theophoric piety with circumstantial naming.<br><br>The repetition <strong>All these were the sons of Azel</strong> creates a deliberate inclusio (bracketing device), emphasizing completeness. Why chronicle Saul's post-monarchic descendants so carefully? The Chronicler demonstrates that God's rejection of Saul's dynasty (1 Samuel 15:28) didn't mean extinction of his lineage—covenant mercy preserved Saul's descendants through Jonathan's line despite dynastic failure. This offered hope to post-exilic Israel: corporate judgment doesn't necessitate individual extinction; God preserves faithful remnants even from rejected systems.<br><br>That Jonathan's line survived while kingship passed to David illustrates grace's complexity: God judges institutions (Saulide monarchy ended) while preserving persons (Jonathan's descendants continued). The names testify to genuine Yahwistic faith ('servant of Yahweh,' 'my help has risen') among Saul's descendants, showing personal piety can flourish even in dynasties under divine judgment.",
            "historical": "Saul's dynasty ended violently on Mount Gilboa (1 Samuel 31, c. 1010 BC) when he and three sons died fighting Philistines. Only Ish-bosheth and Jonathan's son Mephibosheth survived. Ish-bosheth's assassination (2 Samuel 4) and Mephibosheth's childless status initially seemed to end Saul's line, but 2 Samuel 21:8 mentions Merab's sons, and this Chronicles passage shows Jonathan's descendants continued through post-exilic period. Their survival testifies to David's covenant with Jonathan (1 Samuel 20:15-16, 42) outlasting the royal rivalry.",
            "questions": [
                "How does God's preservation of Saul's descendants through Jonathan comfort those whose families have experienced corporate discipline or institutional failure?",
                "What does the theophoric piety in Azel's sons' names teach about maintaining personal faithfulness even when family legacy includes divine judgment?"
            ]
        }
    },
    "9": {
        "8": {
            "analysis": "<strong>And Ibneiah the son of Jeroham, and Elah the son of Uzzi</strong>—this verse lists post-exilic Benjamite residents of Jerusalem with extended genealogies. <strong>Ibneiah</strong> (יִבְנְיָה 'Yahweh builds'), <strong>Jeroham</strong> (יְרֹחָם 'cherished' or 'loved'), <strong>Elah</strong> (אֵלָה 'oak' or 'terebinth'), <strong>Uzzi</strong> (עֻזִּי 'my strength'), <strong>Michri</strong> (מִכְרִי 'price'), <strong>Meshullam</strong> (מְשֻׁלָּם 'recompensed'), <strong>Shephathiah</strong> (שְׁפַטְיָה 'Yahweh judges'), <strong>Reuel</strong> (רְעוּאֵל 'friend of God'), and <strong>Ibnijah</strong> (יִבְנִיָּה 'Yahweh builds')—the genealogical depth (seven generations: Ibneiah←Jeroham←...←Ibnijah) validates these families' legitimate Benjamite ancestry despite 70 years in Babylon.<br><br>The repetition of <strong>Yahweh builds</strong> (יִבְנְיָה) at both ends of this genealogy creates a theological frame: Yahweh who built ancient Benjamin's families now rebuilds them post-exile. The name <strong>Reuel</strong> ('friend of God') notably appears as Moses's father-in-law's name (Exodus 2:18), suggesting either name recycling or Midianite integration into Israel—a reminder that ethnic Israel included grafted-in strangers who became covenant friends of God, anticipating Gentile inclusion in Christ's body (Ephesians 2:19).<br><br>The meticulous preservation of seven-generation genealogies for returning families demonstrates the post-exilic community's concern with legitimacy. Unlike modern individualism, ancient identity was corporate and genealogical—you were your lineage. These names aren't filler; they're validation that Jerusalem's post-exilic population were authentic Israel, not mere squatters in ancestral land.",
            "historical": "Chapter 9 lists residents of Jerusalem after Babylonian exile (538+ BC), paralleling Nehemiah 11's register. Babylonian policy mixed deportees from various nations, threatening Jewish ethnic-religious identity. Returning exiles faced challenges from Samaritans and others claiming equal right to the land. These genealogies proved the returnees' legitimate descent from pre-exilic tribal families, crucial for land ownership, temple service, and community leadership. Archaeological evidence shows Jerusalem's post-exilic population remained small (perhaps 1,500 initially) until Nehemiah's repopulation efforts (Nehemiah 11:1-2).",
            "questions": [
                "How does the name 'Yahweh builds' bracketing this genealogy encourage Christians facing the 'rebuilding' phase after spiritual devastation or church decline?",
                "What does the seven-generation genealogical preservation teach about the importance of knowing your spiritual heritage and faith legacy?"
            ]
        },
        "18": {
            "analysis": "<strong>Who hitherto waited in the king's gate eastward</strong>—this identifies Levitical gatekeepers' specific post at the <strong>king's gate</strong> (שַׁעַר־הַמֶּלֶךְ sha'ar hammelekh), the eastern entrance to the temple mount. In ancient Near Eastern culture, gate-keepers held strategic security roles, controlling access to sacred/royal precincts, collecting revenues, and serving as information hubs. The phrase <strong>hitherto</strong> (עַד־הֵנָּה ad-hennah, 'until now') suggests continuity from pre-exilic practice: post-exilic gatekeepers maintained the same posts their ancestors held before Babylonian destruction.<br><br><strong>They were porters in the companies of the children of Levi</strong> (שֹׁעֲרִים לְמַחֲנוֹת בְּנֵי־לֵוִי sho'arim lemachanot benei-Levi)—the term <strong>companies</strong> (מַחֲנוֹת machanot, literally 'camps') recalls wilderness wanderings when Levites camped around the tabernacle in military formation (Numbers 1-3). The language deliberately archaizes temple service, connecting Second Temple ritual to Mosaic origins—the post-exilic community isn't innovating but restoring authentic ancient practice.<br><br>The <strong>eastern</strong> gate held special significance: it faced the rising sun, the direction from which God's glory entered Solomon's temple (Ezekiel 43:1-5) and from which Ezekiel prophesied God's glory would return (Ezekiel 43:4). Gatekeepers at this portal literally stood watch for God's return, a posture of eschatological expectation. Symbolically, they prefigure Christians 'watching and waiting' for Christ's return from the east (Matthew 24:27, 42).",
            "historical": "The gatekeepers' role developed from tabernacle guards (Numbers 3:38) through Davidic reorganization (1 Chronicles 26) to Second Temple service (Ezra 2:42; Nehemiah 11:19). The 'king's gate' (likely the eastern/Golden Gate) served as primary access point to the temple mount's royal sector. After Babylonian destruction (586 BC), this gate's restoration symbolized renewed divine-human encounter. Ezekiel's vision of the permanently shut eastern gate (Ezekiel 44:1-2) may refer to the outer wall's gate, not this inner temple court gate, or represent eschatological reality awaiting Messiah's return.",
            "questions": [
                "How does the gatekeepers' 'watching' posture at the eastern gate inform Christian vigilance for Christ's return from the east?",
                "What does the continuity of gatekeeping posts 'hitherto' teach about the importance of maintaining faithful service even through catastrophic interruptions like exile?"
            ]
        },
        "28": {
            "analysis": "<strong>And certain of them had the charge of the ministering vessels</strong> (וּמֵהֶם עַל־כְּלֵי הָעֲבוֹדָה)—this describes a specialized Levitical role: inventory control of sacred utensils used in temple ritual. The Hebrew <strong>charge</strong> (עַל al, 'over' or 'upon') indicates assigned responsibility and accountability. These weren't merely storage clerks but liturgical stewards ensuring ritual purity and proper usage of consecrated objects—bowls, basins, knives, censers, etc., each with specific halakhic requirements.<br><br><strong>That they should bring them in and out by tale</strong> (כִּי־בְמִסְפָּר יְבִיאוּם וּבְמִסְפָּר יוֹצִיאוּם)—the phrase <strong>by tale</strong> (בְמִסְפָּר bemispar, 'by number') means they counted vessels in and out, like library checkout systems. This accountability prevented loss, theft, or unauthorized use of holy objects. The meticulous care reflects Uzzah's death for touching the ark improperly (2 Samuel 6:6-7) and Nadab/Abihu's destruction for unauthorized fire (Leviticus 10:1-2)—holy things require holy handling.<br><br>This mundane administrative detail—counting dishes—illustrates the sanctification of ordinary tasks when done for God's house. The New Testament parallel appears in Acts 6:1-6, where deacons served tables so apostles could focus on Word and prayer; both roles were vital, requiring Spirit-filled servants. The principle: there are no 'mere' tasks in God's service, only consecrated or profaned ones.",
            "historical": "Solomon's temple contained extensive precious metalwork: golden lampstands, tables, bowls, censers, etc. (1 Kings 7:48-50). Babylonian looting (586 BC) took most treasures (2 Kings 25:13-17), but returnees brought back some (Ezra 1:7-11). The Second Temple initially lacked much of the First Temple's grandeur, making careful stewardship of existing vessels crucial. This verse's emphasis on accountability reflects post-exilic economic scarcity—they couldn't afford to lose even one sacred utensil through carelessness.",
            "questions": [
                "How does the 'by tale' accountability system for temple vessels challenge modern casualness about sacred spaces, objects, and responsibilities?",
                "What does the dignifying of 'counting dishes' as Spirit-empowered Levitical service teach about the sanctification of mundane church administrative work?"
            ]
        }
    }
}

def main():
    """Add verse-specific commentary to 1 Chronicles."""

    # Path to the 1 Chronicles commentary file
    file_path = Path(__file__).parent.parent / 'kjvstudy_org' / 'data' / 'verse_commentary' / '1_chronicles.json'

    # Load existing data
    print(f"Loading {file_path}...")
    with open(file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    # Update with new commentary
    verses_added = 0
    for chapter, verses in COMMENTARY.items():
        if chapter not in data['commentary']:
            data['commentary'][chapter] = {}

        for verse, content in verses.items():
            data['commentary'][chapter][verse] = content
            verses_added += 1
            print(f"  Updated 1 Chronicles {chapter}:{verse}")

    # Save updated data
    print(f"\nSaving updated file...")
    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

    print(f"\n✓ Successfully updated {verses_added} verses in 1 Chronicles")
    print(f"  File: {file_path}")

    # Summary
    print("\nVerses updated:")
    for chapter in sorted(COMMENTARY.keys(), key=int):
        verse_list = ', '.join(sorted(COMMENTARY[chapter].keys(), key=int))
        print(f"  Chapter {chapter}: verses {verse_list}")

if __name__ == '__main__':
    main()
