#!/usr/bin/env python3
"""
Script to add comprehensive commentary for 10 specific verses to per-book commentary files
Daniel 4:5, Psalms 6:9, Luke 23:29, Ezekiel 40:33, Job 18:14,
Deuteronomy 33:25, John 20:7, John 13:18, Psalms 109:20, Numbers 33:1
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from kjvstudy_org.utils.commentary_loader import merge_commentary_entries

# Define the commentary data
commentaries = {
    "Daniel": {
        "4": {
            "5": {
                "analysis": "<strong>I saw a dream which made me afraid, and the thoughts upon my bed and the visions of my head troubled me.</strong> This verse introduces Nebuchadnezzar's second prophetic dream, a divine communication that profoundly disturbed the mighty Babylonian king. The Hebrew word for \"afraid\" (<em>dechal</em>, דְּחַל) in Aramaic (Daniel 2-7 is written in Aramaic) conveys intense fear and terror, while \"troubled\" (<em>behal</em>, בְּהַל) suggests mental confusion and alarm.<br><br>The phrase \"thoughts upon my bed and the visions of my head\" employs Hebrew parallelism to emphasize the comprehensive nature of this divine revelation—both the rational mind and the imaginative faculties were engaged. Unlike false dreams or psychological phenomena, God-given dreams possess a distinctive quality that unsettles human pride and self-sufficiency. Nebuchadnezzar, despite his absolute power and previous encounter with divine revelation (chapter 2), finds himself helpless before God's supernatural communication.<br><br>This verse demonstrates a theological principle: God sovereignly communicates with both believers and unbelievers to accomplish His purposes. The king's fear reflects the appropriate human response to divine holiness and judgment. The dream's troubling nature serves as divine preparation for the humbling message that follows—Nebuchadnezzar will be stripped of power and reason until he acknowledges that \"the most High ruleth in the kingdom of men\" (Daniel 4:25). God's revelation often disturbs before it instructs, breaking through human pride to prepare hearts for truth.",
                "historical": "This episode occurred during Nebuchadnezzar's reign over the Neo-Babylonian Empire (605-562 BCE), likely in the latter part of his rule when Babylon stood at its zenith of power and architectural splendor. The Hanging Gardens, one of the Seven Wonders of the Ancient World, exemplified Babylonian magnificence. Archaeological evidence confirms Nebuchadnezzar's extensive building projects documented in cuneiform inscriptions.<br><br>Ancient Near Eastern kings regularly consulted dreams as divine communications, employing professional dream interpreters and maintaining dream books. However, Nebuchadnezzar's dream defied conventional interpretation, requiring divine insight. The Babylonian worldview recognized multiple deities controlling various spheres, making the Hebrew monotheistic claim that \"the most High ruleth\" revolutionary and threatening to imperial ideology.<br><br>The literary structure of Daniel 4 is unique—written as a royal proclamation from Nebuchadnezzar himself, making it a testimony of conversion and acknowledgment of Yahweh's supremacy. This historical narrative provided encouragement to Jewish exiles that their God remained sovereign over even the mightiest earthly kingdoms. The chapter's Aramaic composition (the lingua franca of international diplomacy) suggests it was intended for broad distribution throughout the empire, proclaiming God's supremacy to pagan nations.",
                "questions": [
                    "How does God use disturbing circumstances or revelations in our lives to break through pride and self-sufficiency?",
                    "What does Nebuchadnezzar's fear before God's revelation teach us about appropriate responses to divine truth?",
                    "How does this passage demonstrate God's sovereignty over human kingdoms and rulers, and what implications does this have for our political engagement?",
                    "In what ways does God communicate truth to those who don't yet know Him, and how should this shape our evangelistic approach?",
                    "How can we cultivate sensitivity to God's voice while discerning between divine communication and mere psychological phenomena?"
                ]
            }
        }
    },
    "Psalms": {
        "6": {
            "9": {
                "analysis": "<strong>The LORD hath heard my supplication; the LORD will receive my prayer.</strong> This triumphant declaration marks the dramatic turning point in Psalm 6, shifting from desperate lament to confident assurance. The Hebrew verb for \"heard\" (<em>shama</em>, שָׁמַע) means more than auditory perception—it implies attentive response and action. God doesn't merely hear; He acts on behalf of His people. The parallel structure emphasizes certainty: \"hath heard\" (perfect tense, completed action) and \"will receive\" (imperfect, ongoing reality).<br><br>The word \"supplication\" (<em>techinnah</em>, תְּחִנָּה) denotes earnest entreaty from a position of need and dependence, while \"prayer\" (<em>tefillah</em>, תְּפִלָּה) encompasses comprehensive communion with God. The double use of \"the LORD\" (Yahweh) emphasizes covenant relationship—this isn't a distant deity but Israel's faithful covenant God who binds Himself to hear His people. David's confidence doesn't rest on prayer's eloquence or intensity but on God's character and promises.<br><br>This verse illustrates a pattern throughout Scripture: faithful lament leads to renewed trust. The psalmist doesn't deny pain or pretend circumstances have changed, but affirms God's attentiveness despite apparent silence. This confidence becomes the foundation for the following verses' bold declaration to enemies. True faith doesn't eliminate struggle but transforms it through the certainty of God's hearing ear and responding heart.",
                "historical": "Psalm 6 is the first of seven \"Penitential Psalms\" traditionally used in Christian liturgy for confession and repentance. The superscription attributes it to David, likely composed during a period of severe physical illness and enemy opposition—possibly during Absalom's rebellion or another crisis when David faced both bodily affliction and political threat. Ancient Near Eastern culture viewed illness as potential divine judgment, making David's situation both physically and spiritually desperate.<br><br>The psalm's structure reflects ancient Hebrew lament patterns: complaint (vv. 1-7), shift to confidence (vv. 8-10), and implicit praise. This literary form provided a template for honest prayer that doesn't deny pain while ultimately affirming God's faithfulness. Jewish tradition associates this psalm with prayer during sickness, and early Christians used it in end-of-life prayers and funerals, trusting God's deliverance from death's power.<br><br>The historical context of Israel's temple worship included professional musicians and singers who led corporate worship using psalms like this. Individual lament psalms became community resources, allowing future generations facing similar trials to voice their pain and faith using David's words. This communal dimension explains how deeply personal psalms function as Scripture for all believers—David's experience becomes a pattern for understanding God's character and faithful response to human suffering.",
                "questions": [
                    "How can we cultivate the kind of confidence in prayer that moves from desperate lament to certain assurance of God's hearing?",
                    "What does this verse teach about the relationship between honest lament and faith-filled confidence?",
                    "How should the certainty that God hears our prayers affect how we pray when circumstances don't immediately change?",
                    "What role does understanding God's covenant faithfulness play in maintaining confidence during prolonged suffering?",
                    "How can we help others move from doubt about God's attentiveness to confidence in His hearing, without minimizing their pain?"
                ]
            }
        },
        "109": {
            "20": {
                "analysis": "<strong>Let this be the reward of mine adversaries from the LORD, and of them that speak evil against my soul.</strong> This verse concludes the imprecatory section of Psalm 109, summarizing David's appeal for divine justice against false accusers and malicious enemies. The word \"reward\" (<em>pe'ullah</em>, פְּעֻלָּה) refers to recompense or wages—what one deserves for their actions. David isn't seeking personal vengeance but divine justice, appealing to \"the LORD\" (Yahweh) as the righteous judge who repays according to deeds.<br><br>The phrase \"speak evil against my soul\" (<em>nefesh</em>, נֶפֶשׁ) indicates attacks aimed at David's very life and being—not mere criticism but malicious slander intended to destroy. The imprecatory psalms (prayers for judgment) trouble modern readers but reflect several biblical realities: (1) God's righteousness demands justice for evil; (2) victims may appeal to God rather than taking personal revenge; (3) these prayers express holy hatred of sin while leaving judgment to God; (4) they anticipate the final judgment when all wrongs will be righted.<br><br>Theologically, this psalm foreshadows Christ's experience of betrayal by Judas (John 13:18; Acts 1:20). Jesus endured false accusation and evil speech, yet responded not with cursing but with forgiveness (Luke 23:34). This contrast illuminates the gospel: Christ bore the curse we deserved (Galatians 3:13), satisfying divine justice while extending mercy to enemies. Believers now pray for enemies' conversion rather than destruction, knowing Christ absorbed God's wrath against sin.",
                "historical": "Psalm 109 is attributed to David and likely originated during one of his many conflicts with enemies who used slander and false testimony as weapons. Ancient Near Eastern legal systems relied heavily on oral testimony without modern forensic evidence, making false accusation particularly dangerous and destructive. A powerful accuser could orchestrate someone's execution, property confiscation, or social ostracism through coordinated false witness.<br><br>The psalm's imprecatory language reflects ancient Near Eastern treaty curses and covenant lawsuit forms. When covenant partners violated agreements, curses specified in the treaty would be invoked. Israel's covenant with Yahweh included blessings for obedience and curses for rebellion (Deuteronomy 27-28). David's appeal for curses on covenant-breakers follows this treaty pattern, asking God to enforce covenant stipulations against those who violated justice and truth.<br><br>Early Christian interpretation saw prophetic fulfillment in Judas Iscariot's betrayal of Jesus. Acts 1:16-20 explicitly applies verses from Psalm 109 to Judas, demonstrating apostolic understanding of the psalm's messianic dimensions. Jewish liturgical tradition includes this psalm among prayers for deliverance from persecution, while Christian use has been cautious, emphasizing Christ's transformation of curse into blessing through the cross. The historical evolution of interpretation shows increasing recognition that Christ absorbed these curses, enabling believers to pray for enemies' salvation rather than destruction.",
                "questions": [
                    "How do we balance desire for justice with Christ's command to love enemies and pray for persecutors?",
                    "What does David's appeal to God rather than personal vengeance teach about handling unjust treatment?",
                    "How does understanding Christ's absorption of divine curse change how we read and apply imprecatory psalms?",
                    "In what situations is it appropriate to pray for divine justice and judgment rather than immediately extending forgiveness?",
                    "How can we cultivate holy hatred of evil without becoming bitter or vengeful toward evildoers?"
                ]
            }
        }
    },
    "Luke": {
        "23": {
            "29": {
                "analysis": "<strong>For, behold, the days are coming, in the which they shall say, Blessed are the barren, and the wombs that never bare, and the paps which never gave suck.</strong> Jesus speaks these prophetic words to the \"daughters of Jerusalem\" as He carries the cross to Golgotha. The Greek particle \"<em>idou</em>\" (ἰδού, \"behold\") commands urgent attention to this solemn prophecy. Jesus reverses conventional Jewish values where barrenness was considered divine curse and childbearing was blessing (Genesis 30:23; 1 Samuel 1:6-7; Luke 1:25).<br><br>This shocking statement prophesies the catastrophic judgment coming upon Jerusalem in 70 AD when Roman legions would destroy the city, slaughter inhabitants, and enslave survivors. During sieges, mothers and children suffered horrifically—starvation drove some to unthinkable acts (see Josephus's accounts of the Jerusalem siege). Jesus warns that suffering will be so severe that childlessness will seem preferable to watching children starve or be killed. The threefold description (barren, never bore, never nursed) emphasizes totality.<br><br>Theologically, this verse demonstrates Jesus's prophetic knowledge and His grief over Jerusalem's rejection of the Messiah. Even while suffering crucifixion, Jesus mourns the judgment falling on the city that rejected Him (cf. Luke 19:41-44). The passage also illustrates the principle that rejecting God's salvation brings devastating consequences. Jerusalem's destruction serves as historical warning of final judgment when those who reject Christ will face eternal consequences far worse than any temporal suffering.",
                "historical": "This prophetic word was fulfilled forty years later during the Roman siege and destruction of Jerusalem in 70 AD, led by Titus. The Jewish historian Josephus provides detailed eyewitness accounts in <em>The Jewish War</em> of the horrific suffering during the five-month siege. Over one million Jews died, and the city was systematically destroyed, including the magnificent temple that had stood since 515 BCE (rebuilt by Herod the Great starting in 20 BCE).<br><br>The historical context of Jesus's walk to Golgotha involved crowds of Jerusalem women who customarily mourned condemned criminals—a charitable act in Jewish culture. However, Jesus redirects their mourning from Himself to their own coming judgment. The prophecy's fulfillment validated Jesus's prophetic authority and warned subsequent generations about the consequences of rejecting God's Messiah. Early Christians, remembering Jesus's warnings, fled Jerusalem before the final siege when they saw Roman armies approaching (as recorded by Eusebius).<br><br>Archaeological excavations in Jerusalem have uncovered evidence of the 70 AD destruction: burned buildings, Roman military equipment, and skeletal remains showing signs of starvation and violence. The Western Wall (Wailing Wall) remains as a visible reminder of the temple's destruction. This historical catastrophe fundamentally changed Judaism, eliminating the temple-based sacrificial system and accelerating development of rabbinic Judaism centered on Torah study and synagogue worship. For Christians, Jerusalem's fall demonstrated that God's judgment prophecies will be literally fulfilled.",
                "questions": [
                    "How should we respond when we recognize God's judgment approaching individuals, institutions, or nations that persist in rejecting Christ?",
                    "What does Jesus's concern for Jerusalem even while suffering crucifixion teach us about how to view and pray for those who oppose the gospel?",
                    "How can we effectively warn people about the eternal consequences of rejecting Christ without seeming judgmental or harsh?",
                    "In what ways does the historical destruction of Jerusalem serve as a warning about final judgment for those who reject Jesus?",
                    "How should the certainty of fulfilled prophecy strengthen our confidence in unfulfilled prophecies about Christ's return and final judgment?"
                ]
            }
        }
    },
    "Ezekiel": {
        "40": {
            "33": {
                "analysis": "<strong>And the little chambers thereof, and the posts thereof, and the arches thereof, were according to these measures: and there were windows therein and in the arches thereof round about: it was fifty cubits long, and five and twenty cubits broad.</strong> This verse forms part of Ezekiel's detailed vision of the restored temple, describing the south gate's architectural specifications. The Hebrew term for \"little chambers\" (<em>ta'im</em>, תָּאִים) refers to guard rooms or chambers flanking the gateway, while \"posts\" (<em>elim</em>, אֵילִים) denotes pillars or jambs, and \"arches\" (<em>elamim</em>, אֵלַמִּים) describes porches or vestibules.<br><br>The precise measurements—fifty cubits long (approximately 75 feet) and twenty-five cubits broad (approximately 37.5 feet)—emphasize divine order and perfection. The phrase \"according to these measures\" indicates conformity to the pattern previously described for the east gate, demonstrating symmetry and careful design. The windows provided light and ventilation while maintaining security, combining practical function with symbolic significance representing divine illumination and transparency.<br><br>Theologically, this meticulous architectural description reveals God's attention to detail and the importance of approaching Him according to His prescribed pattern. The symmetry suggests God's unchanging character and impartial justice—the same standards apply to all gates. The vision's overwhelming detail (chapters 40-48 contain extensive measurements) serves multiple purposes: demonstrating God's glory dwelling in precise order, providing hope to exiles of future restoration, foreshadowing the perfect dwelling of God with humanity in the new creation, and establishing that worship must conform to divine revelation rather than human invention.",
                "historical": "Ezekiel received this vision in 573 BCE (the twenty-fifth year of exile, fourteenth year after Jerusalem's destruction) while living among Jewish exiles in Babylon by the Kebar River. The exiles had witnessed Solomon's temple's destruction in 586 BCE—a catastrophic event that seemed to end God's presence among His people. This detailed temple vision provided hope of restoration and continuity with Israel's worship traditions while introducing significant modifications to the Solomonic temple design.<br><br>Ancient Near Eastern temples typically featured elaborate gateways serving both defensive and ceremonial functions. The chambers would house guards controlling access, while the multiple gates and courtyards created progressive stages of holiness as worshipers approached the divine presence. Ezekiel's temple vision shares some features with Solomon's temple and the wilderness tabernacle but includes unique elements never historically constructed—leading to debates about whether this describes a literal future temple or symbolic spiritual realities.<br><br>The vision's precision parallels ancient Near Eastern architectural texts like the Mesopotamian temple building accounts, where gods provided detailed specifications for temple construction. However, unlike pagan temples designed to house idol images, Israel's temple housed God's presence symbolized by the ark of the covenant. The Second Temple (built 515 BCE) and Herod's temple (renovated 20 BCE-63 CE) never fully matched Ezekiel's specifications, suggesting eschatological fulfillment. Christian interpretation sees ultimate fulfillment in Christ (John 2:19-21), the church as God's temple (1 Corinthians 3:16), and the new Jerusalem where God dwells directly with humanity (Revelation 21:22).",
                "questions": [
                    "How does God's attention to precise detail in worship design inform our approach to corporate worship today?",
                    "What do the symmetrical measurements teach us about God's character and His standards for approaching Him?",
                    "How can we balance appreciating Old Testament worship patterns while recognizing their fulfillment in Christ?",
                    "What hope does Ezekiel's vision of restoration offer to believers experiencing spiritual exile or distance from God's manifest presence?",
                    "In what ways does the detailed architectural vision point forward to the new creation where God dwells perfectly with His people?"
                ]
            }
        }
    },
    "Job": {
        "18": {
            "14": {
                "analysis": "<strong>His confidence shall be rooted out of his tabernacle, and it shall bring him to the king of terrors.</strong> Bildad the Shuhite, one of Job's three friends, speaks these words describing the fate of the wicked. The Hebrew word for \"confidence\" (<em>mibtach</em>, מִבְטָח) denotes security, trust, or that in which one places confidence. \"Rooted out\" (<em>nataq</em>, נָתַק) suggests violent tearing away or forcible removal. The \"tabernacle\" (<em>ohel</em>, אֹהֶל) represents one's dwelling place, household, and sphere of security.<br><br>The phrase \"king of terrors\" (<em>melek ballahot</em>, מֶלֶךְ בַּלָּהוֹת) is a powerful metaphor for death personified as a sovereign ruler whose authority inspires dread. Ancient Near Eastern literature personified death (Mot in Canaanite texts) as a powerful deity, though biblical usage strips death of divine status while acknowledging its terrifying power over humanity. Bildad portrays the wicked person's false confidence being stripped away, leaving him defenseless before death's approach.<br><br>Ironically, while Bildad intends this as description of the wicked, it applies to all humanity apart from God's redemption. Every person faces the \"king of terrors\" when earthly securities fail and death looms. The New Testament reveals Christ's victory over death (1 Corinthians 15:55-57; Hebrews 2:14-15), transforming death from \"king of terrors\" to defeated enemy. For believers, Christ removes death's sting, enabling facing mortality without terror. Bildad's theology, while containing truth about sin's consequences, fails to comprehend grace, redemption, and God's purposes in righteous suffering—the very lessons Job's experience would teach.",
                "historical": "The Book of Job is set in the patriarchal period (approximately 2000-1800 BCE) in the land of Uz, likely located in Edom or northern Arabia. Job's friends—Eliphaz, Bildad, and Zophar—represent conventional ancient Near Eastern wisdom traditions that connected suffering directly to personal sin and prosperity to righteousness. This retribution theology permeated ancient cultures and appears in various wisdom literature from Egypt, Mesopotamia, and Canaan.<br><br>Bildad's speech in chapter 18 reflects typical ancient Near Eastern poetic forms using vivid imagery of trap, snare, and terrors to describe the wicked person's fate. The cultural context assumed that premature death, loss of property, and destruction of one's household signaled divine judgment for wickedness. This worldview made Job's suffering particularly scandalous—his catastrophic losses suggested severe sin, yet the book's prologue reveals Job's righteousness (Job 1:1, 8).<br><br>The Book of Job challenges simplistic retribution theology by presenting a righteous sufferer, demonstrating that suffering doesn't always indicate personal sin and that God's purposes transcend human understanding. Ancient readers familiar with retribution theology would find Job's experience profoundly disturbing and thought-provoking. The book's preservation in Scripture validates honest questioning while ultimately affirming God's sovereignty, wisdom, and inscrutability. Historical interpretation shows Job's enduring relevance: every generation faces the problem of innocent suffering and must choose between simplistic formulas and trust in God's mysterious but good purposes.",
                "questions": [
                    "How does Christ's victory over death transform our understanding of death from \"king of terrors\" to defeated enemy?",
                    "What false securities or confidences do we tend to build our lives upon that will ultimately be \"rooted out\"?",
                    "How should we respond to those who, like Bildad, assume suffering always indicates personal sin?",
                    "In what ways does Job's experience challenge simplistic formulas about the relationship between righteousness and blessing?",
                    "How can we cultivate confidence in Christ that enables us to face death without terror?"
                ]
            }
        }
    },
    "Deuteronomy": {
        "33": {
            "25": {
                "analysis": "<strong>Thy shoes shall be iron and brass; and as thy days, so shall thy strength be.</strong> Moses pronounces this blessing upon the tribe of Asher in his final prophetic discourse before his death. The Hebrew words for \"iron\" (<em>barzel</em>, בַּרְזֶל) and \"brass\" (<em>nechosheth</em>, נְחֹשֶׁת) refer to metals symbolizing strength, durability, and security. The \"shoes\" (<em>man'al</em>, מִנְעָל) represent protection for life's journey—the feet bearing the body through varied terrain need reliable covering.<br><br>The metaphor suggests Asher's territory would provide strength and security, possibly referring to mineral resources, military defense, or economic prosperity. Archaeological evidence confirms significant iron and copper production in regions associated with Asher's tribal territory in northern Israel. Beyond literal interpretation, the blessing promises divine enablement for whatever challenges lie ahead—secure foundation and adequate resources for the journey.<br><br>The second phrase, \"as thy days, so shall thy strength be,\" has become a beloved promise throughout church history. The Hebrew construction suggests proportional provision—strength matching need, grace sufficient for each day's trials. This doesn't promise elimination of difficulty but adequate resources to endure it. Theologically, this anticipates New Testament promises of God's sufficient grace (2 Corinthians 12:9) and Christ's yoke being easy and burden light (Matthew 11:30). The blessing teaches dependence on daily divine provision rather than self-sufficiency, trusting God to supply strength matching each day's demands. This principle combats both presumption (assuming strength for tomorrow's trials) and anxiety (fearing inadequacy for future challenges).",
                "historical": "Deuteronomy 33 records Moses's final blessing upon Israel's twelve tribes before his death on Mount Nebo (approximately 1406 BCE). This blessing parallels Jacob's deathbed blessing in Genesis 49, establishing a pattern of patriarchal prophecy guiding tribal identity and destiny. Moses speaks as prophet and covenant mediator, pronouncing divine favor and predicting future circumstances for each tribe.<br><br>Asher's tribal territory was allocated in the fertile coastal region of northern Israel (Joshua 19:24-31), including areas of Phoenician influence. The region's prosperity is confirmed by Jacob's blessing, \"Out of Asher his bread shall be fat, and he shall yield royal dainties\" (Genesis 49:20). Archaeological evidence indicates this area had significant agricultural productivity, trade connections with Phoenician cities, and mineral resources. The blessing's reference to iron and bronze may reflect these natural resources or metalworking industries.<br><br>The historical fulfillment remains somewhat obscure in biblical narrative—Asher isn't prominently featured in conquest accounts or judges period. However, the tribe's endurance and the region's prosperity vindicated Moses's blessing. By the time of Christ, the area (Galilee) became central to Jesus's ministry, with several disciples coming from this region. Christian interpretation sees Moses's blessing finding ultimate fulfillment in Christ, who provides believers with spiritual resources (iron and brass shoes) and daily strength for kingdom service. The blessing's preservation in Scripture transforms a tribal prophecy into a universal promise for all who trust God's provision.",
                "questions": [
                    "How does the promise of daily strength matching daily need address our tendency toward anxiety about the future?",
                    "What \"iron and brass shoes\" has God provided for the specific journey and calling He's given you?",
                    "How can we distinguish between seeking illegitimate security in worldly resources versus gratefully receiving God's material provisions?",
                    "In what ways does this verse challenge both presumption (assuming we have strength for tomorrow) and fear (doubting God's provision)?",
                    "How does understanding God's proportional provision of grace affect how we approach overwhelming circumstances?"
                ]
            }
        }
    },
    "John": {
        "20": {
            "7": {
                "analysis": "<strong>And the napkin, that was about his head, not lying with the linen clothes, but wrapped together in a place by itself.</strong> John records this specific detail about the grave clothes found in Jesus's empty tomb. The Greek word for \"napkin\" (<em>soudarion</em>, σουδάριον) refers to a face cloth or head covering used in Jewish burial customs to bind the jaw shut and cover the face. The linen clothes (<em>othonia</em>, ὀθόνια) were long strips used to wrap the body with spices (John 19:40).<br><br>The significance lies in the careful arrangement: the head cloth was \"wrapped together\" (<em>entetuligmenon</em>, ἐντετυλιγμένον—rolled up or folded) and placed separately from the body wrappings. This detail refutes the theft theory—grave robbers wouldn't waste time carefully arranging burial cloths. The orderly scene suggests Jesus's body passed through the wrappings without disturbing them, leaving the collapsed grave clothes in position while the head cloth remained in its original location, still wrapped but now empty.<br><br>Theologically, this detail demonstrates John's eyewitness testimony—he remembers specific visual details from that transformative morning. The careful arrangement reflects Jesus's sovereignty even in resurrection; this wasn't a frantic escape but a deliberate, ordered departure. Some interpreters see symbolic significance: removing the head covering symbolizes death's defeat, as death could no longer veil Christ's face. The empty, arranged grave clothes testify that Jesus conquered death, rose bodily, and left evidence convincing eyewitnesses of resurrection reality. This small detail carries apologetic weight, supporting resurrection historicity through circumstantial evidence.",
                "historical": "John's Gospel records events of Sunday morning, the first day of the week following Jesus's Friday crucifixion and Saturday Sabbath rest (John 20:1). Jewish burial customs involved washing the body, anointing with spices (myrrh, aloes), wrapping in linen strips, and covering the face with a separate cloth. Joseph of Arimathea and Nicodemus had performed hasty burial preparations before Sabbath began (John 19:38-42), placing Jesus in a new tomb carved from rock.<br><br>Archaeological discoveries of first-century Jewish tombs in Jerusalem confirm burial practices described in the Gospels: stone-cut chambers with benches for body preparation, rolling stones sealing entrances, and ossuaries for secondary burial. The Turin Shroud, while controversial regarding authenticity, demonstrates ancient burial cloth patterns consistent with Gospel accounts. Roman guards had sealed and secured the tomb (Matthew 27:62-66), making the empty tomb and undisturbed grave clothes even more remarkable.<br><br>Early Christian apologetics emphasized resurrection eyewitness testimony, with 1 Corinthians 15:3-8 listing numerous witnesses. The empty tomb and grave clothes became foundational evidence for resurrection preaching. Jewish opponents never produced Jesus's body—instead claiming disciples stole it (Matthew 28:11-15), an explanation contradicted by the arranged grave clothes and disciples' transformation from fearful fugitives to bold martyrs. Church history records countless testimonies of transformed lives based on resurrection reality, flowing from the historical event John witnessed and carefully documented, including this small but significant detail of the folded face cloth.",
                "questions": [
                    "How do small details in resurrection accounts strengthen confidence in the historical reliability of the Gospels?",
                    "What does the orderly arrangement of grave clothes reveal about Jesus's character and the nature of His resurrection?",
                    "How should the physical, bodily resurrection of Jesus affect our understanding of Christian hope for our own resurrection?",
                    "In what ways does resurrection evidence address modern skepticism about Christianity's supernatural claims?",
                    "How can we effectively use historical evidence like the empty tomb and grave clothes in evangelistic conversations?"
                ]
            }
        },
        "13": {
            "18": {
                "analysis": "<strong>I speak not of you all: I know whom I have chosen: but that the scripture may be fulfilled, He that eateth bread with me hath lifted up his heel against me.</strong> Jesus speaks these words during the Last Supper, distinguishing between the faithful eleven and Judas Iscariot. The Greek verb for \"know\" (<em>oida</em>, οἶδα) indicates comprehensive, intimate knowledge—not merely intellectual awareness but deep personal understanding. \"Whom I have chosen\" (<em>exelexamen</em>, ἐξελεξάμην) uses the aorist tense, pointing to a specific past decision, Jesus's sovereign selection of the twelve disciples.<br><br>Jesus quotes Psalm 41:9, where David laments betrayal by a close friend: \"mine own familiar friend, in whom I trusted, which did eat of my bread, hath lifted up his heel against me.\" The phrase \"lifted up his heel\" depicts treacherous attack, like a horse kicking backward to injure. Sharing bread established covenant relationship in ancient culture, making betrayal by a table companion especially heinous. Jesus applies David's experience typologically to Judas's coming betrayal, demonstrating Scripture's prophetic fulfillment in Messiah's sufferings.<br><br>Theologically, this verse addresses the tension between divine sovereignty and human responsibility. Jesus sovereignly chose Judas knowing he would betray Him (John 6:70), yet Judas remained morally responsible for his actions. God's foreknowledge and prophetic Scripture don't negate human agency. The verse also reveals Jesus's omniscience—He knows hearts thoroughly (John 2:25). Despite this knowledge, Jesus shared intimate fellowship with Judas, demonstrating divine patience and giving opportunity for repentance. The fulfillment of Scripture in specific details of Jesus's life validates His messianic identity and God's sovereign orchestration of redemption through human choices, even evil ones.",
                "historical": "This scene occurs during the Last Supper in the upper room in Jerusalem, Thursday evening before Jesus's Friday crucifixion (approximately 30 AD). The meal was likely a Passover celebration or closely associated with Passover, filled with symbolic foods and rituals commemorating Israel's exodus from Egypt. Jesus transforms this meal into the institution of the Lord's Supper, giving new meaning to bread and wine as symbols of His body and blood.<br><br>Jewish meal fellowship carried profound significance in ancient culture, establishing covenant bonds and mutual obligations. Sharing bread with someone created relationship requiring loyalty and protection. Judas's betrayal after eating with Jesus constituted ultimate treachery, violating sacred hospitality bonds. Ancient readers would be shocked by such covenant-breaking. The disciples' response—asking \"Is it I?\" (Matthew 26:22)—reveals their uncertainty and self-examination despite their commitment to Jesus.<br><br>Early church history records Judas's infamy as the archetypal betrayer. Church fathers debated whether Judas could have repented and the extent of his moral culpability given Jesus's foreknowledge. Medieval art depicted Judas at the Last Supper, often without a halo or seated apart from others. The historical reality of Judas's betrayal, predicted in Scripture and fulfilled in detail, became powerful evidence for Jesus's messianic identity and Scripture's reliability. The account warns against superficial discipleship and demonstrates that proximity to Christ without heart transformation leads to destruction rather than salvation.",
                "questions": [
                    "How do we reconcile God's sovereign choice with human moral responsibility in salvation and judgment?",
                    "What does Jesus's patient treatment of Judas despite knowing his betrayal teach about how we should treat those who may harm us?",
                    "How should the fulfillment of Scripture in detailed specifics strengthen our confidence in biblical prophecy?",
                    "In what ways does Judas's betrayal demonstrate the danger of proximity to Christ without genuine heart transformation?",
                    "How can we guard against the self-deception that allowed Judas to betray Jesus while appearing to be a faithful disciple?"
                ]
            }
        }
    },
    "Numbers": {
        "33": {
            "1": {
                "analysis": "<strong>These are the journeys of the children of Israel, which went forth out of the land of Egypt with their armies under the hand of Moses and Aaron.</strong> This verse introduces the detailed itinerary of Israel's wilderness wanderings from Egypt to the plains of Moab. The Hebrew word for \"journeys\" (<em>mas'ei</em>, מַסְעֵי) comes from the root <em>nasa</em> (נָסַע), meaning to pull up tent pegs, to set out, to travel. This suggests organized movement and divinely directed stages rather than aimless wandering.<br><br>\"Went forth out of the land of Egypt\" recalls the exodus, Israel's foundational redemptive event establishing national identity and covenant relationship with Yahweh. The phrase \"with their armies\" (<em>tsiv'otam</em>, צִבְאֹתָם) can also mean \"in their companies\" or \"organized groups,\" depicting orderly departure rather than chaotic flight. This military terminology emphasizes that exodus was divine conquest, Yahweh leading His covenant people as their commander.<br><br>\"Under the hand of Moses and Aaron\" acknowledges dual leadership: Moses as prophet and lawgiver, Aaron as high priest. Their complementary roles foreshadow Christ's combined prophetic and priestly offices. Theologically, the wilderness journey represents the believer's pilgrimage from bondage (Egypt/sin) through sanctification (wilderness testing and teaching) toward promised inheritance (Canaan/eternal rest). Each stage had purpose in God's redemptive plan. The meticulous record demonstrates God's attention to detail, His faithfulness through extended trials, and His providential guidance. The forty-two stations (verses 1-49) remind later generations that seemingly interminable wilderness experiences have divine purpose and will conclude with entrance into God's promises.",
                "historical": "Numbers 33 provides the most complete biblical itinerary of Israel's wilderness wanderings spanning approximately forty years (1446-1406 BCE according to early exodus dating, or 1270-1230 BCE according to late dating). The chapter serves as historical summary near the end of Numbers as Israel camps on the plains of Moab preparing to enter Canaan. Moses writes this record (verse 2) as memorial for future generations, ensuring accurate preservation of this formative period.<br><br>Archaeological and geographical research has attempted to identify the forty-two encampment sites mentioned. Some locations are clearly identified (e.g., Kadesh-barnea, Mount Hor), while others remain uncertain. The route likely followed available water sources and pasturage for the massive population with flocks and herds. Egyptian records and Sinai inscriptions provide some historical context for the period, though direct archaeological evidence of Israel's wilderness sojourn is minimal due to nomadic lifestyle leaving few material remains.<br><br>Ancient Near Eastern peoples maintained travel itineraries for military campaigns, trade routes, and royal journeys. Israel's itinerary served both historical and theological purposes: documenting God's faithful preservation, identifying sacred sites, and establishing property boundaries. Jewish tradition has preserved these place names in liturgy and commentary, while Christian interpretation sees the wilderness journey as typology for Christian pilgrimage. Early church fathers used Israel's journey allegorically for spiritual formation, while Reformation interpreters emphasized historical-grammatical meaning. The historical journey became pattern for understanding God's guidance, testing, provision, and faithfulness during believers' earthly pilgrimage toward heavenly rest.",
                "questions": [
                    "How does understanding our Christian life as a pilgrimage (like Israel's journey) shape our response to trials and delays?",
                    "What do the forty years of wilderness wandering teach us about God's purposes in prolonged seasons of testing?",
                    "How should we respond when our spiritual journey seems to involve circular repetition rather than linear progress?",
                    "In what ways does Israel's organized, staged journey under Moses and Aaron's leadership model proper church order and pastoral guidance?",
                    "How can we cultivate gratitude for God's faithfulness during extended wilderness experiences when we don't yet see the promised land?"
                ]
            }
        }
    }
}

def main():
    merge_commentary_entries(commentaries)

    print("\n✓ Successfully added commentary for 10 verses:")
    print("  - Daniel 4:5")
    print("  - Psalms 6:9")
    print("  - Luke 23:29")
    print("  - Ezekiel 40:33")
    print("  - Job 18:14")
    print("  - Deuteronomy 33:25")
    print("  - John 20:7")
    print("  - John 13:18")
    print("  - Psalms 109:20")
    print("  - Numbers 33:1")
    print(f"\nTotal verses updated: 10")

if __name__ == "__main__":
    main()
