#!/usr/bin/env python3
"""Add comprehensive commentary for 10 specific verses to verse_commentary.json"""

import json
from pathlib import Path

# Define the commentary data for the 10 requested verses
NEW_COMMENTARY = {
    "John": {
        "19": {
            "10": {
                "analysis": "<strong>Then saith Pilate unto him, Speakest thou not unto me? knowest thou not that I have power to crucify thee, and have power to release thee?</strong> Pilate's words reveal his frustration and confusion at Jesus' silence. The Greek word <em>exousia</em> (ἐξουσία) translated \"power\" means \"authority\" or \"right,\" emphasizing Pilate's legal jurisdiction as Roman governor. His double assertion (\"power to crucify... power to release\") underscores both his judicial authority and his expectation that Jesus should plead for mercy.<br><br>Yet Pilate's claim to autonomous power is ironic. While he possessed delegated Roman authority, he was ultimately a pawn in God's sovereign plan of redemption. Jesus' silence fulfills Isaiah 53:7—\"as a sheep before her shearers is dumb, so he openeth not his mouth.\" This silence is not weakness but divine restraint, demonstrating Jesus' voluntary submission to the Father's will.<br><br>Theologically, this verse illuminates the interplay between human authority and divine sovereignty. Pilate represents earthly power structures that appear supreme yet operate only within God's permissive will. Jesus' response in verse 11 clarifies that Pilate's authority is derived, not inherent: \"Thou couldest have no power at all against me, except it were given thee from above.\" This truth comforts believers facing unjust earthly powers—God remains sovereign over all human authority.",
                "historical": "This confrontation occurred during Passover week, approximately AD 30-33, in the Praetorium (governor's headquarters) in Jerusalem. Pilate served as prefect of Judea (AD 26-36) under Emperor Tiberius, responsible for maintaining Roman order and collecting taxes. Historical sources (Josephus, Philo, Tacitus) portray Pilate as cruel and politically insecure, having already provoked Jewish unrest through tactless policies.<br><br>The trial's timing was politically precarious. Pilate feared Jewish riots during Passover, when Jerusalem swelled with pilgrims and messianic expectations ran high. His vacillation between releasing Jesus and appeasing the Jewish leaders reveals his political weakness—he needed cooperation from the Sanhedrin to govern effectively. The threat that he was \"not Caesar's friend\" (John 19:12) likely referenced Sejanus's recent fall from power in Rome (AD 31), making Pilate vulnerable to accusations of disloyalty.<br><br>Roman crucifixion was reserved for slaves, rebels, and non-citizens, serving as public deterrent through prolonged, agonizing death. That Pilate seriously considered crucifying an innocent man reveals both Roman brutality and the political pressures he faced. Archaeological evidence includes the \"Pilate Stone\" discovered in Caesarea (1961), confirming his historical existence and title.",
                "questions": [
                    "How does Pilate's claim to power contrast with Jesus' understanding of true authority, and what does this teach us about earthly versus divine power?",
                    "In what ways does Jesus' silence before Pilate fulfill Old Testament prophecy and demonstrate his voluntary sacrifice?",
                    "How should believers respond when facing unjust earthly authorities, knowing that all power is ultimately derived from God?",
                    "What does this passage reveal about the relationship between political expediency and moral truth?",
                    "How does understanding God's sovereignty over human authority provide comfort and guidance when we face persecution or injustice?"
                ]
            }
        }
    },
    "Jeremiah": {
        "9": {
            "20": {
                "analysis": "<strong>Yet hear the word of the LORD, O ye women, and let your ear receive the word of his mouth, and teach your daughters wailing, and every one her neighbour lamentation.</strong> This verse forms part of Jeremiah's prophecy of imminent judgment upon Judah. The Hebrew imperative <em>shema</em> (שְׁמַעְנָה, \"hear\") demands urgent attention to divine revelation. God directly addresses women, likely because in ancient Near Eastern culture, women led public mourning rituals and passed cultural traditions to the next generation.<br><br>The command to \"teach your daughters wailing\" (<em>nehi</em>, נְהִי—a formal lamentation) and \"neighbour lamentation\" (<em>qinah</em>, קִינָה—a funeral dirge) indicates the magnitude of coming devastation. This wasn't to be ordinary grief but organized, intergenerational mourning. The Hebrew construction suggests professional mourning women would be insufficient—every woman must become skilled in lamentation because death would be so widespread.<br><br>Theologically, this verse underscores God's sovereignty in judgment and the seriousness of covenant unfaithfulness. Yet even in announcing judgment, God shows mercy by warning the people, giving them opportunity to repent. The New Testament application reminds believers that persistent rejection of God's word leads to inevitable judgment, but also that God faithfully warns before He judges (2 Peter 3:9). The verse challenges us to receive God's word seriously, even when it confronts our sin.",
                "historical": "This prophecy dates to approximately 605-586 BC, during the final decades before Babylon's destruction of Jerusalem. Jeremiah ministered during the reigns of Judah's last kings (Josiah, Jehoahaz, Jehoiakim, Jehoiachin, Zedekiah), a period of political instability, religious apostasy, and impending Babylonian invasion. Despite King Josiah's earlier reforms (622 BC), Judah had relapsed into idolatry, social injustice, and false confidence in the temple's presence.<br><br>Ancient Near Eastern mourning customs involved professional mourning women who led public lamentations with stylized crying, tearing garments, wearing sackcloth, and casting dust on heads. These rituals expressed communal grief and sought to move the gods to compassion. Archaeological findings from Mesopotamia and Egypt confirm such practices were widespread. However, Jeremiah's prophecy indicates this coming judgment would exceed normal mourning capacity—every woman would need to learn these skills because professional mourners couldn't handle the scale of death.<br><br>The Babylonian sieges of 597 and 586 BC fulfilled this prophecy terribly. Thousands died from famine, disease, and violence. Lamentations (likely written by Jeremiah) records the unbearable suffering, including cannibalism during the siege. The intergenerational teaching mentioned here proved tragically necessary.",
                "questions": [
                    "Why does God specifically address women in this passage, and what does this reveal about their role in transmitting faith and culture?",
                    "How does this prophecy demonstrate both God's justice in judgment and His mercy in providing warning?",
                    "What parallels can we draw between Judah's rejection of God's word and contemporary society's response to biblical truth?",
                    "How should believers today respond to God's warnings about judgment, both personally and in calling others to repentance?",
                    "In what ways does this passage challenge us to take God's word seriously even when it contains difficult or uncomfortable messages?"
                ]
            }
        },
        "32": {
            "10": {
                "analysis": "<strong>And I subscribed the evidence, and sealed it, and took witnesses, and weighed him the money in the balances.</strong> This verse describes Jeremiah's purchase of a field in Anathoth during Jerusalem's siege by Babylon—a prophetic sign-act demonstrating God's faithfulness to His covenant promises. The Hebrew <em>kahtov basefer</em> (כָּתוֹב בַּסֵּפֶר, \"subscribed the evidence\") refers to signing the legal deed. <em>Va'echtom</em> (וָאֶחְתֹּם, \"sealed it\") involved pressing a clay seal to authenticate the document, protecting it from tampering.<br><br>\"Took witnesses\" (<em>va'a'id edim</em>) follows ancient Near Eastern legal protocols requiring multiple witnesses for property transactions. \"Weighed him the money in the balances\" reflects pre-coinage economies where silver was measured by weight (<em>shekel</em> literally means \"weight\"). This meticulous legal process authenticated Jeremiah's purchase before God and man.<br><br>The theological significance is profound: while Jerusalem faced imminent destruction and exile, God commanded Jeremiah to purchase land—an act of faith in God's promise of restoration. This purchase declared that \"houses and fields and vineyards shall be possessed again in this land\" (Jeremiah 32:15). It demonstrates that true faith trusts God's promises even when circumstances seem hopeless. For believers, this models confident hope in God's ultimate restoration despite present difficulties, pointing forward to Christ's securing our eternal inheritance.",
                "historical": "This event occurred in 587 BC during Nebuchadnezzar's final siege of Jerusalem, months before the city's destruction. Jeremiah was imprisoned in the court of the guard for prophesying Jerusalem's fall—considered treasonous by King Zedekiah. The purchase of family land in Anathoth (Jeremiah's hometown, about 3 miles northeast of Jerusalem) exercised his right of redemption as nearest kinsman (<em>go'el</em>), based on Levitical law (Leviticus 25:25).<br><br>Ancient Near Eastern property transactions followed strict legal protocols. Archaeological discoveries of clay tablets from Mesopotamia, Egypt, and Elephantine show similar procedures: written contracts, sealed copies, witnesses, and measured payment. The \"evidence\" likely consisted of two copies—one sealed (for safekeeping) and one open (for reference), stored in earthen jars for preservation (Jeremiah 32:14), as confirmed by Dead Sea Scroll discoveries.<br><br>The historical context makes Jeremiah's purchase remarkable: Jerusalem was besieged, famine ravaged the city, Babylonian victory was certain, and the land would soon be worthless. Yet Jeremiah's obedience to God's command demonstrated faith that exceeded rational calculation. The Babylonian exile lasted 70 years, after which Judeans did indeed return and repossess their ancestral lands, fulfilling this prophetic sign.",
                "questions": [
                    "How does Jeremiah's purchase of land during a siege demonstrate radical faith in God's promises despite contrary circumstances?",
                    "What does this legal transaction reveal about God's character—His faithfulness to keep covenant promises?",
                    "In what ways does this passage challenge believers to make costly, faith-based decisions that seem foolish by worldly standards?",
                    "How does Jeremiah's role as <em>go'el</em> (redeemer) prefigure Christ's work as our Kinsman-Redeemer?",
                    "What hope does this passage offer believers facing seemingly hopeless situations—whether personal, ecclesial, or cultural?"
                ]
            }
        },
        "36": {
            "3": {
                "analysis": "<strong>It may be that the house of Judah will hear all the evil which I purpose to do unto them; that they may return every man from his evil way; that I may forgive their iniquity and their sin.</strong> This verse reveals God's redemptive heart even in pronouncing judgment. The phrase \"it may be\" (<em>ulay</em>, אוּלַי) doesn't indicate divine uncertainty but rather expresses God's genuine desire for repentance and His respect for human moral agency. God's judgments are never arbitrary but always redemptive in purpose—seeking to turn people from destruction to restoration.<br><br>The Hebrew <em>shuvu</em> (שֻׁבוּ, \"return\") is the key Old Testament word for repentance, meaning to turn around, to reverse direction. It's not mere regret but active turning from \"evil way\" (<em>derek ra'ah</em>) back to God's covenant path. The promise \"that I may forgive\" (<em>v'salachti</em>, וְסָלַחְתִּי) reveals God's eagerness to pardon. Divine forgiveness isn't reluctant or conditional on our merit but flows from God's gracious character when we genuinely repent.<br><br>Theologically, this passage affirms several crucial truths: (1) God warns before He judges, giving opportunity for repentance; (2) genuine repentance involves turning from sin, not just feeling sorry; (3) God desires mercy, not judgment (Ezekiel 33:11); (4) divine forgiveness is comprehensive—\"iniquity and sin\" covers all forms of rebellion. This points forward to Christ, through whom God's desire to forgive finds ultimate expression in the gospel (Acts 3:19; 1 John 1:9).",
                "historical": "This event occurred in 605/604 BC during the fourth year of Jehoiakim's reign. Jeremiah had prophesied for 23 years (since Josiah's 13th year, 627 BC), warning Judah to repent and avoid Babylonian judgment. Despite King Josiah's earlier reforms, his successors led Judah back into idolatry and injustice. Babylon had recently defeated Egypt at Carchemish (605 BC), establishing Nebuchadnezzar's dominance and making Judah a vassal state.<br><br>God commanded Jeremiah to write all his prophecies on a scroll, making them portable and preservable. Since Jeremiah was \"shut up\" (possibly banned from the temple or under house arrest), his scribe Baruch read the scroll publicly during a fast day. The scroll's reading before officials and eventually King Jehoiakim created a moment of decision for the nation.<br><br>Jehoiakim's response was telling: he burned the scroll section by section, showing contempt for God's word. This contrasts dramatically with his father Josiah, who tore his clothes in repentance when hearing God's word (2 Kings 22:11). The burning of God's word symbolized rejection of God Himself. God then commanded Jeremiah to rewrite the scroll with additional judgments. Jehoiakim died in disgrace (probably 598 BC), and Jerusalem fell to Babylon in 586 BC, fulfilling these prophecies.",
                "questions": [
                    "What does God's use of \"it may be\" reveal about His heart toward sinners and His respect for human moral agency?",
                    "How does this verse demonstrate that God's purpose in warning of judgment is redemptive rather than punitive?",
                    "What is the relationship between hearing God's word, repenting from evil ways, and receiving divine forgiveness?",
                    "How does Jehoiakim's rejection of God's word contrast with proper response to divine warning, and what are the consequences of each?",
                    "In what ways does this passage point forward to the gospel message of repentance and forgiveness through Christ?"
                ]
            }
        }
    },
    "Psalms": {
        "109": {
            "26": {
                "analysis": "<strong>Help me, O LORD my God: O save me according to thy mercy:</strong> This urgent cry for divine intervention comes from one of the most intense imprecatory psalms. The Hebrew <em>ezreni</em> (עָזְרֵנִי, \"help me\") and <em>hoshi'eni</em> (הוֹשִׁיעֵנִי, \"save me\") are imperatives expressing desperate dependence on God. The psalmist (traditionally David) faces false accusation and vicious enemies who repay his good with evil and his love with hatred (verses 4-5).<br><br>The address \"O LORD my God\" (<em>Yahweh Elohai</em>) combines God's covenant name (Yahweh) with the personal possessive (\"my God\"), asserting both God's faithfulness to His promises and the psalmist's personal relationship with Him. This dual invocation grounds the appeal in covenant loyalty.<br><br>The phrase \"according to thy mercy\" (<em>k'chasdeka</em>, כְּחַסְדֶּךָ) is crucial—the psalmist appeals not to his own merit but to God's <em>hesed</em> (חֶסֶד), His covenant-keeping love and loyal faithfulness. This mercy-based appeal recognizes that salvation comes through God's gracious character, not human deserving. Theologically, this points forward to salvation by grace through faith in Christ (Ephesians 2:8-9). The psalm's imprecations against enemies ultimately find fulfillment in Christ's judgment against all who oppose God's kingdom, while His mercy saves those who trust Him.",
                "historical": "Psalm 109 is attributed to David, likely composed during persecution by Saul or Absalom's rebellion. David faced repeated false accusations, betrayal by trusted allies, and death threats from those he had befriended. The historical superscription identifies it as \"A Psalm of David,\" and Peter applies verse 8 to Judas Iscariot's betrayal (Acts 1:20), connecting David's experience to Christ's suffering.<br><br>This psalm belongs to the genre of imprecatory psalms (others include Psalms 69, 137, 140), which call down God's judgment on evildoers. Ancient Near Eastern culture understood such curses as invoking divine justice against covenant-breakers and oppressors. While modern readers often find these prayers troubling, they express several important truths: (1) righteous indignation against evil is appropriate; (2) vengeance belongs to God, not personal retaliation; (3) justice demands that wickedness be punished; (4) God's kingdom will ultimately triumph over all opposition.<br><br>The historical context of persecution makes this prayer for help profoundly relevant. David's enemies sought his destruction through slander, false witness, and conspiracy. His appeal to God's mercy rather than his own innocence demonstrates covenant faith. The New Testament shows that David's suffering prefigured Christ's, who also faced false accusation, betrayal, and unjust condemnation, yet committed Himself to God's just judgment (1 Peter 2:23).",
                "questions": [
                    "How does the psalmist's appeal to God's mercy rather than his own merit instruct us in how to approach God in prayer?",
                    "What is the proper role of imprecatory prayers in Christian life—when is it appropriate to call for God's judgment?",
                    "How does David's experience of betrayal and false accusation prefigure Christ's suffering and vindication?",
                    "In what ways does this verse teach us to depend entirely on God when facing unjust opposition?",
                    "How should believers balance trusting God's mercy with seeking His justice against those who oppose His kingdom?"
                ]
            }
        }
    },
    "Daniel": {
        "2": {
            "18": {
                "analysis": "<strong>That they would desire mercies of the God of heaven concerning this secret; that Daniel and his fellows should not perish with the rest of the wise men of Babylon.</strong> This verse reveals Daniel's response to King Nebuchadnezzar's impossible demand—interpret a dream without being told its content. The Aramaic <em>rachamim</em> (רַחֲמִין, \"mercies\") appears in plural form, emphasizing abundant compassion and tender mercy from \"the God of heaven\" (<em>Elah shemaya</em>), a title emphasizing God's sovereignty over earthly kingdoms.<br><br>\"Desire mercies\" translates <em>l'ba'ah rachamim</em>, meaning to seek or request compassionately. Daniel's immediate response to crisis was prayer, specifically corporate prayer with Hananiah, Mishael, and Azariah (Shadrach, Meshach, Abednego). This demonstrates the power and importance of united prayer (Matthew 18:19-20). Daniel didn't rely on his own wisdom or spiritual gifts but wholly depended on God's revelation.<br><br>\"This secret\" (<em>raza</em>, רָזָא) refers to the mystery God alone could reveal. The term later appears in apocalyptic literature for divine mysteries requiring supernatural disclosure. Theologically, this verse teaches: (1) believers should respond to crises with prayer, not panic; (2) corporate prayer strengthens faith; (3) God reveals what humans cannot discover; (4) God's mercy extends even to those in pagan kingdoms. This points to Christ, the ultimate revelation of God's mysteries (Colossians 2:2-3), and the gospel revealed to all nations.",
                "historical": "This event occurred early in Nebuchadnezzar's reign (approximately 603-602 BC), shortly after Daniel and his friends were taken captive to Babylon in 605 BC. Nebuchadnezzar had recently defeated Egypt at Carchemish, establishing Babylonian dominance over the ancient Near East. Daniel and his companions were among the Jewish nobility selected for three years of training in Babylonian language, literature, and wisdom to serve in the king's court.<br><br>Babylonian culture highly valued dream interpretation, consulting professional dream interpreters, astrologers, and magicians. Ancient texts reveal that Babylonian wise men kept extensive dream catalogs with standardized interpretations. However, Nebuchadnezzar's demand to tell both dream and interpretation without hearing the dream first was unprecedented and impossible by human means—exposing the impotence of pagan wisdom.<br><br>The king's decree to execute all wise men (including Daniel's group) reveals his absolute power and volatile temperament. Archaeological and historical records confirm Nebuchadnezzar as a brilliant but ruthless ruler who rebuilt Babylon into the ancient world's most magnificent city. The threat to Daniel and his friends tested whether their faith in Yahweh surpassed mere cultural religion. Their response—seeking God's mercies through prayer—demonstrated genuine covenant faith that trusted God even when facing execution.",
                "questions": [
                    "How does Daniel's immediate turn to prayer in crisis model the proper Christian response to seemingly impossible situations?",
                    "What is the significance of Daniel seeking corporate prayer with his friends rather than praying alone?",
                    "How does this passage demonstrate the superiority of revelation from the God of heaven over human wisdom?",
                    "In what ways does Daniel's situation illustrate believers living faithfully in hostile, pagan cultures?",
                    "How does God's revelation of mysteries to Daniel point forward to Christ as the ultimate revelation of God's wisdom and purposes?"
                ]
            },
            "38": {
                "analysis": "<strong>And wheresoever the children of men dwell, the beasts of the field and the fowls of the heaven hath he given into thine hand, and hath made thee ruler over them all. Thou art this head of gold.</strong> This verse is part of Daniel's interpretation of Nebuchadnezzar's dream. The Aramaic <em>bar-anash</em> (בַּר־אֲנָשׁ, \"children of men\") emphasizes humanity's universality. God's sovereignty extends over all creation—humans, beasts, and birds—and He delegates authority to earthly rulers according to His purposes (Romans 13:1).<br><br>The phrase \"given into thine hand\" reflects the dominion mandate given to Adam (Genesis 1:28), now bestowed upon Nebuchadnezzar as the supreme earthly ruler of his era. However, this authority is derivative, not autonomous—God \"hath made thee ruler,\" establishing that all authority comes from above. \"Thou art this head of gold\" identifies Nebuchadnezzar's Babylonian empire as the first of four kingdoms in the statue vision, emphasizing Babylon's splendor and supremacy among ancient empires.<br><br>Theologically, this verse teaches: (1) God sovereignly establishes and removes earthly kingdoms; (2) human rulers exercise delegated, not inherent, authority; (3) earthly kingdoms are temporary, subject to God's eternal purposes; (4) even pagan rulers unwittingly serve God's plan. This points to Christ's kingdom, the \"stone cut without hands\" (Daniel 2:34-35, 44-45) that will crush all earthly kingdoms and establish God's eternal reign. Jesus is the true King whose authority is absolute and everlasting.",
                "historical": "Nebuchadnezzar II reigned 605-562 BC, transforming Babylon into antiquity's most magnificent city. Archaeological excavations confirm his massive building projects: the Ishtar Gate, Hanging Gardens (one of Seven Wonders), the Processional Way, and ziggurat temples. His empire stretched from the Persian Gulf to the Mediterranean, encompassing Mesopotamia, Syria, Phoenicia, and Judah. The \"head of gold\" aptly describes Babylon's wealth, power, and architectural splendor.<br><br>The dream's statue represented successive empires: gold (Babylon), silver (Medo-Persia), bronze (Greece), iron/clay (Rome and its successors). Each kingdom would be inferior in some aspect to its predecessor. History confirms this prophecy's accuracy: Babylon fell to Medo-Persia (539 BC), which fell to Greece under Alexander (331 BC), which gave way to Rome (63 BC). The prophecy remains partially unfulfilled, awaiting Christ's return to establish God's indestructible kingdom.<br><br>Nebuchadnezzar's response to this interpretation reveals both his greatness and his pride. Though temporarily humbled by the revelation, he later erected a golden image demanding worship (Daniel 3), demonstrating how earthly power corrupts. His subsequent humbling in Daniel 4 (driven to insanity, living like an animal) proved that even the \"head of gold\" must bow before the King of Heaven. This historical pattern warns against pride in human achievement.",
                "questions": [
                    "How does this verse demonstrate God's sovereignty over earthly kingdoms and rulers, and how should this shape our political engagement?",
                    "What is the significance of authority being delegated from God rather than inherent to human rulers?",
                    "How does understanding the temporary nature of earthly kingdoms affect our priorities and loyalties as believers?",
                    "In what ways does Nebuchadnezzar's empire prefigure and contrast with Christ's eternal kingdom?",
                    "What warnings against pride and self-sufficiency can we draw from Nebuchadnezzar's initial exaltation and later humbling?"
                ]
            }
        }
    },
    "Proverbs": {
        "16": {
            "6": {
                "analysis": "<strong>By mercy and truth iniquity is purged: and by the fear of the LORD men depart from evil.</strong> This proverb reveals the twofold means of dealing with sin: divine atonement and human response. The Hebrew <em>chesed</em> (חֶסֶד, \"mercy\") denotes covenant faithfulness and loyal love, while <em>emet</em> (אֱמֶת, \"truth\") signifies reliability, faithfulness, and integrity. Together, these divine attributes accomplish <em>kippur</em> (כִּפֻּר, \"purged\" or \"atoned for\"), the same word used for the Day of Atonement sacrifices that covered sin.<br><br>The verse's structure shows both objective and subjective aspects of salvation: God's mercy and truth provide atonement for sin (objective), while \"the fear of the LORD\" produces moral transformation (subjective). <em>Yirat Yahweh</em> (יִרְאַת יְהוָה, \"fear of the LORD\") means reverential awe, worship, and submission to God's authority. This fear motivates believers to \"depart from evil\" (<em>sur me-ra</em>, סוּר מֵרָע), actively turning away from sin's path.<br><br>Theologically, this proverb anticipates the gospel's full revelation: Christ embodies both God's mercy and truth (John 1:14, 17). His sacrifice provides complete atonement for iniquity (Hebrews 9:14; 1 John 1:7). Yet salvation involves transformation, not just forgiveness—genuine fear of the Lord produces holiness and departure from evil (2 Corinthians 7:1; Titus 2:11-14). This verse refutes both legalism (we cannot purge our own iniquity) and antinomianism (genuine salvation produces moral change).",
                "historical": "Proverbs represents wisdom collected primarily during Solomon's reign (970-930 BC) but compiled later, possibly during Hezekiah's reforms (715-686 BC). Proverbs 16:6 reflects Israel's temple-centered covenant theology, where sacrificial atonement and ethical living were inseparable. The Old Covenant established that sin required blood sacrifice (Leviticus 17:11), while also demanding holiness and justice from God's people (Leviticus 19:2; Micah 6:8).<br><br>Ancient Near Eastern wisdom literature (Egyptian Instruction texts, Mesopotamian proverbs) emphasized moral behavior for pragmatic success but lacked Israel's theological foundation in Yahweh's covenant character. Only Israel's wisdom rooted ethics in relationship with the living God whose mercy atones for sin and whose character defines goodness. The \"fear of the LORD\" as wisdom's beginning (Proverbs 1:7, 9:10) distinguished Israel's wisdom from pagan philosophy.<br><br>Historical context shows the tension between ritual and ethics that the prophets repeatedly addressed (Isaiah 1:11-17; Amos 5:21-24). Mere sacrifice without heart transformation was worthless, yet true fear of the Lord couldn't exist without acknowledging sin's seriousness requiring atonement. Proverbs 16:6 holds these together—God's mercy purges iniquity, and genuine response involves departing from evil. This balance found ultimate expression in Christ's sacrifice establishing the New Covenant.",
                "questions": [
                    "How do God's mercy and truth work together to provide atonement for sin, and how does this point to Christ's work on the cross?",
                    "What is the relationship between receiving forgiveness for sin and being transformed to depart from evil?",
                    "How does \"the fear of the LORD\" function as both the beginning of wisdom and the motivation for holy living?",
                    "In what ways does this proverb refute both legalism (self-purging of iniquity) and antinomianism (mercy without moral transformation)?",
                    "How should understanding God's mercy and truth shape our approach to personal sin and our evangelism to others?"
                ]
            }
        }
    },
    "Ezekiel": {
        "3": {
            "7": {
                "analysis": "<strong>But the house of Israel will not hearken unto thee; for they will not hearken unto me: for all the house of Israel are impudent and hardhearted.</strong> God warns Ezekiel that his prophetic ministry will face stubborn rejection. The Hebrew <em>lo yavu lishmoa</em> (לֹא־יָבוּא לִשְׁמֹעַ, \"will not hearken\") means refusing to listen with intent to obey. This wasn't mere incomprehension but willful defiance. The phrase \"they will not hearken unto me\" reveals that rejection of God's prophet equals rejection of God Himself—a principle Jesus later affirmed (Luke 10:16; John 15:20).<br><br>\"Impudent\" (<em>chazqey-metzach</em>, חִזְקֵי־מֵצַח) literally means \"strong of forehead,\" depicting shameless boldness in sin. \"Hardhearted\" (<em>qshey-lev</em>, קְשֵׁי־לֵב) means obstinate, refusing to be moved by God's word. The forehead represents public demeanor; the heart represents inner will. Together, they describe comprehensive rebellion—external defiance and internal resistance.<br><br>Theologically, this verse addresses: (1) the mystery of human hardness against God despite clear revelation; (2) the cost of faithful prophetic ministry—Ezekiel must speak knowing rejection awaits; (3) God's foreknowledge doesn't negate human responsibility; (4) rejection of God's messengers reveals heart condition. This points to Christ, the ultimate Prophet whom His own people rejected (John 1:11). Yet God's purposes prevail despite human hardness, accomplishing redemption through the very rejection of His Son. Ezekiel's ministry prefigured the gospel's reception—some believe, many reject.",
                "historical": "Ezekiel prophesied among Jewish exiles in Babylon (593-571 BC), having been deported in 597 BC with King Jehoiachin and other nobles. While Jeremiah ministered in Jerusalem to those remaining, Ezekiel addressed the exile community at Tel-abib by the Chebar canal. The exiles maintained false hope for quick return, refusing to acknowledge that their exile resulted from covenant unfaithfulness. False prophets encouraged this delusion (Ezekiel 13), making Ezekiel's message of prolonged exile and Jerusalem's coming destruction unwelcome.<br><br>The phrase \"house of Israel\" encompasses both Judah (southern kingdom) and the northern tribes' descendants, all characterized by rebellion against Yahweh. Israel's history from the Exodus onward showed persistent patterns of idolatry, injustice, and treaty-breaking despite God's patience and repeated warnings through prophets. Ezekiel's call came during this climactic moment of judgment—Jerusalem would fall in 586 BC, fulfilling prophetic warnings.<br><br>Ancient Near Eastern prophets typically enjoyed royal patronage, delivering favorable oracles. Ezekiel's task was different—announce unwelcome judgment to a people convinced of their righteousness because they possessed the temple. Archaeological evidence from Babylonian exile communities shows Israelites maintained ethnic and religious identity but struggled with theological questions about Yahweh's power in a foreign land. Ezekiel's ministry addressed these doubts while calling for genuine repentance rather than false hope.",
                "questions": [
                    "How does this passage explain the reality that faithful proclamation of God's word sometimes results in rejection rather than acceptance?",
                    "What does it mean that the people's rejection of God's prophet equals rejection of God Himself, and how does this apply to Christian witness today?",
                    "How should believers respond when ministering to those characterized as \"impudent and hardhearted\"?",
                    "In what ways does Ezekiel's experience prefigure Christ's rejection and the gospel's mixed reception?",
                    "How does God's foreknowledge of human rejection affect our responsibility to proclaim His truth faithfully?"
                ]
            }
        },
        "33": {
            "31": {
                "analysis": "<strong>And they come unto thee as the people cometh, and they sit before thee as my people, and they hear thy words, but they will not do them: for with their mouth they shew much love, but their heart goeth after their covetousness.</strong> This verse exposes religious hypocrisy in devastating terms. The people attended Ezekiel's prophetic gatherings, appearing to be \"my people\" (God's covenant community), and \"hear thy words\" (<em>shamau</em>, שָׁמְעוּ)—but hearing without obeying reveals false religion. The contrast between external conformity and internal rebellion illustrates what Jesus later condemned as honoring God with lips while hearts remain far from Him (Matthew 15:8, citing Isaiah 29:13).<br><br>\"They will not do them\" (<em>lo ya'asu otam</em>, לֹא יַעֲשׂוּ אֹתָם) reveals the heart of the problem—disconnection between profession and practice, hearing and doing. James 1:22-25 echoes this warning against self-deception through hearing-only religion. \"With their mouth they shew much love\" (<em>agavim rabim</em>, עֲגָבִים רַבִּים) describes emotional expressions of devotion—possibly enthusiastic worship or affirmations of love for God—that mask true heart condition.<br><br>The root problem: \"their heart goeth after their covetousness\" (<em>acharey bitzam libam holek</em>, אַחֲרֵי בִּצְעָם לִבָּם הֹלֵךְ). <em>Betza</em> (בֶּצַע) means unjust gain, greed, profit pursued at others' expense. Covetousness—desiring what belongs to others or prioritizing material gain—reveals idolatry (Colossians 3:5). Theologically, this verse warns that religious activity without heart transformation is worthless before God. True faith produces obedience; genuine love for God surpasses love for wealth.",
                "historical": "This rebuke came during Ezekiel's later ministry (approximately 586-585 BC), after Jerusalem's fall. News of the city's destruction had reached the exiles (Ezekiel 33:21), validating Ezekiel's prophecies and initially increasing his popularity. People gathered to hear him, treating his messages as entertainment or novelty rather than as God's authoritative word requiring obedience. This created a dangerous situation—religious observance without genuine repentance.<br><br>The exile community faced identity crisis: removed from the land, temple destroyed, political independence lost. Some responded with genuine soul-searching and repentance; others maintained external religious forms while pursuing material prosperity in Babylon. Archaeological evidence shows some Jewish exiles achieved economic success in Babylon, particularly in banking and commerce. This prosperity created tension between maintaining covenant faithfulness and adopting Babylonian commercial values.<br><br>Ancient Near Eastern culture recognized similar hypocrisy. Egyptian wisdom texts condemned those who gave lip service to gods while violating ma'at (truth/justice). However, Israel's prophets uniquely emphasized that Yahweh demands heart-level integrity, not mere ritual compliance. The historical context shows that exile should have prompted deep repentance, yet many substituted religious attendance for genuine transformation. This pattern recurred throughout Israel's history and continues in every generation of the church.",
                "questions": [
                    "How does this passage distinguish between genuine faith and religious hypocrisy?",
                    "What does it mean to \"hear\" God's word in the biblical sense, and why is hearing without doing self-deception?",
                    "How does covetousness function as practical idolatry, and what does it reveal about true heart allegiance?",
                    "In what ways might contemporary Christians exhibit this same pattern of outward religious observance with inward covetousness?",
                    "How can believers examine themselves to ensure their worship and profession of love for God align with obedient, transformed lives?"
                ]
            }
        }
    }
}

def update_commentary_json():
    """Update the verse_commentary.json file with new commentary"""
    json_path = Path(__file__).parent.parent / "kjvstudy_org" / "data" / "verse_commentary.json"

    print(f"Reading commentary file: {json_path}")

    # Read existing commentary
    with open(json_path, 'r', encoding='utf-8') as f:
        commentary = json.load(f)

    # Track additions
    additions = []

    # Add new commentary
    for book, chapters in NEW_COMMENTARY.items():
        if book not in commentary:
            commentary[book] = {}

        for chapter, verses in chapters.items():
            if chapter not in commentary[book]:
                commentary[book][chapter] = {}

            for verse, content in verses.items():
                commentary[book][chapter][verse] = content
                additions.append(f"{book} {chapter}:{verse}")
                print(f"Added commentary for {book} {chapter}:{verse}")

    # Write updated commentary
    print(f"\nWriting updated commentary to: {json_path}")
    with open(json_path, 'w', encoding='utf-8') as f:
        json.dump(commentary, f, indent=2, ensure_ascii=False)

    print(f"\n✓ Successfully added commentary for {len(additions)} verses:")
    for ref in additions:
        print(f"  - {ref}")

    return len(additions)

if __name__ == "__main__":
    total = update_commentary_json()
    print(f"\nTotal verses updated: {total}")
